#ParsedReport
*04-04-2022*

Elephant Framework Delivered in Phishing Attacks Against Ukrainian Organizations

https://www.intezer.com/blog/research/elephant-malware-targeting-ukrainian-orgs

*Actors/Campaigns*:
Unc2589 (tags: phishing)

*Threats*:
Graphsteel (tags: stealer, malware, phishing)
Grimplant (tags: malware, backdoor, phishing)
Cobalt\_strike
Elephant\_loader
Babar

*Industry*:
Government, Petroleum, Media

*Geo*:
Romania, Russian, Ukrainian, Turkey, French, Ukraine, Israel

*IOCs*:
File: 3
IP: 1
Url: 1
Hash: 1
Path: 1
Domain: 1

*Links*:
`https://github.com/redcode-labs/Coldfire`
`https://github.com/kerbyj/goLazagne`