#ParsedReport
*16-05-2022*

Rewterz Threat Advisory CVE-2022-28837 Adobe Acrobat and Adobe Reader Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-28837-adobe-acrobat-and-adobe-reader-vulnerability

*CVEs*:
CVE-2022-28837  \[[Vulners](https://vulners.com/cve/CVE-2022-28837)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

