#ParsedReport
*06-05-2022*

Rewterz Threat Advisory Node.js ejs Module and Angular Module Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-node-js-ejs-module-and-angular-module-vulnerabilities

*CVEs*:
CVE-2022-25844  \[[Vulners](https://vulners.com/cve/CVE-2022-25844)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Unavailable

CVE-2022-29078  \[[Vulners](https://vulners.com/cve/CVE-2022-29078)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - ejs (3.1.6)


*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 2

*Links*:
`https://github.com/mde/ejs`