#ParsedReport
*25-04-2022*

Quantum Ransomware

https://thedfirreport.com/2022/04/25/quantum-ransomware

*Actors/Campaigns*:
Xinglocker (tags: ransomware)

*Threats*:
Icedid (tags: ransomware)
Conti (tags: ransomware)
Revil (tags: ransomware)
Cobalt\_strike (tags: ransomware)
Psexec\_tool (tags: ransomware)

*TTPs*:
Tactics: 10
Technics: 18

*IOCs*:
File: 15
Path: 7
Domain: 3
IP: 5
Coin: 1
Hash: 9

*YARA*: Found
*SIGMA*: Found

*Links*:
`https://gist.github.com/0xtornado/69d12572520122cb9bddc2d6793d97ab`