#ParsedReport
*03-05-2022*

Update on cyber activity in Eastern Europe

https://blog.google/threat-analysis-group/update-on-cyber-activity-in-eastern-europe

*Actors/Campaigns*:
Fancy\_bear
Cold\_river
Ghostwriter
Curious\_gorge
Comment\_crew

*Threats*:
Turla

*Industry*:
Petroleum, Government, Ngo, Telco, Logistic, Financial

*Geo*:
Belarusian, Russia, Iran, Korea, Ukraine, Lithuania, Russian, China, Asia

*IOCs*:
File: 1
Hash: 2
Domain: 14
Email: 1

