#ParsedReport
*02-06-2022*

Iranian Threat Actor Continues to Develop Mass Exploitation Tools

https://www.deepinstinct.com/blog/iranian-threat-actor-continues-to-develop-mass-exploitation-tools

*Actors/Campaigns*:
Cleaver
Cobalt\_mirage

*Threats*:
Blister\_loader
Log4shell\_vuln (tags: malware)
Mirage
Plink
Proxyshell\_vuln

*Geo*:
Iranian, Iran

*CVEs*:
CVE-2018-13379  \[[Vulners](https://vulners.com/cve/CVE-2018-13379)]
    Vulners: Score: *5.0*, CVSS: *4.0*, 
    Vulners: Exploitation: True
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix
    Soft:
    - fortinet fortios (le6.0.4, le5.6.7)


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 1
Path: 2
Hash: 34
IP: 7
Domain: 12

*Links*:
`https://github.com/fatedier/frp`