#ParsedReport
*13-04-2022*

Dismantling ZLoader: How malicious ads led to disabled security tools and ransomware

https://www.microsoft.com/security/blog/2022/04/13/dismantling-zloader-how-malicious-ads-led-to-disabled-security-tools-and-ransomware

*Actors/Campaigns*:
Darkside (tags: malware, ransomware)
Blackmatter (tags: malware, ransomware)

*Threats*:
Z\_loader (tags: fraud, proxy, spam, scam, malware, ransomware, rat, trojan, phishing)
Zeus (tags: malware, ransomware)
Cobalt\_strike (tags: malware, ransomware)
Ragnarlocker (tags: malware, ransomware)
Ryuk (tags: malware, ransomware)
Atera\_tool
Psexec\_tool

*Industry*:
Telco, Financial

*Geo*:
China, Japan

*CVEs*:
CVE-2020-1599  \[[Vulners](https://vulners.com/cve/CVE-2020-1599)]
    Vulners: Score: *2.1*, CVSS: *3.9*, 
    Vulners: Exploitation: True
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows 10 (-, 20h2, 1607, 1803, 1809, 1903, 1909, 2004)
    - microsoft windows 7 (-)
    - microsoft windows 8.1 (-)
    - microsoft windows rt 8.1 (-)
    - microsoft windows server 2008 (-, r2)
    have more...
CVE-2012-0151  \[[Vulners](https://vulners.com/cve/CVE-2012-0151)]
    Vulners: Score: *9.3*, CVSS: *7.7*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.3*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows vista (\*, \*)
    - microsoft windows server 2008 (r2, \*, \*, \*, r2)
    - microsoft windows xp (\*, -)
    - microsoft windows 7 (\*, \*)
    - microsoft windows server 2003 (\*)
    have more...
CVE-2013-3900  \[[Vulners](https://vulners.com/cve/CVE-2013-3900)]
    Vulners: Score: *7.6*, CVSS: *7.3*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.3*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows server 2008 (r2, r2, -)
    - microsoft windows 7 (-)
    - microsoft windows rt (-)
    - microsoft windows 8.1 (-)
    - microsoft windows server 2003 (-)
    have more...

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
Domain: 14
Url: 2
File: 16
Path: 1

