#ParsedReport
*13-04-2022*

Rewterz Threat Advisory CVE-2022-28893 Linux Kernel Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-28893-linux-kernel-vulnerability

*CVEs*:
CVE-2022-28893  \[[Vulners](https://vulners.com/cve/CVE-2022-28893)]
    Vulners: Score: *7.2*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix
    Soft:
    - linux linux kernel (le5.17.2)


*TTPs*:
Tactics: 2
Technics: 0

*Links*:
`https://github.com/torvalds/linux/commit/f00432063db1a0db484e85193eccc6845435b80e`