#ParsedReport
*23-05-2022*

Sandworm uses a new version of ArguePatch to attack targets in Ukraine

https://www.welivesecurity.com/2022/05/20/sandworm-ukraine-new-version-arguepatch-malware-loader

*Actors/Campaigns*:
Sandworm (tags: ransomware, malware)

*Threats*:
Arguepatch\_loader (tags: ransomware, malware)
Crashoverride
Killdisk
Hermeticwiper
Hermeticwizard
Partyticket
Isaacwiper

*Industry*:
Energy

*Geo*:
Ukrainian, Ukraines, Ukraine

*IOCs*:
File: 1
Hash: 1

