#ParsedReport
*16-05-2022*

Rewterz Threat Advisory CVE-2022-1417 GitLab Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-1417-gitlab-vulnerability

*CVEs*:
CVE-2022-1417  \[[Vulners](https://vulners.com/cve/CVE-2022-1417)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

