#ParsedReport
*21-05-2022*

Rewterz Threat Alert APT36 Crimson RAT Active IOCs

https://www.rewterz.com/rewterz-news/rewterz-threat-alert-apt36-crimson-rat-active-iocs-2

*Actors/Campaigns*:
Transparenttribe (tags: phishing, rat, malware)

*Threats*:
Crimson\_rat (tags: phishing, rat, malware)
Watering\_hole\_technique

*Industry*:
Healthcare, Government

*Geo*:
India

*CVEs*:
CVE-2017-0199  \[[Vulners](https://vulners.com/cve/CVE-2017-0199)]
    Vulners: Score: *9.3*, CVSS: *9.6*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.3*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows server 2008 (r2, \*)
    - microsoft windows server 2012 (-)
    - microsoft windows vista (\*)
    - microsoft office (2010, 2013, 2016, 2007)
    - microsoft windows 7 (\*)
    have more...

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 1
Hash: 9

