#ParsedReport
*22-05-2022*

Rewterz Threat Alert A PowerShell RAT Targeting German Users Russian-Ukrainian Cyber Warfare Active IOCs

https://www.rewterz.com/rewterz-news/rewterz-threat-alert-a-powershell-rat-targeting-german-users-russian-ukrainian-cyber-warfare-active-iocs

*Threats*:
Bespoke

*Geo*:
German, Ukraine, Ukraines, Russian

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
Domain: 2
File: 2
Hash: 9

