#ParsedReport
*21-04-2022*

Warez users fell for Certishell. Sivpici.php5.sk (2015-2018)

https://decoded.avast.io/danielbenes/warez-users-fell-for-certishell/?utm\_source=rss&utm\_medium=rss&utm\_campaign=warez-users-fell-for-certishell

*Threats*:
Certishell (tags: fraud, ddos, ransomware, rat, malware, keylogger, cryptomining)
Xmrig\_miner (tags: cryptomining)
Vmprotect (tags: cryptomining)
Filecoder
Themida\_packer\_tool (tags: cryptomining)

*Geo*:
Slovakia, Czech

*IOCs*:
Domain: 3
File: 33
Registry: 2
Url: 272
Hash: 554

*Links*:
`https://github.com/monoxgas/sRDI`
`https://github.com/avast/ioc/blob/master/Certishell/samples.sha256`
`https://github.com/avast/ioc/blob/master/Certishell/network.txt`
`https://github.com/avast/ioc/tree/master/Certishell`