#ParsedReport
*19-05-2022*

Chaos Ransomware Variant Sides with Russia

https://www.fortinet.com/blog/threat-research/chaos-ransomware-variant-sides-with-russia

*Threats*:
Chaos (tags: phishing, ransomware, malware)
Conti (tags: ransomware)
Lockbit (tags: ransomware)
Filecoder

*Industry*:
Financial

*Geo*:
Ukrainian, Russia, Russian, Japanese, Ukraine

*TTPs*:
Tactics: 5
Technics: 6

*IOCs*:
File: 1
Hash: 1

