#ParsedReport
*29-05-2022*

Rewterz Threat Advisory Multiple Linux Kernel Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-linux-kernel-vulnerabilities-6

*Threats*:
Lockdown

*CVEs*:
CVE-2022-21499  \[[Vulners](https://vulners.com/cve/CVE-2022-21499)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.1*
    X-Force: Patch: Official fix

CVE-2022-1786  \[[Vulners](https://vulners.com/cve/CVE-2022-1786)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

