#ParsedReport
*04-05-2022*

Operation CuckooBees: A Winnti Malware Arsenal Deep-Dive

https://www.cybereason.com/blog/operation-cuckoobees-a-winnti-malware-arsenal-deep-dive

*Actors/Campaigns*:
Axiom (tags: rootkit, rat, backdoor, proxy, malware)

*Threats*:
Deploylog (tags: rootkit, rat, malware)
Spyder (tags: malware)
Privatelog (tags: rootkit)
Winnkit (tags: rootkit, rat, malware)
Stashlog (tags: malware)
Sparklog
Lolbin
Cryptopp\_tool
Eternal\_petya

*Industry*:
Government

*Geo*:
Chinese

*TTPs*:
Tactics: 4
Technics: 0

*IOCs*:
File: 18
Path: 32
Registry: 1
Hash: 14

*Links*:
`https://github.com/securycore/Ikeext-Privesc`