#ParsedReport
*20-05-2022*

Rewterz Threat Advisory CVE-2022-0005 Intel Software Guard Extensions (SGX) Platform Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-0005-intel-software-guard-extensions-sgx-platform-vulnerability

*CVEs*:
CVE-2022-0005  \[[Vulners](https://vulners.com/cve/CVE-2022-0005)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

