#ParsedReport
*22-05-2022*

Rewterz Threat Advisory Multiple Apple macOS Big Sur and macOS Monterey Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-apple-macos-big-sur-and-macos-monterey-vulnerabilities

*Threats*:
Applescript

*CVEs*:
CVE-2022-26725  \[[Vulners](https://vulners.com/cve/CVE-2022-26725)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.2*
    X-Force: Patch: Official fix

CVE-2022-26693  \[[Vulners](https://vulners.com/cve/CVE-2022-26693)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-26769  \[[Vulners](https://vulners.com/cve/CVE-2022-26769)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix

CVE-2022-26750  \[[Vulners](https://vulners.com/cve/CVE-2022-26750)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26753  \[[Vulners](https://vulners.com/cve/CVE-2022-26753)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26728  \[[Vulners](https://vulners.com/cve/CVE-2022-26728)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-22663  \[[Vulners](https://vulners.com/cve/CVE-2022-22663)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-26727  \[[Vulners](https://vulners.com/cve/CVE-2022-26727)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-26742  \[[Vulners](https://vulners.com/cve/CVE-2022-26742)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26694  \[[Vulners](https://vulners.com/cve/CVE-2022-26694)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-26755  \[[Vulners](https://vulners.com/cve/CVE-2022-26755)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-26746  \[[Vulners](https://vulners.com/cve/CVE-2022-26746)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-26718  \[[Vulners](https://vulners.com/cve/CVE-2022-26718)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix

CVE-2022-26697  \[[Vulners](https://vulners.com/cve/CVE-2022-26697)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.1*
    X-Force: Patch: Official fix

CVE-2022-26752  \[[Vulners](https://vulners.com/cve/CVE-2022-26752)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26741  \[[Vulners](https://vulners.com/cve/CVE-2022-26741)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26749  \[[Vulners](https://vulners.com/cve/CVE-2022-26749)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26775  \[[Vulners](https://vulners.com/cve/CVE-2022-26775)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26754  \[[Vulners](https://vulners.com/cve/CVE-2022-26754)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26772  \[[Vulners](https://vulners.com/cve/CVE-2022-26772)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26722  \[[Vulners](https://vulners.com/cve/CVE-2022-26722)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix

CVE-2022-26715  \[[Vulners](https://vulners.com/cve/CVE-2022-26715)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix

CVE-2022-26776  \[[Vulners](https://vulners.com/cve/CVE-2022-26776)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26743  \[[Vulners](https://vulners.com/cve/CVE-2022-26743)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26756  \[[Vulners](https://vulners.com/cve/CVE-2022-26756)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix

CVE-2022-26770  \[[Vulners](https://vulners.com/cve/CVE-2022-26770)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix

CVE-2022-26712  \[[Vulners](https://vulners.com/cve/CVE-2022-26712)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-26698  \[[Vulners](https://vulners.com/cve/CVE-2022-26698)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.1*
    X-Force: Patch: Official fix

CVE-2022-26723  \[[Vulners](https://vulners.com/cve/CVE-2022-26723)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix

CVE-2022-26704  \[[Vulners](https://vulners.com/cve/CVE-2022-26704)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26720  \[[Vulners](https://vulners.com/cve/CVE-2022-26720)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix

CVE-2022-26748  \[[Vulners](https://vulners.com/cve/CVE-2022-26748)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26708  \[[Vulners](https://vulners.com/cve/CVE-2022-26708)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26767  \[[Vulners](https://vulners.com/cve/CVE-2022-26767)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-26761  \[[Vulners](https://vulners.com/cve/CVE-2022-26761)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 3
Technics: 0

