#ParsedReport
*05-05-2022*

NetDooka Framework Distributed via PrivateLoader Malware as Part of Pay-Per-Install Service. Attack overview

https://www.trendmicro.com/en\_us/research/22/e/netdooka-framework-distributed-via-privateloader-ppi.html

*Threats*:
Netdooka (tags: botnet, backdoor, trojan, malware, dropper, rat, ddos)
Privateloader (tags: botnet, backdoor, trojan, malware, dropper, rat, ddos)
Smokeloader\_backdoor (tags: malware)
Redline\_stealer (tags: malware)
Anubis (tags: malware)
Viper\_rat
Trojan.win32.stop.el
Trojan.win64.protdrive.a
Trojan.win32.vindor.a

*IOCs*:
File: 4
Path: 3
IP: 3
Hash: 38
Url: 5

*Links*:
`https://github.com/microsoft/Windows-driver-samples/tree/master/general/obcallback`
`https://github.com/SweetIceLolly/Prevent\_File\_Deletion`