#ParsedReport
*24-05-2022*

How to Analyze Phishing Email Files

https://www.intezer.com/blog/incident-response/automate-analysis-phishing-email-files

*Threats*:
Emotet (tags: malware)
Trickbot (tags: malware)
Nanocore\_rat (tags: malware)
Agent\_tesla (tags: phishing)
Snake\_keylogger (tags: phishing)
Lokibot\_stealer (tags: phishing)
Formbook (tags: phishing)
Icedid

*Industry*:
Financial, Petroleum, Energy, Government

*Geo*:
Georgia, Ukrainian, Israel

*IOCs*:
File: 2
Domain: 2

*Links*:
`https://github.com/TeamMsgExtractor/msg-extractor`
`https://github.com/diogo-alves/eml-extractor`