#ParsedReport
*24-05-2022*

Yashma Ransomware, Tracing the Chaos Family Tree

https://blogs.blackberry.com/en/2022/05/yashma-ransomware-tracing-the-chaos-family-tree

*Actors/Campaigns*:
Wizard\_spider

*Threats*:
Yashma (tags: malware, ransomware, rat)
Chaos (tags: malware, ransomware, rat)
Onyx (tags: malware, ransomware)
Ryuk (tags: ransomware)

*Industry*:
Healthcare, Financial

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 3
Path: 1
Hash: 14

*YARA*: Found

