#ParsedReport
*26-05-2022*

SpiderLabs Blog. Grandoreiro Banking Malware Resurfaces for Tax Season

https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/grandoreiro-banking-malware-resurfaces-for-tax-season

*Threats*:
Grandoreiro (tags: dns, backdoor, malware, phishing, spam, rat, trojan)
Javali (tags: trojan)
Fake-trusteer (tags: trojan)

*Industry*:
Financial

*Geo*:
Mexico, Spain, Brazil, America, American

*IOCs*:
Url: 4
Path: 1
Registry: 1
Hash: 6
File: 3
Domain: 1
IP: 1

*Links*:
`https://github.com/SpiderLabs/Grandoreiro-decryptor/blob/main/grandoreiro\_string\_decryptor.py`
`https://github.com/SpiderLabs/Grandoreiro-decryptor/blob/main/grandoreiro\_dga\_gen.py`