#ParsedReport
*12-04-2022*

Industroyer2: Industroyer reloaded

https://www.welivesecurity.com/2022/04/12/industroyer2-industroyer-reloaded

*Actors/Campaigns*:
Sandworm

*Threats*:
Crashoverride (tags: rat, trojan, malware)
Killdisk (tags: rat, malware)
Orcshred (tags: malware)
Soloshred (tags: malware)
Awfulshred (tags: malware)
Blackout
Eternal\_petya
Arguepatch\_loader

*Industry*:
Financial, Government, Ics, Energy

*Geo*:
Ukraine, Ukrainian, Russian, Ukraines

*IOCs*:
File: 2
Hash: 7

