#ParsedReport
*13-05-2022*

The Good, The Bad and the Ugly in Cybersecurity Week 20

https://www.sentinelone.com/blog/the-good-the-bad-and-the-ugly-in-cybersecurity-week-20-3

*Threats*:
Acidrain

*Industry*:
Government

*Geo*:
Ukraines, Russian, German, Ukrainian, Ukraine

*CVEs*:
CVE-2022-1388  \[[Vulners](https://vulners.com/cve/CVE-2022-1388)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - f5 big-ip access policy manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip advanced firewall manager (le11.6.5, le12.1.6, <15.1.5.1, <14.1.4.6, <13.1.5, <16.1.2.2)
    - f5 big-ip analytics (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip application acceleration manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip application security manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    have more...

