#ParsedReport
*30-04-2022*

SpiderLabs Blog. Stormous: The Pro-Russian, Clout Hungry Ransomware Gang Targets the US and Ukraine

https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/stormous-the-pro-russian-clout-hungry-ransomware-gang-targets-the-us-and-ukraine

*Actors/Campaigns*:
Lapsus (tags: ransomware)

*Threats*:
Clout\_hungry (tags: ddos, ransomware)

*Industry*:
Financial, Government, Healthcare

*Geo*:
Ukrainian, Saudi, India, Chinese, American, Ukraine, Russian, Russia, Arabia

