#ParsedReport
*16-05-2022*

Rewterz Threat Advisory Multiple Adobe InDesign Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-adobe-indesign-vulnerabilities

*CVEs*:
CVE-2022-28832  \[[Vulners](https://vulners.com/cve/CVE-2022-28832)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-28831  \[[Vulners](https://vulners.com/cve/CVE-2022-28831)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-28833  \[[Vulners](https://vulners.com/cve/CVE-2022-28833)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

