#ParsedReport
*19-04-2022*

BAZARLOADER: Unpacking an ISO File Infection. Step 1: Mounting ISO File & Extracting Stage 1 Executable

https://www.0ffset.net/reverse-engineering/bazarloader-iso-file-infection/?utm\_source=rss&utm\_medium=rss&utm\_campaign=bazarloader-iso-file-infection

*Threats*:
Bazarbackdoor
Metasploit\_tool
Cobalt\_strike

*IOCs*:
File: 4
Hash: 1

*Links*:
`https://github.com/OALabs/hashdb-ida`
`https://github.com/mandiant/flare-emu`
`https://github.com/OALabs/hashdb/blob/b3cc544fad41c749d04616663ac13f02bf1aaf37/algorithms/metasploit.py`
`https://github.com/OALabs/BlobRunner`