#ParsedReport
*22-05-2022*

Rewterz Threat Advisory Multiple NVIDIA GPU Display Driver for Windows and Linux Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-nvidia-gpu-display-driver-for-windows-and-linux-vulnerabilities

*CVEs*:
CVE-2022-28185  \[[Vulners](https://vulners.com/cve/CVE-2022-28185)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.8*
    X-Force: Patch: Official fix

CVE-2022-28184  \[[Vulners](https://vulners.com/cve/CVE-2022-28184)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-28188  \[[Vulners](https://vulners.com/cve/CVE-2022-28188)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-28187  \[[Vulners](https://vulners.com/cve/CVE-2022-28187)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-28182  \[[Vulners](https://vulners.com/cve/CVE-2022-28182)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.5*
    X-Force: Patch: Official fix

CVE-2022-28189  \[[Vulners](https://vulners.com/cve/CVE-2022-28189)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-28186  \[[Vulners](https://vulners.com/cve/CVE-2022-28186)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-28190  \[[Vulners](https://vulners.com/cve/CVE-2022-28190)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-28181  \[[Vulners](https://vulners.com/cve/CVE-2022-28181)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.5*
    X-Force: Patch: Official fix

CVE-2022-28183  \[[Vulners](https://vulners.com/cve/CVE-2022-28183)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.7*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 1

