#ParsedReport
*22-04-2022*

TeamTNT targeting AWS, Alibaba

http://blog.talosintelligence.com/2022/04/teamtnt-targeting-aws-alibaba.html

*Actors/Campaigns*:
Teamtnt (tags: malware, scan, stealer, dns, cryptomining, rat, rootkit)
Chimaera

*Threats*:
Xmrig\_miner
Tsunami\_botnet
Hildegard
Pnscan\_tool
Masscan\_tool
Zgrab\_scanner\_tool

*Industry*:
Financial

*Geo*:
German

*TTPs*:
Tactics: 1
Technics: 7

*IOCs*:
Domain: 2
IP: 10
Url: 12
File: 8
Coin: 5
Email: 1
Hash: 50

*Links*:
`https://github.com/weaveworks/scope/`
`https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz`
`https://github.com/rainbowminer/RainbowMiner`
`https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.31/lolMiner\_v1.31\_Lin64.tar.gz`
`https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/powershell\_7.1.3-1.ubuntu.18.04\_amd64.`