#ParsedReport
*21-04-2022*

Rewterz Threat Advisory Multiple IBM Products Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-ibm-products-vulnerabilities

*CVEs*:
CVE-2021-39072  \[[Vulners](https://vulners.com/cve/CVE-2021-39072)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.9*
    X-Force: Patch: Official fix

CVE-2021-39078  \[[Vulners](https://vulners.com/cve/CVE-2021-39078)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.1*
    X-Force: Patch: Official fix

CVE-2021-39076  \[[Vulners](https://vulners.com/cve/CVE-2021-39076)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.7*
    X-Force: Patch: Official fix

CVE-2021-39033  \[[Vulners](https://vulners.com/cve/CVE-2021-39033)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
IP: 4

