#ParsedReport
*12-04-2022*

SystemBC Being Used by Various Attackers

https://asec.ahnlab.com/en/33600

*Actors/Campaigns*:
Darkside
Pseudomanuscrypt

*Threats*:
Systembc (tags: proxy, spam, malware, ransomware, dropper, scan, rat, stealer, dns)
Smokeloader\_backdoor
Emotet
Rig\_tool
Ryuk
Egregor
Cobalt\_strike
Psexec\_tool
Cryptbot\_stealer
Redline\_stealer
Trojan/win.malpe.r480644
Trojan/win.generic.c5006057
Malware/win32.rl\_generic.r358611
Trojan/win32.agent.c3511593

*Industry*:
Financial

*IOCs*:
File: 5
Hash: 4
Domain: 5
IP: 4
Url: 2

*Links*:
`https://github.com/wbenny/mini-tor`