#ParsedReport
*22-04-2022*

Rewterz Threat Advisory CVE-2022-24858 Node.js next-auth module Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-24858-node-js-next-auth-module-vulnerability

*CVEs*:
CVE-2022-24858  \[[Vulners](https://vulners.com/cve/CVE-2022-24858)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 1

*Links*:
`https://github.com/nextauthjs/next-auth/security/advisories/GHSA-f9wg-5f46-cjmw`