#ParsedReport
*20-05-2022*

Rewterz Threat Advisory CVE-2022-24422 Dell EMC iDRAC9 Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-24422-dell-emc-idrac9-vulnerability

*CVEs*:
CVE-2022-24422  \[[Vulners](https://vulners.com/cve/CVE-2022-24422)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.6*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
IP: 2

