#ParsedReport
*24-05-2022*

Malware Analysis: Trickbot

https://thehackernews.com/2022/05/malware-analysis-trickbot.html

*Actors/Campaigns*:
Wizard\_spider
Shathak

*Threats*:
Trickbot (tags: phishing, scan, ransomware, trojan, malware)
Cobalt\_strike (tags: malware)
Ryuk (tags: malware)
Conti (tags: malware)
Comrade\_circle
Bazarbackdoor

*Industry*:
Financial

*TTPs*:
Tactics: 3
Technics: 0

*IOCs*:
File: 5
Hash: 1
IP: 2

