#ParsedReport
*29-05-2022*

Rewterz Threat Advisory CVE-2022-29246 Microsoft Azure RTOS USBX Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-29246-microsoft-azure-rtos-usbx-vulnerability

*CVEs*:
CVE-2022-29246  \[[Vulners](https://vulners.com/cve/CVE-2022-29246)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

*Links*:
`https://github.com/azure-rtos/usbx/security/advisories/GHSA-hh5p-x584-j8hv`