#ParsedReport
*16-05-2022*

Rewterz Threat Advisory Multiple Microsoft Excel Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-microsoft-excel-vulnerabilities

*CVEs*:
CVE-2022-29109  \[[Vulners](https://vulners.com/cve/CVE-2022-29109)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-29110  \[[Vulners](https://vulners.com/cve/CVE-2022-29110)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

