#ParsedReport
*28-03-2022*

Avast Finds Compromised Philippine Navy Certificate Used in Remote Access Tool

https://decoded.avast.io/threatintel/avast-finds-compromised-philippine-navy-certificate-used-in-remote-access-tool/?utm\_source=rss&utm\_medium=rss&utm\_campaign=avast-finds-compromised-philippine-navy-certificate-used-in-remote-access-tool

*Threats*:
Quasar\_rat

*Geo*:
Philippines, Philippine

*IOCs*:
Domain: 1
Path: 1
Hash: 1
File: 1

*Links*:
`https://github.com/avast/ioc/tree/master/Philippine-Navy-Certificate`