#ParsedReport
*11-04-2022*

Snow abuse and gluttony: Analysis of suspected Lazarus attack activities against Korean companies

https://mp.weixin.qq.com/s/kcIaoB8Yta1zI6Py-uxupA

*Actors/Campaigns*:
Lazarus (tags: malware, phishing)

*Industry*:
Financial

*Geo*:
Asia, Korean

*CVEs*:
CVE-2017-0199  \[[Vulners](https://vulners.com/cve/CVE-2017-0199)]
    Vulners: Score: *9.3*, CVSS: *9.6*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.3*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows server 2008 (r2, \*)
    - microsoft windows server 2012 (-)
    - microsoft windows vista (\*)
    - microsoft office (2010, 2013, 2016, 2007)
    - microsoft windows 7 (\*)
    have more...

*IOCs*:
File: 7
Coin: 1
Hash: 21

