#ParsedReport
*25-05-2022*

Method that Tricks Users to Perceive Attachment of PDF File as Safe File

https://asec.ahnlab.com/en/34707

*Threats*:
Formbook
Lokibot\_stealer
Trojan/win.nsisinject.r491618
Trojan/win.nsisinject.r487995
Trojan/win.generic.r481309

*Geo*:
Korean

*CVEs*:
CVE-2018-0798  \[[Vulners](https://vulners.com/cve/CVE-2018-0798)]
    Vulners: Score: *9.3*, CVSS: *9.3*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *Unknown*
    X-Force: Patch: Unknown
    Soft:
    - microsoft office (2010, 2016, 2016, 2007, 2013)
    - microsoft word (2013, 2016, 2007, 2010, 2013)
    - microsoft office compatibility pack (-)

CVE-2017-0199  \[[Vulners](https://vulners.com/cve/CVE-2017-0199)]
    Vulners: Score: *9.3*, CVSS: *9.6*, 
    Vulners: Exploitation: True
    X-Force: Risk: *Unknown*
    X-Force: Patch: Unknown
    Soft:
    - microsoft windows server 2008 (r2, \*)
    - microsoft windows server 2012 (-)
    - microsoft windows vista (\*)
    - microsoft office (2010, 2013, 2016, 2007)
    - microsoft windows 7 (\*)
    have more...

*IOCs*:
File: 7
Url: 6
Hash: 9

