#ParsedReport
*29-04-2022*

Rewterz Threat Advisory CVE-2022-0540 Atlassian ira Server, Data Center, Jira Service Management Server, and Data Center Seraph Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-0540-atlassian-ira-server-data-center-jira-service-management-server-and-data-center-seraph-vulnerability

*CVEs*:
CVE-2022-0540  \[[Vulners](https://vulners.com/cve/CVE-2022-0540)]
    Vulners: Score: *6.8*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix
    Soft:
    - atlassian jira core (<8.13.8, <8.20.6, <8.22.0)
    - atlassian jira data center (<8.13.8, <8.20.6, <8.22.0)
    - atlassian jira server (<8.13.18, <8.20.6, <8.22.0)
    - atlassian jira service management (<4.13.8, <4.13.18, <4.20.6, <4.20.6, <4.22.0, <4.22.0)


*TTPs*:
Tactics: 1
Technics: 0

