#ParsedReport
*18-04-2022*

Threat Spotlight: Conti Ransomware Group Behind theKarakurt Hacking Team. Threat Spotlight: Conti Ransomware Group Behind the Karakurt Hacking Team

https://www.infinitumit.com.tr/conti-ransomware-group-behind-the-karakurt-hacking-team

*Threats*:
Conti (tags: phishing, ransomware, malware, rat, dns, vpn, proxy)
Cobalt\_strike
Anydesk\_tool
Mimikatz
Metasploit\_tool
Ligolo
Log4shell\_vuln

*Industry*:
Government

*Geo*:
Germany, Canada, Russian

*CVEs*:
CVE-2021-44228  \[[Vulners](https://vulners.com/cve/CVE-2021-44228)]
    Vulners: Score: *9.3*, CVSS: *4.0*, 
    Vulners: Exploitation: True
    X-Force: Risk: *10*
    X-Force: Patch: Official fix
    Soft:
    - apache log4j (2.0, 2.0, 2.0, 2.0, <2.3.1, <2.12.2, <2.15.0)
    - siemens sppa-t3000 ses3000 firmware (\*)
    - siemens captial (<2019.1, 2019.1, 2019.1)
    - siemens comos (\*)
    - siemens desigo cc advanced reports (4.0, 4.1, 4.2, 5.0, 5.1)
    have more...

*TTPs*:
Tactics: 9
Technics: 23

*IOCs*:
Domain: 1
IP: 21
File: 3
Url: 2

*Links*:
`https://github.com/tnpitsecurity/ligolo-ng`
`https://github.com/infinitumitlabs`
`https://github.com/rapid7/metasploit-framework`
`https://github.com/Lozy/danted`
`https://github.com/SecureAuthCorp/impacket`
`https://github.com/infinitumitlabs/Karakurt-Hacking-Team-CTI`