#ParsedReport
*28-04-2022*

LAPSUS$: Recent techniques, tactics and procedures

https://research.nccgroup.com/2022/04/28/lapsus-recent-techniques-tactics-and-procedures

*Actors/Campaigns*:
Lapsus (tags: ransomware, malware, vpn, dns)

*Threats*:
Rvtools\_tool
Adexplorer\_tool

*Industry*:
Financial

*TTPs*:
Tactics: 4
Technics: 15

*IOCs*:
Domain: 1
IP: 3
Url: 1

*Links*:
`https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning`