#ParsedReport
*13-04-2022*

Rewterz Threat Advisory Multiple Google Chrome Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-google-chrome-vulnerabilities-19

*CVEs*:
CVE-2022-1310  \[[Vulners](https://vulners.com/cve/CVE-2022-1310)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1305  \[[Vulners](https://vulners.com/cve/CVE-2022-1305)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1314  \[[Vulners](https://vulners.com/cve/CVE-2022-1314)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1306  \[[Vulners](https://vulners.com/cve/CVE-2022-1306)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1309  \[[Vulners](https://vulners.com/cve/CVE-2022-1309)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1311  \[[Vulners](https://vulners.com/cve/CVE-2022-1311)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1308  \[[Vulners](https://vulners.com/cve/CVE-2022-1308)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1313  \[[Vulners](https://vulners.com/cve/CVE-2022-1313)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1307  \[[Vulners](https://vulners.com/cve/CVE-2022-1307)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1312  \[[Vulners](https://vulners.com/cve/CVE-2022-1312)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

