#ParsedReport
*11-05-2022*

202204

https://blog.netlab.360.com/public-cloud-threat-intelligence-202204

*Threats*:
Cobra
Mirai
Bashlite
Tsunami\_botnet
Kryptik\_trojan

*Industry*:
Financial

*CVEs*:
CVE-2021-2022420  \[[Vulners](https://vulners.com/cve/CVE-2021-2022420)]
CVE-2022-29464  \[[Vulners](https://vulners.com/cve/CVE-2022-29464)]
    Vulners: Score: *10.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - wso2 api manager (le4.0.0)
    - wso2 enterprise integrator (le6.6.0)
    - wso2 identity server (le5.11.0)
    - wso2 identity server analytics (5.4.0, 5.4.1, 5.5.0, 5.6.0)
    - wso2 identity server as key manager (le5.10.0)
    have more...
CVE-2021-31805  \[[Vulners](https://vulners.com/cve/CVE-2021-31805)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.1*
    X-Force: Patch: Official fix
    Soft:
    - apache struts (le2.5.29)


*IOCs*:
File: 1

