#ParsedReport
*23-05-2022*

Metastealer filling the Racoon void. tl;dr

https://research.nccgroup.com/2022/05/20/metastealer-filling-the-racoon-void

*Threats*:
Meta\_stealer (tags: stealer, keylogger, spam, malware)
Raccoon\_stealer (tags: stealer, keylogger, spam, malware)
Hiddenvnc\_tool

*Industry*:
E-commerce

*Geo*:
Israeli

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
IP: 1
File: 5
Path: 3

*YARA*: Found

*Links*:
`https://github.com/yhirose/cpp-httplib`
`https://github.com/Ybalrid/kissnet`
`https://github.com/nlohmann/json`