#ParsedReport
*06-04-2022*

Operation Bearded Barbie: APT-C-23 Campaign Targeting Israeli Officials

https://www.cybereason.com/blog/operation-bearded-barbie-apt-c-23-campaign-targeting-israeli-officials

*Actors/Campaigns*:
Aridviper (tags: ransomware, keylogger, malware, phishing, backdoor)
Molerats

*Threats*:
Barbie (tags: ransomware, keylogger, malware, phishing, backdoor)

*Industry*:
Government, Healthcare

*Geo*:
Israel

*TTPs*:
Tactics: 5
Technics: 0

*IOCs*:
Url: 8
File: 3
Domain: 8
Hash: 22

