#ParsedReport
*29-05-2022*

Rewterz Threat Advisory Multiple Apple Products Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-apple-products-vulnerabilities

*CVEs*:
CVE-2021-30998  \[[Vulners](https://vulners.com/cve/CVE-2021-30998)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4*
    X-Force: Patch: Official fix

CVE-2021-31007  \[[Vulners](https://vulners.com/cve/CVE-2021-31007)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.2*
    X-Force: Patch: Official fix

CVE-2021-31010  \[[Vulners](https://vulners.com/cve/CVE-2021-31010)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix

CVE-2022-26690  \[[Vulners](https://vulners.com/cve/CVE-2022-26690)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.2*
    X-Force: Patch: Official fix

CVE-2021-30956  \[[Vulners](https://vulners.com/cve/CVE-2021-30956)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *2.4*
    X-Force: Patch: Official fix

CVE-2022-22676  \[[Vulners](https://vulners.com/cve/CVE-2022-22676)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.8*
    X-Force: Patch: Official fix

CVE-2021-30943  \[[Vulners](https://vulners.com/cve/CVE-2021-30943)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix

CVE-2022-22672  \[[Vulners](https://vulners.com/cve/CVE-2022-22672)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix

CVE-2021-31009  \[[Vulners](https://vulners.com/cve/CVE-2021-31009)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.2*
    X-Force: Patch: Official fix

CVE-2022-26691  \[[Vulners](https://vulners.com/cve/CVE-2022-26691)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2021-30994  \[[Vulners](https://vulners.com/cve/CVE-2021-30994)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4*
    X-Force: Patch: Official fix

CVE-2021-30999  \[[Vulners](https://vulners.com/cve/CVE-2021-30999)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4*
    X-Force: Patch: Official fix

CVE-2021-30944  \[[Vulners](https://vulners.com/cve/CVE-2021-30944)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4*
    X-Force: Patch: Official fix

CVE-2021-31006  \[[Vulners](https://vulners.com/cve/CVE-2021-31006)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.2*
    X-Force: Patch: Official fix

CVE-2021-30997  \[[Vulners](https://vulners.com/cve/CVE-2021-30997)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.2*
    X-Force: Patch: Official fix

CVE-2021-31000  \[[Vulners](https://vulners.com/cve/CVE-2021-31000)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4*
    X-Force: Patch: Official fix

CVE-2021-31001  \[[Vulners](https://vulners.com/cve/CVE-2021-31001)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2021-30933  \[[Vulners](https://vulners.com/cve/CVE-2021-30933)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2021-30962  \[[Vulners](https://vulners.com/cve/CVE-2021-30962)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4*
    X-Force: Patch: Official fix

CVE-2021-31005  \[[Vulners](https://vulners.com/cve/CVE-2021-31005)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4*
    X-Force: Patch: Official fix

CVE-2021-31008  \[[Vulners](https://vulners.com/cve/CVE-2021-31008)]
    Vulners: Score: *Unknown*, CVSS: *0.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-26688  \[[Vulners](https://vulners.com/cve/CVE-2022-26688)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.4*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 3
Technics: 0

