#ParsedReport
*21-05-2022*

Rewterz Threat Advisory CVE-2022-22393 IBM WebSphere Application Server Liberty Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-22393-ibm-websphere-application-server-liberty-vulnerability

*CVEs*:
CVE-2022-22393  \[[Vulners](https://vulners.com/cve/CVE-2022-22393)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
IP: 2

