#ParsedReport
*22-05-2022*

Rewterz Threat Advisory VMware VMSA-2022-0014 Actively Exploited

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-vmware-vmsa-2022-0014-actively-exploited

*CVEs*:
CVE-2022-22973  \[[Vulners](https://vulners.com/cve/CVE-2022-22973)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-22972  \[[Vulners](https://vulners.com/cve/CVE-2022-22972)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
IP: 3
File: 4

