#ParsedReport
*16-05-2022*

Rewterz Threat Advisory Multiple SAP Host Agent and NetWeaver and ABAP Platform Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-sap-host-agent-and-netweaver-and-abap-platform-vulnerabilities

*CVEs*:
CVE-2022-28774  \[[Vulners](https://vulners.com/cve/CVE-2022-28774)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix

CVE-2022-29616  \[[Vulners](https://vulners.com/cve/CVE-2022-29616)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix

CVE-2022-29611  \[[Vulners](https://vulners.com/cve/CVE-2022-29611)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-29610  \[[Vulners](https://vulners.com/cve/CVE-2022-29610)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.4*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

