#ParsedReport
*18-04-2022*

Rewterz Threat Alert ICS: Johnson Controls Metasys Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-alert-ics-johnson-controls-metasys-vulnerability

*Industry*:
Ics

*CVEs*:
CVE-2021-36205  \[[Vulners](https://vulners.com/cve/CVE-2021-36205)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

