#ParsedReport
*22-05-2022*

Rewterz Threat Advisory CVE-2022-25617 WordPress Code Snippets plugin Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-25617-wordpress-code-snippets-plugin-vulnerability

*CVEs*:
CVE-2022-25617  \[[Vulners](https://vulners.com/cve/CVE-2022-25617)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.7*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

