#ParsedReport
*08-05-2022*

Rewterz Threat Advisory Multiple F5 Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-f5-vulnerabilities

*CVEs*:
CVE-2022-28705  \[[Vulners](https://vulners.com/cve/CVE-2022-28705)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix

CVE-2022-28707  \[[Vulners](https://vulners.com/cve/CVE-2022-28707)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8*
    X-Force: Patch: Official fix

CVE-2022-26415  \[[Vulners](https://vulners.com/cve/CVE-2022-26415)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.7*
    X-Force: Patch: Official fix

CVE-2022-29491  \[[Vulners](https://vulners.com/cve/CVE-2022-29491)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix

CVE-2022-27806  \[[Vulners](https://vulners.com/cve/CVE-2022-27806)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.7*
    X-Force: Patch: Official fix

CVE-2022-25990  \[[Vulners](https://vulners.com/cve/CVE-2022-25990)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix

CVE-2022-26372  \[[Vulners](https://vulners.com/cve/CVE-2022-26372)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix

CVE-2022-29263  \[[Vulners](https://vulners.com/cve/CVE-2022-29263)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-25946  \[[Vulners](https://vulners.com/cve/CVE-2022-25946)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.7*
    X-Force: Patch: Official fix

CVE-2022-27230  \[[Vulners](https://vulners.com/cve/CVE-2022-27230)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix

CVE-2022-28691  \[[Vulners](https://vulners.com/cve/CVE-2022-28691)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix

CVE-2022-28716  \[[Vulners](https://vulners.com/cve/CVE-2022-28716)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix

CVE-2022-1388  \[[Vulners](https://vulners.com/cve/CVE-2022-1388)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - f5 big-ip access policy manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip advanced firewall manager (le11.6.5, <15.1.5.1, <14.1.4.6, <13.1.5, le12.1.6, <16.1.2.2)
    - f5 big-ip analytics (le11.6.5, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5, le12.1.6)
    - f5 big-ip application acceleration manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip application security manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    have more...
CVE-2022-27189  \[[Vulners](https://vulners.com/cve/CVE-2022-27189)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 1

