#ParsedReport
*19-05-2022*

ITG23 Crypters Highlight Cooperation Between Cybercriminal Groups

https://securityintelligence.com/posts/itg23-crypters-cooperation-between-cybercriminal-groups

*Actors/Campaigns*:
Wizard\_spider (tags: malware, trojan, backdoor, proxy, fraud, rat, ransomware, dropper)
Shathak (tags: trojan, ransomware, malware)
Xinglocker (tags: ransomware)
Ta577
Ta570

*Threats*:
Emotet (tags: malware, trojan, backdoor, proxy, ransomware)
Icedid (tags: malware, trojan, backdoor, proxy, ransomware)
Mountlocker (tags: ransomware)
Qakbot (tags: trojan, backdoor, ransomware, malware)
Gozi (tags: trojan, ransomware, malware)
Tron (tags: rat, ransomware)
Skeleton\_operation (tags: rat, ransomware)
Trickbot (tags: ransomware)
Bazarbackdoor (tags: ransomware)
Conti (tags: ransomware)
Colibri\_loader (tags: ransomware)
Anchor
Diavol
Cobalt\_strike (tags: ransomware)
Ryuk
Sliver\_tool
Beacon
Astrolocker (tags: ransomware)
Bumblebee
Netwalker
Zeus
Anubis
Quantum\_locker

*Industry*:
Financial

*Geo*:
Ukrainian

*IOCs*:
File: 4
Hash: 59

*Links*:
`https://github.com/akakist/megatron/)`
`https://github.com/stephenfewer/ReflectiveDLLInjection`
`https://github.com/monoxgas/sRDI`
`https://github.com/BishopFox/sliver`