#ParsedReport
*01-06-2022*

MSDT abused to achieve RCE on Microsoft Office

https://blog.sekoia.io/msdt-abused-to-achieve-rce-on-microsoft-office

*Threats*:
Follina\_vuln
Cobalt\_strike
Beacon
Plugx\_rat
Lolbas\_technique

*Industry*:
Telco

*Geo*:
Chinese, Philippines, Russian, Nepal, Ukraine

*CVEs*:
CVE-2022-30190  \[[Vulners](https://vulners.com/cve/CVE-2022-30190)]

*TTPs*:

*IOCs*:
Hash: 9
File: 4
Domain: 6
Url: 5
IP: 3

*YARA*: Found
*SIGMA*: Found

