#ParsedReport
*05-05-2022*

Shells blooming in Spring

https://labs.k7computing.com/index.php/shells-blooming-in-spring

*Threats*:
Spring4shell (tags: rat)
Log4shell\_vuln (tags: rat)
Mirai
Emotet

*CVEs*:
CVE-2022-22965  \[[Vulners](https://vulners.com/cve/CVE-2022-22965)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - vmware spring framework (<5.2.20, <5.3.18)
    - cisco cx cloud agent (<2.1.0)
    - oracle communications cloud native core automated test suite (1.9.0, 22.1.0)
    - oracle communications cloud native core console (1.9.0, 22.1.0)
    - oracle communications cloud native core network exposure function (22.1.0)
    have more...
CVE-2022-22695  \[[Vulners](https://vulners.com/cve/CVE-2022-22695)]
CVE-2022-22963  \[[Vulners](https://vulners.com/cve/CVE-2022-22963)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - vmware spring cloud function (le3.1.6, le3.2.2)


*IOCs*:
File: 8
Hash: 1

*Links*:
`https://github.com/dinosn/CVE-2022-22963`
`https://github.com/lunasec-io/Spring4Shell-POC`
`https://github.com/reznok/Spring4Shell-POC`