#ParsedReport
*22-05-2022*

Rewterz Threat Advisory CVE-2021-42648 Node.js code-server module Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2021-42648-node-js-code-server-module-vulnerability

*CVEs*:
CVE-2021-42648  \[[Vulners](https://vulners.com/cve/CVE-2021-42648)]
    Vulners: Score: *4.3*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.4*
    X-Force: Patch: Official fix
    Soft:
    - coder code-server (<3.12.0)


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 1

