#ParsedReport
*16-05-2022*

Rewterz Threat Advisory CVE-2022-28819 Adobe Character Animator Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-28819-adobe-character-animator-vulnerability

*CVEs*:
CVE-2022-28819  \[[Vulners](https://vulners.com/cve/CVE-2022-28819)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

