#ParsedReport
*31-03-2022*

Security Advisory: Spring Cloud Framework Vulnerabilities

https://www.zscaler.com/blogs/security-research/security-advisory-spring-cloud-framework-vulnerabilities

*Threats*:
Spring4shell


*CVEs*:
CVE-2022-22963  \[[Vulners](https://vulners.com/cve/CVE-2022-22963)]
    Score: CVSS Unknown, Vulners PENDING, 
    Exploitation: Unknown
    Patch: Official fix

CVE-2022-22965  \[[Vulners](https://vulners.com/cve/CVE-2022-22965)]
    Score: CVSS Unknown, Vulners PENDING, 
    Exploitation: Unknown
    Patch: Official fix


*Links*:
`https://github.com/spring-projects/spring-framework/commit/7f7fb58dd0dae86d22268a4b59ac7c72a6c22529`