*25-03-2022*
Technical Analysis. Zscaler Cloud Sandbox Detection. Conclusion. Indicators of Compromise. Conti Ransomware Attacks Persist With an Updated Version Despite Leaks

https://www.zscaler.com/blogs/security-research/conti-continues-attacks-updated-ransomware-version-despite-leaks

*Threats*:
Conti (ransomware, malware)
Maze

*Geo*:
Ukraine, Ukrainian

*IOCs*:
File: 3
Registry: 1
Path: 1
Hash: 5