#ParsedReport
*02-06-2022*

GoodWill Ransomware? Or Just Another Jasmin Variant?

https://www.netskope.com/blog/goodwill-ransomware-or-just-another-jasmin-variant

*Actors/Campaigns*:
Carbanak (tags: ransomware)

*Threats*:
Goodwill (tags: malware, rat, ransomware, stealer, fraud)
Jasmin (tags: malware, rat, ransomware, stealer, fraud)
Zeus
Hiddentear (tags: ransomware)
Follina\_vuln
Redline\_stealer

*Industry*:
Financial

*CVEs*:
CVE-2022-30190  \[[Vulners](https://vulners.com/cve/CVE-2022-30190)]
    Vulners: Score: *9.3*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows server 2012 (r2, -)
    - microsoft windows 10 (1607, -, 20h2, 1809, 21h1, 21h2)
    - microsoft windows 8.1 (-)
    - microsoft windows server 2016 (-)
    - microsoft windows server 2008 (-, r2)
    have more...

*IOCs*:
File: 4

*YARA*: Found

*Links*:
`https://github.com/netskopeoss/NetskopeThreatLabsIOCs/tree/main/Jasmin%20Ransomware/IOCs`
`https://github.com/codesiddhant/Jasmin-Ransomware`
`https://github.com/netskopeoss/NetskopeThreatLabsIOCs/tree/main/Jasmin%20Ransomware`