#ParsedReport
*16-05-2022*

Rewterz Threat Advisory CVE-2022-29107 Microsoft Office Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-29107-microsoft-office-vulnerability

*CVEs*:
CVE-2022-29107  \[[Vulners](https://vulners.com/cve/CVE-2022-29107)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

