#ParsedReport
*01-06-2022*

Follina: Zero-Day Vulnerability found in MS-MSDT

https://www.netskope.com/blog/follina-zero-day-vulnerability-found-in-ms-msdt

*Threats*:
Follina\_vuln (tags: malware, stealer)
Log4shell\_vuln
Emotet
Redline\_stealer

*Geo*:
Italy, Belarus

*CVEs*:
CVE-2021-40444  \[[Vulners](https://vulners.com/cve/CVE-2021-40444)]
    Vulners: Score: *6.8*, CVSS: *2.1*, 
    Vulners: Exploitation: True
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows 10 (-, 20h2, 21h1, 1607, 1809, 1909, 2004)
    - microsoft windows 7 (-)
    - microsoft windows 8.1 (-)
    - microsoft windows rt 8.1 (-)
    - microsoft windows server 2008 (-, r2)
    have more...
CVE-2022-30190  \[[Vulners](https://vulners.com/cve/CVE-2022-30190)]

*IOCs*:
File: 5
Path: 1
Registry: 2
Hash: 6
Url: 2

