#ParsedReport
*12-05-2022*

RedLine Stealer Campaign Using Binance Mystery Box Videos to Spread GitHub-Hosted Payload

https://www.netskope.com/blog/redline-stealer-campaign-using-binance-mystery-box-videos-to-spread-github-hosted-payload

*Actors/Campaigns*:
Lapsus

*Threats*:
Redline\_stealer (tags: vpn, fraud, malware, phishing, rat, stealer)
Formbook
Emotet

*Industry*:
Financial

*Geo*:
Kyrgyzstan, Russia, Ukrainian, Azerbaijan, Uzbekistan, Belarus, Tajikistan, Ukraine, Armenia, Moldova

*IOCs*:
File: 12

*YARA*: Found

*Links*:
`https://github.com/Zer0Mem0ry/RunPE/blob/master/RunPE.cpp`
`https://github.com/netskopeoss/NetskopeThreatLabsIOCs/tree/main/RedLine%20Stealer`
`https://github.com/netskopeoss/NetskopeThreatLabsIOCs/tree/main/RedLine%20Stealer/IOCs`