#ParsedReport
*23-05-2022*

Rewterz Threat Advisory CVE-2022-20821 Cisco IOS XR Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-20821-cisco-ios-xr-vulnerability

*Industry*:
Healthcare

*CVEs*:
CVE-2022-20821  \[[Vulners](https://vulners.com/cve/CVE-2022-20821)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

