#ParsedReport
*01-06-2022*

SideWinder.AntiBot.Script

https://blog.group-ib.com/sidewinder-antibot

*Actors/Campaigns*:
Sidewinder
Blackmatter

*Threats*:
Mimicry
Comrade\_circle

*Industry*:
Education, Financial, Ngo, Government

*Geo*:
Bhutan, Indian, India, Asia, Pakistan, Afghanistan, Myanmar, Philippines, China, Pakistani, Singapore, Nepal, Bangladesh

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 6
Hash: 5
Url: 464
IP: 89
Domain: 10

