#ParsedReport
*08-05-2022*

Rewterz Threat Advisory Multiple Google Chrome Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-google-chrome-vulnerabilities-20

*Threats*:
Ozone

*CVEs*:
CVE-2022-1483  \[[Vulners](https://vulners.com/cve/CVE-2022-1483)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1492  \[[Vulners](https://vulners.com/cve/CVE-2022-1492)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1499  \[[Vulners](https://vulners.com/cve/CVE-2022-1499)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1490  \[[Vulners](https://vulners.com/cve/CVE-2022-1490)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1480  \[[Vulners](https://vulners.com/cve/CVE-2022-1480)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1498  \[[Vulners](https://vulners.com/cve/CVE-2022-1498)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1489  \[[Vulners](https://vulners.com/cve/CVE-2022-1489)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1497  \[[Vulners](https://vulners.com/cve/CVE-2022-1497)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1482  \[[Vulners](https://vulners.com/cve/CVE-2022-1482)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1488  \[[Vulners](https://vulners.com/cve/CVE-2022-1488)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1478  \[[Vulners](https://vulners.com/cve/CVE-2022-1478)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1493  \[[Vulners](https://vulners.com/cve/CVE-2022-1493)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1494  \[[Vulners](https://vulners.com/cve/CVE-2022-1494)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1496  \[[Vulners](https://vulners.com/cve/CVE-2022-1496)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1479  \[[Vulners](https://vulners.com/cve/CVE-2022-1479)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1481  \[[Vulners](https://vulners.com/cve/CVE-2022-1481)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1500  \[[Vulners](https://vulners.com/cve/CVE-2022-1500)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1477  \[[Vulners](https://vulners.com/cve/CVE-2022-1477)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1495  \[[Vulners](https://vulners.com/cve/CVE-2022-1495)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1491  \[[Vulners](https://vulners.com/cve/CVE-2022-1491)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1484  \[[Vulners](https://vulners.com/cve/CVE-2022-1484)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1487  \[[Vulners](https://vulners.com/cve/CVE-2022-1487)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1501  \[[Vulners](https://vulners.com/cve/CVE-2022-1501)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1486  \[[Vulners](https://vulners.com/cve/CVE-2022-1486)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

