#ParsedReport
*11-05-2022*

New ransomware trends in 2022

https://securelist.com/new-ransomware-trends-in-2022/106457

*Actors/Campaigns*:
Blackmatter

*Threats*:
Conti (tags: ransomware)
Blackcat (tags: ransomware, malware)
Lockbit (tags: ransomware, malware)
Stealbit (tags: ransomware)
Exmatter\_tool (tags: ransomware, malware)
Hermeticwiper
Doublezero (tags: malware)

*Industry*:
Financial, Retail

*Geo*:
Russia, Belarusian, Ukrainian, Ukraine, Russian, African

*IOCs*:
File: 5
Hash: 2

