#ParsedReport
*21-04-2022*

Rewterz Threat Advisory CVE-2021-36828 WP Maintenance plugin for WordPress Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2021-36828-wp-maintenance-plugin-for-wordpress-vulnerability

*CVEs*:
CVE-2021-36828  \[[Vulners](https://vulners.com/cve/CVE-2021-36828)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

