*24-03-2022*
Windows Subsystem for Linux (WSL): Threats Still Lurk Below the (Sub)Surface

https://blog.lumen.com/windows-subsystem-for-linux-wsl-threats/?utm_source=rss&utm_medium=rss&utm_campaign=windows-subsystem-for-linux-wsl-threats

*Threats*:
Keyjeeklogger\_keylogger (keylogger)
Cobalt\_strike (rat)
Telegramrat\_rat

*IOCs*:
File: 2
Email: 1
Registry: 2
Url: 1

*Links*:
https://github.com/Sp00p64/DiscordRAT
https://github.com/3ct0s/discord-keylogger/blob/main/keylogger.py
https://github.com/Bainky/Telegram-RAT
https://github.com/wodxgod/Discord-Token-Grabber/blob/master/token-grabber.py
https://github.com/blacklotuslabs/IOCs/blob/main/WSL\_IoCs\_March2022.txt