#ParsedReport
*08-05-2022*

Rewterz Threat Advisory ICS: Johnson Controls Metasys Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-ics-johnson-controls-metasys-vulnerability

*Industry*:
Ics

*CVEs*:
CVE-2022-21934  \[[Vulners](https://vulners.com/cve/CVE-2022-21934)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

