#ParsedReport
*02-04-2022*

Fresh TOTOLINK Vulnerabilities Picked Up by Beastmode Mirai Campaign

https://www.fortinet.com/blog/threat-research/totolink-vulnerabilities-beastmode-mirai-campaign

*Threats*:
Beastmode\_botnet (tags: ddos, rat, malware, botnet)
Mirai (tags: ddos, rat, malware, botnet)
Dark\_mirai\_botnet

*Industry*:
Iot

*CVEs*:
CVE-2016-5674  \[[Vulners](https://vulners.com/cve/CVE-2016-5674)]
    Vulners: Score: *10.0*, CVSS: *8.5*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.3*
    X-Force: Patch: Unavailable
    Soft:
    - netgear readynas surveillance (1.4.2, 1.4.1, 1.1.1, 1.1.2, 1.3.2.14, 1.2.0.4, 1.3.2.4, 1.4.0)
    - nuuo nvrmini 2 (3.0.0, 2.2.1, 2.0.0, 1.7.6, 1.7.5)
    - nuuo nvrsolo (2.3.9.6, 2.3.7.10, 2.0.0, 1.75, 3.0.0, 2.1.5, 2.0.1, 2.3.7.9, 2.3.1.20, 2.3, 2.2.2)

CVE-2021-4045  \[[Vulners](https://vulners.com/cve/CVE-2021-4045)]
    Vulners: Score: *10.0*, CVSS: *3.7*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Unavailable
    Soft:
    - tp-link tapo c200 firmware (le1.1.15)

CVE-2022-25075  \[[Vulners](https://vulners.com/cve/CVE-2022-25075)]
    Vulners: Score: *7.5*, CVSS: *6.9*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Official fix
    Soft:
    - totolink a3000ru firmware (v5.9c.2280\_b20180512)

CVE-2021-45382  \[[Vulners](https://vulners.com/cve/CVE-2021-45382)]
    Vulners: Score: *10.0*, CVSS: *5.3*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Unavailable
    Soft:
    - dlink dir-820l firmware (-)
    - dlink dir-820lw firmware (-)
    - dlink dir-826l firmware (-)
    - dlink dir-830l firmware (-)
    - dlink dir-836l firmware (-)
    have more...
CVE-2022-26210  \[[Vulners](https://vulners.com/cve/CVE-2022-26210)]
    Vulners: Score: *7.5*, CVSS: *7.1*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Unavailable
    Soft:
    - totolink a830r firmware (5.9c.4729\_b20191112)
    - totolink a3100r firmware (4.1.2cu.5050\_b20200504)
    - totolink a950rg firmware (4.1.2cu.5161\_b20200903)
    - totolink a800r firmware (4.1.2cu.5137\_b20200730)
    - totolink a3000ru firmware (5.9c.5185\_b20201128)
    have more...
CVE-2022-26186  \[[Vulners](https://vulners.com/cve/CVE-2022-26186)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Unavailable
    Soft:
    - totolink n600r firmware (4.3.0cu.7570\_b20200620)

CVE-2017-17215  \[[Vulners](https://vulners.com/cve/CVE-2017-17215)]
    Vulners: Score: *6.5*, CVSS: *6.9*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.8*
    X-Force: Patch: Unavailable
    Soft:
    - huawei hg532 firmware (-)


*IOCs*:
File: 7
Url: 11
IP: 2
Hash: 22

