#ParsedReport
*25-04-2022*

New Core Impact Backdoor Delivered Via VMWare Vulnerability

https://blog.morphisec.com/vmware-identity-manager-attack-backdoor

*Actors/Campaigns*:
Cleaver (tags: backdoor)
Woolen\_goldfish

*Threats*:
Cobalt\_strike (tags: backdoor)
Metasploit\_tool (tags: backdoor)
Powertrash\_tool
Log4shell\_vuln
Jssloader

*Geo*:
London, Iranian

*CVEs*:
CVE-2022-22958  \[[Vulners](https://vulners.com/cve/CVE-2022-22958)]
    Vulners: Score: *6.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.1*
    X-Force: Patch: Official fix
    Soft:
    - vmware cloud foundation (<5.0)
    - vmware identity manager (3.3.3, 3.3.4, 3.3.5, 3.3.6)
    - vmware vrealize automation (7.6, <9.0)
    - vmware vrealize suite lifecycle manager (<9.0)
    - vmware workspace one access (20.10.0.0, 20.10.0.1, 21.08.0.0, 21.08.0.1)
    have more...
CVE-2022-22957  \[[Vulners](https://vulners.com/cve/CVE-2022-22957)]
    Vulners: Score: *6.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.1*
    X-Force: Patch: Official fix
    Soft:
    - vmware cloud foundation (<5.0)
    - vmware identity manager (3.3.3, 3.3.4, 3.3.5, 3.3.6)
    - vmware vrealize automation (7.6, <9.0)
    - vmware vrealize suite lifecycle manager (<9.0)
    - vmware workspace one access (20.10.0.0, 20.10.0.1, 21.08.0.0, 21.08.0.1)
    have more...
CVE-2022-22954  \[[Vulners](https://vulners.com/cve/CVE-2022-22954)]
    Vulners: Score: *10.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - vmware identity manager (3.3.3, 3.3.4, 3.3.5, 3.3.6)
    - vmware vrealize automation (7.6, le8.6)
    - vmware workspace one access (20.10.0.0, 20.10.0.1, 21.08.0.0, 21.08.0.1)
    - vmware cloud foundation (le4.3.1)
    - vmware vrealize suite lifecycle manager (le8.2)
    have more...

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 1
IP: 1
Domain: 2
Url: 1
Hash: 2

