#ParsedReport
*29-05-2022*

Rewterz Threat Advisory CVE-2022-22365 IBM WebSphere Application Server Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-22365-ibm-websphere-application-server-vulnerability

*CVEs*:
CVE-2022-22365  \[[Vulners](https://vulners.com/cve/CVE-2022-22365)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.6*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 1

