#ParsedReport
*22-04-2022*

Rewterz Threat Advisory Multiple Oracle Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-oracle-vulnerabilities-2

*CVEs*:
CVE-2022-21489  \[[Vulners](https://vulners.com/cve/CVE-2022-21489)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.3*
    X-Force: Patch: Official fix

CVE-2022-21433  \[[Vulners](https://vulners.com/cve/CVE-2022-21433)]
CVE-2022-21435  \[[Vulners](https://vulners.com/cve/CVE-2022-21435)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix

CVE-2022-21492  \[[Vulners](https://vulners.com/cve/CVE-2022-21492)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-21488  \[[Vulners](https://vulners.com/cve/CVE-2022-21488)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.8*
    X-Force: Patch: Official fix

CVE-2022-21486  \[[Vulners](https://vulners.com/cve/CVE-2022-21486)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *2.9*
    X-Force: Patch: Official fix

CVE-2022-21436  \[[Vulners](https://vulners.com/cve/CVE-2022-21436)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix

CVE-2022-21453  \[[Vulners](https://vulners.com/cve/CVE-2022-21453)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-21450  \[[Vulners](https://vulners.com/cve/CVE-2022-21450)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.4*
    X-Force: Patch: Official fix

CVE-2022-21454  \[[Vulners](https://vulners.com/cve/CVE-2022-21454)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-21438  \[[Vulners](https://vulners.com/cve/CVE-2022-21438)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix

CVE-2022-21455  \[[Vulners](https://vulners.com/cve/CVE-2022-21455)]
CVE-2022-21484  \[[Vulners](https://vulners.com/cve/CVE-2022-21484)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *2.9*
    X-Force: Patch: Official fix

CVE-2022-21498  \[[Vulners](https://vulners.com/cve/CVE-2022-21498)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-21448  \[[Vulners](https://vulners.com/cve/CVE-2022-21448)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-21441  \[[Vulners](https://vulners.com/cve/CVE-2022-21441)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix

CVE-2022-21461  \[[Vulners](https://vulners.com/cve/CVE-2022-21461)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-21430  \[[Vulners](https://vulners.com/cve/CVE-2022-21430)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.5*
    X-Force: Patch: Official fix

CVE-2022-21457  \[[Vulners](https://vulners.com/cve/CVE-2022-21457)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.9*
    X-Force: Patch: Official fix

CVE-2022-21485  \[[Vulners](https://vulners.com/cve/CVE-2022-21485)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *2.9*
    X-Force: Patch: Official fix

CVE-2022-21459  \[[Vulners](https://vulners.com/cve/CVE-2022-21459)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-21447  \[[Vulners](https://vulners.com/cve/CVE-2022-21447)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-21443  \[[Vulners](https://vulners.com/cve/CVE-2022-21443)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.7*
    X-Force: Patch: Official fix

CVE-2022-21460  \[[Vulners](https://vulners.com/cve/CVE-2022-21460)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.4*
    X-Force: Patch: Official fix

CVE-2022-21458  \[[Vulners](https://vulners.com/cve/CVE-2022-21458)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-21487  \[[Vulners](https://vulners.com/cve/CVE-2022-21487)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.8*
    X-Force: Patch: Official fix

CVE-2022-21427  \[[Vulners](https://vulners.com/cve/CVE-2022-21427)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix

CVE-2022-21497  \[[Vulners](https://vulners.com/cve/CVE-2022-21497)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.1*
    X-Force: Patch: Official fix

CVE-2022-21490  \[[Vulners](https://vulners.com/cve/CVE-2022-21490)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.3*
    X-Force: Patch: Official fix

CVE-2022-21456  \[[Vulners](https://vulners.com/cve/CVE-2022-21456)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-21434  \[[Vulners](https://vulners.com/cve/CVE-2022-21434)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix

CVE-2022-21444  \[[Vulners](https://vulners.com/cve/CVE-2022-21444)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.4*
    X-Force: Patch: Official fix

CVE-2022-21445  \[[Vulners](https://vulners.com/cve/CVE-2022-21445)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix

CVE-2022-21462  \[[Vulners](https://vulners.com/cve/CVE-2022-21462)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix

CVE-2022-21496  \[[Vulners](https://vulners.com/cve/CVE-2022-21496)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix

CVE-2022-21437  \[[Vulners](https://vulners.com/cve/CVE-2022-21437)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix

CVE-2022-21491  \[[Vulners](https://vulners.com/cve/CVE-2022-21491)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-21442  \[[Vulners](https://vulners.com/cve/CVE-2022-21442)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-21494  \[[Vulners](https://vulners.com/cve/CVE-2022-21494)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4*
    X-Force: Patch: Official fix

CVE-2022-21440  \[[Vulners](https://vulners.com/cve/CVE-2022-21440)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-21432  \[[Vulners](https://vulners.com/cve/CVE-2022-21432)]
CVE-2022-21431  \[[Vulners](https://vulners.com/cve/CVE-2022-21431)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *10*
    X-Force: Patch: Official fix

CVE-2022-21446  \[[Vulners](https://vulners.com/cve/CVE-2022-21446)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.2*
    X-Force: Patch: Official fix

CVE-2022-21451  \[[Vulners](https://vulners.com/cve/CVE-2022-21451)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.4*
    X-Force: Patch: Official fix

CVE-2022-21452  \[[Vulners](https://vulners.com/cve/CVE-2022-21452)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix

CVE-2022-21493  \[[Vulners](https://vulners.com/cve/CVE-2022-21493)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.9*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
IP: 3

