#ParsedReport
*20-05-2022*

Rewterz Threat Advisory Multiple Vmware Tanzu Spring Framework Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-vmware-tanzu-spring-framework-vulnerabilities

*Threats*:
Spring4shell

*CVEs*:
CVE-2022-22970  \[[Vulners](https://vulners.com/cve/CVE-2022-22970)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-22971  \[[Vulners](https://vulners.com/cve/CVE-2022-22971)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

