#ParsedReport
*13-05-2022*

Rewterz Threat Advisory CVE-2022-24099 Adobe Photoshop Font Parsing Out-Of-Bounds Read Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-24099-adobe-photoshop-font-parsing-out-of-bounds-read-vulnerability

*CVEs*:
CVE-2022-24099  \[[Vulners](https://vulners.com/cve/CVE-2022-24099)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

