#ParsedReport
*20-05-2022*

Why Remediation Alone Is Not Enough When Infected by Malware

https://asec.ahnlab.com/en/34549

*Actors/Campaigns*:
Darkside (tags: malware)

*Threats*:
Cobalt\_strike (tags: malware)
Runminer
Reverserdp\_technique
Dropper/win.agent
Dropper/win32.agent
Nbtscan\_tool
Malware/win64.generic
Win\_loader

*Geo*:
Korean

*CVEs*:
CVE-2017-10271  \[[Vulners](https://vulners.com/cve/CVE-2017-10271)]
    Vulners: Score: *5.0*, CVSS: *4.9*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - oracle weblogic server (10.3.6.0.0, 12.2.1.1.0, 12.1.3.0.0, 12.2.1.2.0)


*IOCs*:
IP: 6
File: 4
Hash: 21

