#ParsedReport
*02-05-2022*

Analysis on recent wiper attacks: examples and how wiper malware works

https://cybersecurity.att.com/blogs/labs-research/analysis-on-recent-wiper-attacks-examples-and-how-they-wiper-malware-works

*Actors/Campaigns*:
Sandworm

*Threats*:
Whisperkill (tags: malware)
Hermeticwiper (tags: malware)
Isaacwiper (tags: malware)
Killdisk (tags: malware)
Doublezero (tags: malware)
Acidrain (tags: malware)
Log4shell\_vuln
Whispergate
Hermeticwizard
Vpnfilter
Crashoverride

*Industry*:
Energy, Financial, Ics, Government

*Geo*:
Ukrainian, Ukraine, Ukranian

*TTPs*:

*IOCs*:
Path: 1
Hash: 11

