#ParsedReport
*29-03-2022*

From the Front Lines \| Hive Ransomware Deploys Novel IPfuscation Technique To Avoid Detection

https://www.sentinelone.com/blog/hive-ransomware-deploys-novel-ipfuscation-technique

*Threats*:
Hive (tags: backdoor, malware, ransomware, rat)
Cobalt\_strike (tags: malware, rat)
Lolbin (tags: ransomware)
Bloodhound\_tool
Hellsgate\_technique (tags: rat)

*TTPs*:
Tactics: 1
Technics: 10

*IOCs*:
Hash: 38
Path: 2
IP: 6
Domain: 2

*YARA*: Found

*Links*:
`https://github.com/am0nsec/HellsGate`