#ParsedReport
*22-05-2022*

Rewterz Threat Advisory CVE-2021-22573 Google OAuth Client Library for Java Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2021-22573-google-oauth-client-library-for-java-vulnerability

*CVEs*:
CVE-2021-22573  \[[Vulners](https://vulners.com/cve/CVE-2021-22573)]
    Vulners: Score: *3.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix
    Soft:
    - google oauth client library for java (<1.33.3)


*TTPs*:
Tactics: 1
Technics: 0

*Links*:
`https://github.com/googleapis/google-oauth-java-client/pull/872`