#ParsedReport
*17-04-2022*

Rewterz Threat Advisory CVE-2022-1280 Linux Kernel Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-1280-linux-kernel-vulnerability

*CVEs*:
CVE-2022-1280  \[[Vulners](https://vulners.com/cve/CVE-2022-1280)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

