#ParsedReport
*08-05-2022*

Rewterz Threat Advisory Mozilla Thunderbird Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-mozilla-thunderbird-vulnerabilities

*CVEs*:
CVE-2022-1520  \[[Vulners](https://vulners.com/cve/CVE-2022-1520)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-29913  \[[Vulners](https://vulners.com/cve/CVE-2022-29913)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

