#ParsedReport
*19-04-2022*

Rewterz Threat Advisory ICS: Siemens SIMATIC Energy Manager Basic and SIMATIC Energy Manager PRO Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-ics-siemens-simatic-energy-manager-basic-and-simatic-energy-manager-pro-vulnerabilities

*Industry*:
Energy, Ics

*CVEs*:
CVE-2022-23449  \[[Vulners](https://vulners.com/cve/CVE-2022-23449)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Official fix

CVE-2022-23448  \[[Vulners](https://vulners.com/cve/CVE-2022-23448)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Official fix

CVE-2022-23450  \[[Vulners](https://vulners.com/cve/CVE-2022-23450)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *10*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

