#ParsedReport
*13-04-2022*

Rewterz Threat Advisory Multiple WordPress Plugin Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-wordpress-plugin-vulnerabilities-2

*CVEs*:
CVE-2022-1153  \[[Vulners](https://vulners.com/cve/CVE-2022-1153)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-0953  \[[Vulners](https://vulners.com/cve/CVE-2022-0953)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

