#ParsedReport
*06-05-2022*

Mobile subscription Trojans and their little tricks

https://securelist.com/mobile-subscription-trojans-and-their-tricks/106412

*Threats*:
Jocker (tags: trojan, malware)
Vesub (tags: trojan, malware)
Triada
Joker (tags: trojan)

*Industry*:
E-commerce, Financial

*Geo*:
Russia, Arabia, Russian, Indonesia, Austria, China, Brazil, Saudi, Switzerland, Mexico, Turkey, Egypt, Poland, India, Germany, Africa, Thailand, Belarus, Algeria, Ukraine, Arab, Malaysia, Oman

*IOCs*:
File: 4
Hash: 37

