#ParsedReport
*11-05-2022*

Putting Things in Context \| Timelining Threat Campaigns

https://www.sentinelone.com/labs/putting-things-in-context-timelining-threat-campaigns

*Actors/Campaigns*:
Modified\_elephant
Axiom

*Threats*:
Acidrain

*Industry*:
Education

*Geo*:
Ukraine

*Links*:
`https://github.com/SentineLabs/aeon/blob/main/Ukranian\_conflict.aeon`
`https://github.com/SentineLabs/aeon/blob/main/SentinelLabs\_ThreatResearch.aeonTpl`