#ParsedReport
*27-04-2022*

Industroyer2: Nozomi Networks Labs Analyzes the IEC 104 Payload

https://www.nozominetworks.com/blog/industroyer2-nozomi-networks-labs-analyzes-the-iec-104-payload

*Actors/Campaigns*:
Sandworm

*Threats*:
Crashoverride (tags: rat, ransomware, scan, malware)
Botenago
Incontroller\_tool
Log4shell\_vuln

*Industry*:
Iot, Energy

*Geo*:
Ukraines, Ukrainian

*IOCs*:
File: 6
Path: 1
Hash: 2

*YARA*: Found

