#ParsedReport
*22-04-2022*

Rewterz Threat Alert Cobalt Strike Beacon Active IOCs Russian-Ukrainian Cyber Warfare

https://www.rewterz.com/rewterz-news/rewterz-threat-alert-cobalt-strike-beacon-active-iocs-russian-ukrainian-cyber-warfare

*Actors/Campaigns*:
Leviathan

*Threats*:
Cobalt\_strike (tags: malware, rat, ransomware)
Metasploit\_tool
Mimikatz

*Geo*:
Ukraine

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 9
Domain: 1
IP: 4
Hash: 6
Url: 2

