#ParsedReport
*02-06-2022*

To HADES and Back: UNC2165 Shifts to LOCKBIT to Evade Sanctions

https://www.mandiant.com/resources/unc2165-shifts-to-evade-sanctions

*Actors/Campaigns*:
Silverfish (tags: trojan, rat, dns, malware, ransomware, vpn, dropper)
Evil\_corp (tags: trojan, rat, malware, ransomware, vpn)
Unc1543
Gold\_winter
Unc2758

*Threats*:
Hades (tags: trojan, rat, dns, malware, ransomware, vpn, dropper)
Lockbit (tags: trojan, rat, dns, malware, ransomware, vpn, dropper)
Blister\_loader
Dridex
Wastedlocker
Cridex
Friedex
Doppelpaymer
Beacon
Phoenix\_locker
Macaw
Fakeudpate
Netsupportmanager\_rat
Cobalt\_strike
Donut
Mimikatz
Kerberoasting\_technique
Keethief\_tool
Secretserversecretstealer
Putty\_tool
Megasync\_tool
Psexec\_tool
Timestomp\_tool
Domain\_fronting\_technique

*Industry*:
Government, Financial

*Geo*:
Russia

*TTPs*:
Tactics: 13
Technics: 85

*IOCs*:
Domain: 17
File: 1
Path: 1

*YARA*: Found

*Links*:
`https://github.com/TheWover/donut`