#ParsedReport
*19-04-2022*

Rewterz Threat Advisory CVE-2022-21803 Node.js nconf module Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-21803-node-js-nconf-module-vulnerability

*CVEs*:
CVE-2022-21803  \[[Vulners](https://vulners.com/cve/CVE-2022-21803)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 2

*Links*:
`https://github.com/indexzero/nconf/pull/397`