#ParsedReport
*13-04-2022*

Enemybot: A Look into Keksec's Latest DDoS Botnet

https://www.fortinet.com/blog/threat-research/enemybot-a-look-into-keksecs-latest-ddos-botnet

*Actors/Campaigns*:
Keksec

*Threats*:
Enemybot (tags: botnet, cryptomining, ddos, rat, malware)
Bashlite (tags: botnet, ddos)
Mirai
Beastmode\_botnet
Log4shell\_vuln

*Industry*:
Iot

*CVEs*:
CVE-2021-41773  \[[Vulners](https://vulners.com/cve/CVE-2021-41773)]
    Vulners: Score: *4.3*, CVSS: *4.4*, 
    Vulners: Exploitation: True
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix
    Soft:
    - apache http server (2.4.49)
    - fedoraproject fedora (34, 35)
    - oracle instantis enterprisetrack (17.1, 17.2, 17.3)
    - netapp cloud backup (-)

CVE-2017-18368  \[[Vulners](https://vulners.com/cve/CVE-2017-18368)]
    Vulners: Score: *10.0*, CVSS: *3.1*, 
    Vulners: Exploitation: True
    X-Force: Risk: *7.3*
    X-Force: Patch: Unavailable
    Soft:
    - billion 5200w-t firmware (7.3.8.0)
    - zyxel p660hn-t1a v2 firmware (7.3.15.0)
    - zyxel p660hn-t1a v1 firmware (7.3.15.0)

CVE-2020-17456  \[[Vulners](https://vulners.com/cve/CVE-2020-17456)]
    Vulners: Score: *7.5*, CVSS: *7.0*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Unavailable
    Soft:
    - seowonintech slc-130 firmware (-)
    - seowonintech slr-120s firmware (-)

CVE-2022-27226  \[[Vulners](https://vulners.com/cve/CVE-2022-27226)]
    Vulners: Score: *9.3*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8*
    X-Force: Patch: Unavailable
    Soft:
    - irz ru21 firmware (le2022-03-16)
    - irz ru21w firmware (le2022-03-16)
    - irz rl21 firmware (le2022-03-16)
    - irz ru41 firmware (le2022-03-16)
    - irz rl01 firmware (le2022-03-16)
    have more...
CVE-2022-25075  \[[Vulners](https://vulners.com/cve/CVE-2022-25075)]
    Vulners: Score: *7.5*, CVSS: *6.9*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Official fix
    Soft:
    - totolink a3000ru firmware (v5.9c.2280\_b20180512)

have more...


*IOCs*:
Hash: 28
File: 12
Url: 19
Domain: 1
