#ParsedReport
*26-04-2022*

ASEC Weekly Malware Statistics (April 18th, 2022 April 24th, 2022)

https://asec.ahnlab.com/en/33798

*Threats*:
Agent\_tesla (tags: malware)
Formbook (tags: malware)
Lokibot\_stealer (tags: malware)
Beamwinhttp\_loader (tags: malware)
Garbage\_cleaner (tags: malware)
Snake\_keylogger (tags: malware)

*Industry*:
Financial, Transport

*Geo*:
Korea

*IOCs*:
Domain: 5
IP: 5
Email: 10
File: 33
Url: 16

