#ParsedReport
*08-05-2022*

Rewterz Threat Advisory CVE-2022-27854 WordPress Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-27854-wordpress-vulnerability

*CVEs*:
CVE-2022-27854  \[[Vulners](https://vulners.com/cve/CVE-2022-27854)]
    Vulners: Score: *3.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.4*
    X-Force: Patch: Unavailable
    Soft:
    - wp-testing project wp-testing (le0.21.19)


*TTPs*:
Tactics: 1
Technics: 0

