#ParsedReport
*04-05-2022*

Old Services, New Tricks: Cloud Metadata Abuse by UNC2903

https://www.mandiant.com/resources/cloud-metadata-abuse-unc2903

*Actors/Campaigns*:
Unc2903 (tags: scan, rat, malware, proxy, vpn)

*Industry*:
Financial

*CVEs*:
CVE-2021-21311  \[[Vulners](https://vulners.com/cve/CVE-2021-21311)]
    Vulners: Score: *6.4*, CVSS: *4.5*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix
    Soft:
    - adminer (<4.7.9)
    - debian debian linux (9.0)

CVE-2019-0211  \[[Vulners](https://vulners.com/cve/CVE-2019-0211)]
    Vulners: Score: *7.2*, CVSS: *3.9*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.2*
    X-Force: Patch: Official fix
    Soft:
    - apache http server (le2.4.38)
    - fedoraproject fedora (29, 30)
    - canonical ubuntu linux (16.04, 18.04, 18.10, 14.04)
    - debian debian linux (9.0)
    - opensuse leap (42.3, 15.0)
    have more...

*TTPs*:
Tactics: 5
Technics: 6

*IOCs*:
IP: 5
Url: 3
File: 3
Coin: 3
Hash: 1

*Links*:
`https://github.com/duo-labs/cloudmapper`
`https://github.com/latacora/remediate-AWS-IMDSv1`
`https://github.com/vrana/adminer/security/advisories/GHSA-x5r2-hj5c-8jx6`
`https://github.com/salesforce/metabadger`
`https://github.com/prowler-cloud/prowler/blob/master/checks/check\_extra786`