#ParsedReport
*31-05-2022*

caution! Microsoft Office Zero-Day Vulnerability Follina (CVE-2022-30190)

https://asec-ahnlab-com.translate.goog/ko/34919/?\_x\_tr\_sl=auto&\_x\_tr\_tl=en&\_x\_tr\_hl=ru&\_x\_tr\_pto=wapp

*Threats*:
Follina\_vuln (tags: malware)

*CVEs*:
CVE-2022-30190  \[[Vulners](https://vulners.com/cve/CVE-2022-30190)]

*IOCs*:
File: 3
Registry: 1
Url: 1
Hash: 2

*Functions Names*: 1

