#ParsedReport
*08-05-2022*

Rewterz Threat Advisory Multiple Linux Kernel Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-linux-kernel-vulnerabilities-5

*Threats*:
Toctou\_vuln
Darkshades

*CVEs*:
CVE-2022-29799  \[[Vulners](https://vulners.com/cve/CVE-2022-29799)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-29800  \[[Vulners](https://vulners.com/cve/CVE-2022-29800)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

