#ParsedReport
*22-05-2022*

Rewterz Threat Advisory Multiple Apache Tika Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-apache-tika-vulnerabilities

*CVEs*:
CVE-2022-25169  \[[Vulners](https://vulners.com/cve/CVE-2022-25169)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-30126  \[[Vulners](https://vulners.com/cve/CVE-2022-30126)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

