#ParsedReport
*02-06-2022*

Clipminer Botnet Makes Operators at Least $1.7 Million

https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/clipminer-bitcoin-mining-hijacking

*Threats*:
Clipminer (tags: malware, scan, botnet, trojan, cryptomining, rat, dropper)
Kryptocibule (tags: malware)
Xmrig\_miner

*Industry*:
Financial

*IOCs*:
File: 5
Hash: 4
Path: 3
Registry: 4
IP: 2

*Functions Names*: 1

