#ParsedReport
*05-05-2022*

Mustang Panda deploys a new wave of malware targeting Europe

http://blog.talosintelligence.com/2022/05/mustang-panda-targets-europe.html

*Actors/Campaigns*:
Red\_delta (tags: trojan, rat, phishing, malware)

*Threats*:
Meterpreter\_tool (tags: rat, malware)
Plugx\_rat (tags: rat, malware)
Cobalt\_strike
Bespoke (tags: rat, malware)
Lolbas\_technique

*Industry*:
Telco, Government, Ngo

*Geo*:
Russia, Mongolia, Afghan, Japanese, Ukraine, Asia, Tibet, Japan, Taiwan, Ukrainian, Belarus, Myanmar, Greece, Russian, Indian, American, Asian

*IOCs*:
File: 14
IP: 28
Path: 5
Registry: 1
Hash: 114
Domain: 1
Url: 44

