#ParsedReport
*21-05-2022*

Rewterz Threat Advisory CVE-2022-30138 Microsoft Windows Print Spooler Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-30138-microsoft-windows-print-spooler-vulnerability

*CVEs*:
CVE-2022-30138  \[[Vulners](https://vulners.com/cve/CVE-2022-30138)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

