#ParsedReport
*29-03-2022*

Transparent Tribe campaign uses new bespoke malware to target Indian government officials

http://blog.talosintelligence.com/2022/03/transparent-tribe-new-campaign.html

*Actors/Campaigns*:
Transparenttribe (tags: vpn, rat, trojan, malware)
Sidecopy
Armor\_piercer

*Threats*:
Crimson\_rat (tags: rat, keylogger, malware)
Oblique\_rat
Capra\_rat
Margulasrat\_rat

*Industry*:
Media, Government

*Geo*:
India, Indian, Pakistan, Afghanistan

*IOCs*:
Domain: 7
Hash: 36
IP: 6
Url: 19

