#ParsedReport
*23-05-2022*

ASEC Weekly Malware Statistics (May 9th, 2022 May 15th, 2022)

https://asec.ahnlab.com/en/34624

*Threats*:
Agent\_tesla (tags: malware)
Formbook (tags: malware)
Lokibot\_stealer (tags: malware)
Avemaria\_rat (tags: malware)
Redline\_stealer (tags: malware)
Beamwinhttp\_loader (tags: malware)

*Industry*:
Financial, Transport

*Geo*:
Korea

*IOCs*:
Domain: 4
IP: 8
Email: 6
File: 27
Url: 18

