#ParsedReport
*09-05-2022*

The InQuest Insider Issue #44 - I got root in Russia

https://inquest.net/newsletter/2022/05/inquest-insider-issue-44-i-got-root-russia

*Threats*:
Dridex
Emotet

*Geo*:
Russia

*CVEs*:
CVE-2021-40444  \[[Vulners](https://vulners.com/cve/CVE-2021-40444)]
    Vulners: Score: *6.8*, CVSS: *2.1*, 
    Vulners: Exploitation: True
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows 10 (-, 20h2, 21h1, 1607, 1809, 1909, 2004)
    - microsoft windows 7 (-)
    - microsoft windows 8.1 (-)
    - microsoft windows rt 8.1 (-)
    - microsoft windows server 2008 (-, r2)
    have more...

