#ParsedReport
*28-04-2022*

New APT Group Earth Berberoka Targets Gambling Websites With Old and New Malware. Technical analysis

https://www.trendmicro.com/en\_us/research/22/d/new-apt-group-earth-berberoka-targets-gambling-websites-with-old.html

*Actors/Campaigns*:
Earth\_berberoka (tags: rat, dropper, proxy, malware, backdoor)

*Threats*:
Gh0st\_rat (tags: malware)
Plugx\_rat (tags: malware)
Puppetloader (tags: malware)
Tigerplug
Basicloader
Quasar\_rat
Asyncrat\_rat

*IOCs*:
Hash: 1
File: 12
Path: 1

*Links*:
`https://github.com/denji/golang-tls`
`https://github.com/lucas-clemente/quic-go`