#ParsedReport
*08-05-2022*

Rewterz Threat Advisory Multiple NVIDIA Jetson Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-nvidia-jetson-vulnerabilities

*CVEs*:
CVE-2022-28197  \[[Vulners](https://vulners.com/cve/CVE-2022-28197)]
    Vulners: Score: *4.6*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5*
    X-Force: Patch: Official fix
    Soft:
    - nvidia jetson linux (<32.7.2)

CVE-2022-28194  \[[Vulners](https://vulners.com/cve/CVE-2022-28194)]
    Vulners: Score: *4.4*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Official fix
    Soft:
    - nvidia jetson linux (<32.7.2)

CVE-2022-28196  \[[Vulners](https://vulners.com/cve/CVE-2022-28196)]
    Vulners: Score: *3.6*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.7*
    X-Force: Patch: Official fix
    Soft:
    - nvidia jetson linux (<32.7.2)

CVE-2022-28195  \[[Vulners](https://vulners.com/cve/CVE-2022-28195)]
    Vulners: Score: *4.6*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.7*
    X-Force: Patch: Official fix
    Soft:
    - nvidia jetson linux (<32.7.2)

CVE-2022-28193  \[[Vulners](https://vulners.com/cve/CVE-2022-28193)]
    Vulners: Score: *4.6*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Official fix
    Soft:
    - nvidia jetson linux (<32.7.2)


*TTPs*:
Tactics: 1
Technics: 0

