#ParsedReport
*31-05-2022*

Staying Ahead of CVE-2022-30190 (Follina)

https://www.sentinelone.com/blog/staying-ahead-of-cve-2022-30190-follina

*Threats*:
Follina\_vuln (tags: malware)
Log4shell\_vuln
Beacon

*Geo*:
Ukraine, Russian, Belarus, Chinese

*CVEs*:
CVE-2022-30190  \[[Vulners](https://vulners.com/cve/CVE-2022-30190)]

*IOCs*:
Hash: 2
Domain: 2
IP: 1
Registry: 2
File: 5

*Functions Names*: 1

