#ParsedReport
*29-05-2022*

Rewterz Threat Advisory CVE-2022-22977 VMware Tools for Windows Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-22977-vmware-tools-for-windows-vulnerability

*CVEs*:
CVE-2022-22977  \[[Vulners](https://vulners.com/cve/CVE-2022-22977)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.8*
    X-Force: Patch: Official fix

CVE-2022-27588  \[[Vulners](https://vulners.com/cve/CVE-2022-27588)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - qnap qvr (le5.1.6)


*TTPs*:
Tactics: 1
Technics: 0

