#ParsedReport
*02-06-2022*

Zero-Day Exploitation of Atlassian Confluence

https://www.volexity.com/blog/2022/06/02/zero-day-exploitation-of-atlassian-confluence

*Threats*:
Chinachopper (tags: rat, vpn)
Meterpreter\_tool
Cobalt\_strike

*Geo*:
China

*CVEs*:
CVE-2022-26134  \[[Vulners](https://vulners.com/cve/CVE-2022-26134)]
    Vulners: Score: *Unknown*, CVSS: *Unknown*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *Unknown*
    X-Force: Patch: Unknown


*IOCs*:
File: 2
IP: 15
Hash: 2

*Links*:
`https://github.com/volexity/threat-intel/blob/main/2022/2022-06-02%20Active%20Exploitation%20Of%20Confluence%200-day/indicators/indicators.csv`
`https://github.com/tennc/webshell/blob/master/caidao-shell/%E8%8F%9C%E5%88%80jsp%E4%BF%AE%E6%94%B9.jsp`
`https://github.com/Freakboy/Behinder`
`https://github.com/volexity/threat-intel/blob/main/2022/2022-06-02%20Active%20Exploitation%20Of%20Confluence%200-day/indicators/yara.yar`