#ParsedReport
*21-04-2022*

Threat Assessment: BlackByte Ransomware

https://unit42.paloaltonetworks.com/blackbyte-ransomware

*Threats*:
Blackbyte (tags: proxy, spyware, rat, malware, ransomware, dns)
Proxyshell\_vuln (tags: ransomware)
Lockbit
Cobalt\_strike (tags: ransomware)

*Industry*:
Energy, E-commerce, Financial, Ics

*Geo*:
America, Asia, Africa, Australia, Canada, Russian, Apac, Japan, Emea

*CVEs*:
CVE-2021-34473  \[[Vulners](https://vulners.com/cve/CVE-2021-34473)]
    Vulners: Score: *10.0*, CVSS: *6.4*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.1*
    X-Force: Patch: Official fix
    Soft:
    - microsoft exchange server (2013, 2016, 2016, 2019, 2019)

CVE-2021-34523  \[[Vulners](https://vulners.com/cve/CVE-2021-34523)]
    Vulners: Score: *7.5*, CVSS: *6.4*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9*
    X-Force: Patch: Official fix
    Soft:
    - microsoft exchange server (2013, 2016, 2016, 2019, 2019)

CVE-2021-31207  \[[Vulners](https://vulners.com/cve/CVE-2021-31207)]
    Vulners: Score: *6.5*, CVSS: *2.8*, 
    Vulners: Exploitation: True
    X-Force: Risk: *6.6*
    X-Force: Patch: Official fix
    Soft:
    - microsoft exchange server (2013, 2016, 2016, 2019, 2019)


*TTPs*:
Tactics: 10
Technics: 17

*IOCs*:
IP: 7
Domain: 1
File: 9
Registry: 1
Coin: 1

*Links*:
`https://github.com/SpiderLabs/BlackByteDecryptor`