#ParsedReport
*27-04-2022*

Assembling the Russian Nesting Doll: UNC2452 Merged into APT29

https://www.mandiant.com/resources/unc2452-merged-into-apt29

*Actors/Campaigns*:
Darkhalo (tags: proxy, dns, backdoor, phishing, malware)
Duke (tags: proxy, dns, backdoor, phishing, malware)

*Threats*:
Cobalt\_strike
Sunburst
Domain\_fronting\_technique
Raindrop\_tool
Teardrop\_tool
Mamadogs\_tool
Crimsonbox\_tool
Guardrails\_tool
Dcsync\_technique
Kerberoasting\_technique

*Industry*:
Government, Telco, Education, Healthcare

*Geo*:
Russian, Asia, America, Russia

*TTPs*:
Tactics: 12
Technics: 55

