#ParsedReport
*31-03-2022*

Analysis of BlackGuard - a new info stealer malware being sold in a Russian hacking forum

https://www.zscaler.com/blogs/security-research/analysis-blackguard-new-info-stealer-malware-being-sold-russian-hacking

*Threats*:
Blackguard\_stealer (tags: cryptomining, vpn, ransomware, malware, phishing, stealer)
Exodus
Terra\_stealer

*Industry*:
Financial, E-commerce

*Geo*:
Russian

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 2
Hash: 10

