#ParsedReport
*14-04-2022*

Rewterz Threat Advisory Multiple SAP Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-sap-vulnerabilities-3

*CVEs*:
CVE-2022-26107  \[[Vulners](https://vulners.com/cve/CVE-2022-26107)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-27654  \[[Vulners](https://vulners.com/cve/CVE-2022-27654)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-27667  \[[Vulners](https://vulners.com/cve/CVE-2022-27667)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix

CVE-2022-26109  \[[Vulners](https://vulners.com/cve/CVE-2022-26109)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-26106  \[[Vulners](https://vulners.com/cve/CVE-2022-26106)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-27655  \[[Vulners](https://vulners.com/cve/CVE-2022-27655)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-26105  \[[Vulners](https://vulners.com/cve/CVE-2022-26105)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-26108  \[[Vulners](https://vulners.com/cve/CVE-2022-26108)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-27657  \[[Vulners](https://vulners.com/cve/CVE-2022-27657)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *2.7*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

