#ParsedReport
*22-04-2022*

Hive Ransomware Analysis

https://www.varonis.com/blog/hive-ransomware-analysis

*Threats*:
Hive (tags: backdoor, ransomware, scan, phishing, malware, vpn)
Proxyshell\_vuln (tags: backdoor, malware)
Cobalt\_strike (tags: malware)
Mimikatz
Log4shell\_vuln
Emotet
Icedid
Qakbot
Conti

*Industry*:
Energy, Healthcare, Retail

*Geo*:
Netherlands, Usa

*CVEs*:
CVE-2021-34523  \[[Vulners](https://vulners.com/cve/CVE-2021-34523)]
    Vulners: Score: *7.5*, CVSS: *6.4*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9*
    X-Force: Patch: Official fix
    Soft:
    - microsoft exchange server (2013, 2016, 2016, 2019, 2019)

CVE-2021-34473  \[[Vulners](https://vulners.com/cve/CVE-2021-34473)]
    Vulners: Score: *10.0*, CVSS: *6.4*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.1*
    X-Force: Patch: Official fix
    Soft:
    - microsoft exchange server (2013, 2016, 2016, 2019, 2019)

CVE-2021-31207  \[[Vulners](https://vulners.com/cve/CVE-2021-31207)]
    Vulners: Score: *6.5*, CVSS: *2.8*, 
    Vulners: Exploitation: True
    X-Force: Risk: *6.6*
    X-Force: Patch: Official fix
    Soft:
    - microsoft exchange server (2013, 2016, 2016, 2019, 2019)


*TTPs*:
Tactics: 10
Technics: 19

*IOCs*:
File: 7
IP: 4
Registry: 1
Hash: 7

*Links*:
`https://github.com/ThePacketBender/webshells`