#ParsedReport
*19-05-2022*

Space Pirates:

https://www.ptsecurity.com/ru-ru/research/pt-esc-threat-intelligence/space-pirates-tools-and-connections

*Actors/Campaigns*:
Spacepirates (tags: dropper, dns, phishing, rat, proxy, backdoor)
Axiom
Emissary\_panda
Ta428
Red\_delta
Redfoxtrot
Stealthytrident
Nightscout
Lazarus

*Threats*:
Former\_first\_rat
Plugx\_rat (tags: dropper, rat, backdoor)
9002 (tags: rat)
Pcshare
Poison\_ivy
Shadowpad
Revbshell
Albaniiutas\_rat
Hyperbro
Smokeloader\_backdoor
Bluetraveller\_rat
Reactorbot
Gh0st\_rat (tags: rat)

*Geo*:
Japanese

*CVEs*:
CVE-2017-0213  \[[Vulners](https://vulners.com/cve/CVE-2017-0213)]
    Vulners: Score: *1.9*, CVSS: *6.4*, 
    Vulners: Exploitation: True
    X-Force: Risk: *7*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows 10 (1607, -, 1511, 1703)
    - microsoft windows rt 8.1 (\*)
    - microsoft windows server 2012 (-, r2)
    - microsoft windows server 2008 (r2, \*)
    - microsoft windows 8.1 (\*)
    have more...

*TTPs*:
Tactics: 10
Technics: 54

*IOCs*:
File: 50
Path: 20
Email: 1
IP: 23
Hash: 156
Registry: 8

*Links*:
`https://github.com/bitsadmin/ReVBShell`
`https://github.com/LiveMirror/pcshare`
`https://github.com/vzex/dog-tunnel`
`https://github.com/obfuscator-llvm/obfuscator/wiki/Control-Flow-Flattening`