#ParsedReport
*19-05-2022*

Space Pirates: Explore the tools and connections of a new hacker group

https://www.ptsecurity.com/ru-ru/research/pt-esc-threat-intelligence/space-pirates-tools-and-connections

*Actors/Campaigns*:
Spacepirates (tags: dropper, malware, dns, backdoor, rat, phishing, proxy)
Axiom
Emissary\_panda
Ta428
Red\_delta
Redfoxtrot
Stealthytrident
Nightscout

*Threats*:
Zupdax (tags: rat)
Former\_first\_rat
Climax\_loader
Rtlshare
Plugx\_rat (tags: backdoor, dropper)
9002 (tags: rat)
Deed\_rat (tags: dns, rat)
Pcshare
Poison\_ivy
Shadowpad
Revbshell
Tmanger
Albaniiutas\_rat
Bluetraveller\_rat
Hyperbro
Smokeloader\_backdoor
Reactorbot
Gh0st\_rat
Chromepass\_tool

*Industry*:
Aerospace, Financial, Government, Energy

*Geo*:
Russian, Asian, Chinese, Russia, Mongolia, Georgia, Japanese

*CVEs*:
CVE-2017-0213  \[[Vulners](https://vulners.com/cve/CVE-2017-0213)]
    Vulners: Score: *1.9*, CVSS: *6.4*, 
    Vulners: Exploitation: True
    X-Force: Risk: *7*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows 10 (1607, -, 1511, 1703)
    - microsoft windows rt 8.1 (\*)
    - microsoft windows server 2012 (-, r2)
    - microsoft windows server 2008 (r2, \*)
    - microsoft windows 8.1 (\*)
    have more...

*TTPs*:
Tactics: 10
Technics: 54

*IOCs*:
File: 51
Path: 20
Email: 1
IP: 23
Hash: 156
Registry: 8

*Links*:
`https://translate.google.com/website?sl=auto&tl=en&hl=ru&client=webapp&u=https://github.com/obfuscator-llvm/obfuscator/wiki/Control-Flow-Flattening`
`https://translate.google.com/website?sl=auto&tl=en&hl=ru&client=webapp&u=https://github.com/bitsadmin/ReVBShell`
`https://translate.google.com/website?sl=auto&tl=en&hl=ru&client=webapp&u=https://github.com/vzex/dog-tunnel`
`https://translate.google.com/website?sl=auto&tl=en&hl=ru&client=webapp&u=https://github.com/LiveMirror/pcshare`