#ParsedReport
*25-04-2022*

ASEC Weekly Malware Statistics (April 11th, 2022 April 17th, 2022)

https://asec.ahnlab.com/en/33763

*Threats*:
Agent\_tesla (tags: malware)
Formbook (tags: malware)
Lokibot\_stealer (tags: malware)
Redline\_stealer (tags: malware)
Beamwinhttp\_loader (tags: malware)
Snake\_keylogger (tags: malware)

*Industry*:
Financial

*IOCs*:
Domain: 5
IP: 6
Email: 7
File: 18
Url: 15

