#ParsedReport
*08-05-2022*

Rewterz Threat Advisory Threat Actors Exploiting VMware Vulnerability Active IOCs

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-threat-actors-exploiting-vmware-vulnerability-active-iocs

*Actors/Campaigns*:
Cleaver

*Threats*:
Cobalt\_strike
Metasploit\_tool

*CVEs*:
CVE-2022-22954  \[[Vulners](https://vulners.com/cve/CVE-2022-22954)]
    Vulners: Score: *10.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - vmware identity manager (3.3.3, 3.3.4, 3.3.5, 3.3.6)
    - vmware vrealize automation (7.6, le8.6)
    - vmware workspace one access (20.10.0.0, 20.10.0.1, 21.08.0.0, 21.08.0.1)
    - vmware cloud foundation (le4.3.1)
    - vmware vrealize suite lifecycle manager (le8.2)
    have more...
CVE-2022-22958  \[[Vulners](https://vulners.com/cve/CVE-2022-22958)]
    Vulners: Score: *6.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.1*
    X-Force: Patch: Official fix
    Soft:
    - vmware cloud foundation (<5.0)
    - vmware identity manager (3.3.3, 3.3.4, 3.3.5, 3.3.6)
    - vmware vrealize automation (7.6, <9.0)
    - vmware vrealize suite lifecycle manager (<9.0)
    - vmware workspace one access (20.10.0.0, 20.10.0.1, 21.08.0.0, 21.08.0.1)
    have more...
CVE-2022-22957  \[[Vulners](https://vulners.com/cve/CVE-2022-22957)]
    Vulners: Score: *6.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.1*
    X-Force: Patch: Official fix
    Soft:
    - vmware cloud foundation (<5.0)
    - vmware identity manager (3.3.3, 3.3.4, 3.3.5, 3.3.6)
    - vmware vrealize automation (7.6, <9.0)
    - vmware vrealize suite lifecycle manager (<9.0)
    - vmware workspace one access (20.10.0.0, 20.10.0.1, 21.08.0.0, 21.08.0.1)
    have more...

*TTPs*:
Tactics: 3
Technics: 0

*IOCs*:
IP: 1
Hash: 3

