*25-03-2022*
Purple Fox Uses New Arrival Vector and Improves Malware Arsenal

https://www.trendmicro.com/en\_us/research/22/c/purple-fox-uses-new-arrival-vector-and-improves-malware-arsenal.html

*Threats*:
Purplefox (stealer, botnet, malware, trojan, rat, rootkit)
Fatalrat\_rat (malware)
Zegost (malware)
Trojan.win64.pfshelloader.sm
Jadtre

*Industry*:
Financial

*Geo*:
Chinese

*IOCs*:
File: 2
IP: 69
Hash: 56
Url: 7