#ParsedReport
*16-05-2022*

Rewterz Threat Advisory SAP Web Dispatcher and SAP Netweaver AS for ABAP Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-sap-web-dispatcher-and-sap-netweaver-as-for-abap-vulnerability

*CVEs*:
CVE-2022-27656  \[[Vulners](https://vulners.com/cve/CVE-2022-27656)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

