#ParsedReport
*27-05-2022*

Threat Source newsletter (May 26, 2022) BlackByte adds itself to the grocery list of big game hunters

http://blog.talosintelligence.com/2022/05/threat-source-newsletter-may-26-2022.html

*Actors/Campaigns*:
Red\_delta

*Threats*:
Blackbyte (tags: spyware, trojan, cryptomining, ransomware, malware)
Conti
Predator
Cytrox

*Industry*:
Government

*Geo*:
Netherlands, Mexico, Indonesia, Greece, Colombia, Armenia, America, Madagascar, Spain, Egypt, Vietnam, China, Ukraine, Serbia

*IOCs*:
Hash: 10
File: 4

