#ParsedReport
*21-04-2022*

Analyzing Attempts to Exploit the Spring4Shell Vulnerability CVE-2022-22965 to Deploy Cryptocurrency Miners. A high number of exploitation attempts

https://www.trendmicro.com/en\_us/research/22/d/spring4shell-exploited-to-deploy-cryptocurrency-miners.html

*Threats*:
Spring4shell (tags: cryptomining, malware, botnet, rat)
Mirai (tags: cryptomining)
Malxmr\_miner

*CVEs*:
CVE-2022-22965  \[[Vulners](https://vulners.com/cve/CVE-2022-22965)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - vmware spring framework (<5.2.20, <5.3.18)
    - cisco cx cloud agent (<2.1.0)
    - oracle communications cloud native core automated test suite (1.9.0, 22.1.0)
    - oracle communications cloud native core console (1.9.0, 22.1.0)
    - oracle communications cloud native core network exposure function (22.1.0)
    have more...

*IOCs*:
File: 2
Path: 1
IP: 1
Hash: 4

