#ParsedReport
*05-04-2022*

Thwarting Loaders: From SocGholish to BLISTERs LockBit Payload

https://www.trendmicro.com/en\_us/research/22/d/Thwarting-Loaders-From-SocGholish-to-BLISTERs-LockBit-Payload.html

*Threats*:
Socgholish\_loader (tags: ransomware, dropper, rat, malware)
Blister\_loader (tags: ransomware, dropper, rat, malware)
Lockbit (tags: ransomware, dropper, rat, malware)
Cobalt\_strike
Emotet
Dridex
Sbit\_rat
Jadtre
Lolbin

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 5
Domain: 1
IP: 20
Path: 1
Hash: 57

