#ParsedReport
*26-05-2022*

Detecting and preventing privilege escalation attacks leveraging Kerberos relaying (KrbRelayUp)

https://www.microsoft.com/security/blog/2022/05/25/detecting-and-preventing-privilege-escalation-attacks-leveraging-kerberos-relaying-krbrelayup

*Threats*:
Krbrelayup\_tool (tags: malware)
Rubeus\_tool
Krbrelay\_tool
Scmuacbypass\_tool
Whisker\_tool
Adcspwn\_tool

*Links*:
`https://github.com/Dec0ne/KrbRelayUp`