#ParsedReport
*14-04-2022*

Rewterz Threat Alert ShadowPad RAT Active IOCs

https://www.rewterz.com/rewterz-news/rewterz-threat-alert-shadowpad-rat-active-iocs

*Actors/Campaigns*:
Comment\_crew
Redecho

*Threats*:
Shadowpad (tags: trojan, malware, rat)

*Industry*:
Financial

*Geo*:
Korea, Japan, Mongolia, Russia, India, Ukraine, Indian, Chinese

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
Domain: 4
IP: 2
Hash: 14

