#ParsedReport
*19-04-2022*

Rewterz Threat Alert IcedID Banking Trojan Active IOCs Russian-Ukrainian Cyber Warfare

https://www.rewterz.com/rewterz-news/rewterz-threat-alert-icedid-banking-trojan-active-iocs-russian-ukrainian-cyber-warfare

*Actors/Campaigns*:
Lunar\_spider

*Threats*:
Icedid (tags: rat, trojan)
Emotet
Trickbot
Hancitor
Zeus
Dridex
Gozi

*Industry*:
Government, Financial

*Geo*:
Ukraine

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 4
Domain: 3
IP: 3
Hash: 12
Url: 3

