#ParsedReport
*18-04-2022*

Rewterz Threat Advisory CVE-2022-1364 Google Chrome V8 Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-1364-google-chrome-v8-vulnerability

*CVEs*:
CVE-2022-1364  \[[Vulners](https://vulners.com/cve/CVE-2022-1364)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

