#ParsedReport
*08-05-2022*

Rewterz Threat Advisory Multiple Apache Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-apache-vulnerabilities-13

*CVEs*:
CVE-2022-23942  \[[Vulners](https://vulners.com/cve/CVE-2022-23942)]
    Vulners: Score: *5.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix
    Soft:
    - apache doris (<1.0.0)

CVE-2022-24706  \[[Vulners](https://vulners.com/cve/CVE-2022-24706)]
    Vulners: Score: *10.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - apache couchdb (<3.2.2)


*TTPs*:
Tactics: 2
Technics: 0

