#ParsedReport
*20-05-2022*

PDF Malware Is Not Yet Dead

https://threatresearch.ext.hp.com/pdf-malware-is-not-yet-dead

*Threats*:
Snake\_keylogger

*CVEs*:
CVE-2017-11882  \[[Vulners](https://vulners.com/cve/CVE-2017-11882)]
    Vulners: Score: *9.3*, CVSS: *8.3*, 
    Vulners: Exploitation: True
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix
    Soft:
    - microsoft office (2013, 2010, 2016, 2007)


*IOCs*:
File: 3
Hash: 6
Url: 3
Domain: 1

*Links*:
`https://github.com/decalage2/oletools/wiki/oleid`
`https://github.com/decalage2/oletools/wiki/rtfobj`