#ParsedReport
*04-05-2022*

SOLARDEFLECTION C2 Infrastructure Used by NOBELIUM in Company Brand Misuse

https://www.recordedfuture.com/solardeflection-c2-infrastructure-used-by-nobelium-in-company-brand-misuse

*Actors/Campaigns*:
Solardeflection (tags: phishing, dns)
Darkhalo (tags: phishing, dns)
Duke
Lunarreflection

*Threats*:
Cobalt\_strike

*Industry*:
Government, Ngo

*Geo*:
Russian, Ukraine

*IOCs*:
Domain: 60
Hash: 11

