#ParsedReport
*22-05-2022*

Rewterz Threat Advisory Multiple Cisco Common Services Platform Collector (CSPC) Software Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-cisco-common-services-platform-collector-cspc-software-vulnerabilities

*CVEs*:
CVE-2022-20669  \[[Vulners](https://vulners.com/cve/CVE-2022-20669)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-20670  \[[Vulners](https://vulners.com/cve/CVE-2022-20670)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-2066  \[[Vulners](https://vulners.com/cve/CVE-2022-2066)]
CVE-2022-20667  \[[Vulners](https://vulners.com/cve/CVE-2022-20667)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-20671  \[[Vulners](https://vulners.com/cve/CVE-2022-20671)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-20668  \[[Vulners](https://vulners.com/cve/CVE-2022-20668)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-20674  \[[Vulners](https://vulners.com/cve/CVE-2022-20674)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-20673  \[[Vulners](https://vulners.com/cve/CVE-2022-20673)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-20672  \[[Vulners](https://vulners.com/cve/CVE-2022-20672)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

