#ParsedReport
*07-04-2022*

Parrot TDS takes over web servers and threatens millions. Campaign overview

https://decoded.avast.io/janrubin/parrot-tds-takes-over-web-servers-and-threatens-millions/?utm\_source=rss&utm\_medium=rss&utm\_campaign=parrot-tds-takes-over-web-servers-and-threatens-millions

*Threats*:
Socgholish\_loader
Prometheus
Netsupportmanager\_rat

*Industry*:
Government

*Geo*:
Brazil, India, Chinese

*IOCs*:
File: 1
Registry: 1
Hash: 8
Domain: 38
IP: 13

*Links*:
`https://github.com/avast/ioc/tree/master/ParrotTDS`