#ParsedReport
*19-04-2022*

Rewterz Threat Advisory CVE-2022-22391 IBM Aspera High-Speed Transfer Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-22391-ibm-aspera-high-speed-transfer-vulnerability

*CVEs*:
CVE-2022-22391  \[[Vulners](https://vulners.com/cve/CVE-2022-22391)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

