#ParsedReport
*15-05-2022*

Rewterz Threat Advisory Multiple Zoom products Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-zoom-products-vulnerabilities

*CVEs*:
CVE-2022-22782  \[[Vulners](https://vulners.com/cve/CVE-2022-22782)]
    Vulners: Score: *6.6*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.9*
    X-Force: Patch: Official fix
    Soft:
    - zoom vdi windows meeting clients (<5.9.6)
    - zoom rooms for conference rooms (<5.10.0)
    - zoom zoom plugin for microsoft outlook (<5.10.3)
    - zoom meetings (<5.9.7)


*TTPs*:
Tactics: 1
Technics: 0

