#ParsedReport
*20-05-2022*

Rewterz Threat Advisory CVE-2022-21151 Intel Processors Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-21151-intel-processors-vulnerability

*CVEs*:
CVE-2022-21151  \[[Vulners](https://vulners.com/cve/CVE-2022-21151)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

