#ParsedReport
*13-04-2022*

Fodcha, a new DDos botnet

https://blog.netlab.360.com/fodcha-a-new-ddos-botnet

*Threats*:
Fodcha\_botnet (tags: scan, botnet, rat, backdoor, ddos, dns)

*Industry*:
Telco

*Geo*:
Korea, China, India, Japan

*CVEs*:
CVE-2021-22205  \[[Vulners](https://vulners.com/cve/CVE-2021-22205)]
    Vulners: Score: *7.5*, CVSS: *5.6*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.9*
    X-Force: Patch: Official fix
    Soft:
    - gitlab (<13.8.8, <13.8.8, <13.9.6, <13.9.6, <13.10.3, <13.10.3)

CVE-2021-35394  \[[Vulners](https://vulners.com/cve/CVE-2021-35394)]
    Vulners: Score: *10.0*, CVSS: *5.4*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - realtek realtek jungle sdk (le3.4.14b)


*IOCs*:
Hash: 37
Url: 28
Domain: 2

