#ParsedReport
*17-04-2022*

Rewterz Threat Advisory CVE-2022-27479 Apache Superset Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-27479-apache-superset-vulnerability

*CVEs*:
CVE-2022-27479  \[[Vulners](https://vulners.com/cve/CVE-2022-27479)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

