#ParsedReport
*14-04-2022*

Rewterz Threat Advisory Multiple Adobe Products Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-adobe-products-vulnerabilities

*CVEs*:
CVE-2022-28270  \[[Vulners](https://vulners.com/cve/CVE-2022-28270)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-28277  \[[Vulners](https://vulners.com/cve/CVE-2022-28277)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-28279  \[[Vulners](https://vulners.com/cve/CVE-2022-28279)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-28271  \[[Vulners](https://vulners.com/cve/CVE-2022-28271)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-24093  \[[Vulners](https://vulners.com/cve/CVE-2022-24093)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.1*
    X-Force: Patch: Official fix

CVE-2022-24098  \[[Vulners](https://vulners.com/cve/CVE-2022-24098)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-28276  \[[Vulners](https://vulners.com/cve/CVE-2022-28276)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-28275  \[[Vulners](https://vulners.com/cve/CVE-2022-28275)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-28278  \[[Vulners](https://vulners.com/cve/CVE-2022-28278)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-27783  \[[Vulners](https://vulners.com/cve/CVE-2022-27783)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-24105  \[[Vulners](https://vulners.com/cve/CVE-2022-24105)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-28273  \[[Vulners](https://vulners.com/cve/CVE-2022-28273)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-28272  \[[Vulners](https://vulners.com/cve/CVE-2022-28272)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-28274  \[[Vulners](https://vulners.com/cve/CVE-2022-28274)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-27784  \[[Vulners](https://vulners.com/cve/CVE-2022-27784)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-23205  \[[Vulners](https://vulners.com/cve/CVE-2022-23205)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

