#ParsedReport
*29-05-2022*

Rewterz Threat Alert An Unknown APT Group Targeting Russian Government Entities Russian-Ukrainian Cyber Warfare Active IOCs

https://www.rewterz.com/rewterz-news/rewterz-threat-alert-an-unknown-apt-group-targeting-russian-government-entities-russian-ukrainian-cyber-warfare-active-iocs

*Actors/Campaigns*:
Shell\_crew

*Threats*:
Log4shell\_vuln
Sakula\_rat

*Industry*:
Petroleum, Media, Government

*Geo*:
Ukraine, Saudi, Russian, Chinese

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 3
Domain: 4
IP: 5
Hash: 81

