#ParsedReport
*22-05-2022*

Rewterz Threat Advisory Multiple NVIDIA vGPU Software Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-nvidia-vgpu-software-vulnerabilities-2

*CVEs*:
CVE-2022-28192  \[[Vulners](https://vulners.com/cve/CVE-2022-28192)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.1*
    X-Force: Patch: Official fix

CVE-2022-28191  \[[Vulners](https://vulners.com/cve/CVE-2022-28191)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 1

