#ParsedReport
*22-04-2022*

Rewterz Threat Advisory CVE-2022-29266 Apache APISIX Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-29266-apache-apisix-vulnerability

*CVEs*:
CVE-2022-29266  \[[Vulners](https://vulners.com/cve/CVE-2022-29266)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

