#ParsedReport
*19-05-2022*

eSentire Threat Intelligence Malware Analysis: Mars Stealer

https://www.esentire.com/blog/esentire-threat-intelligence-malware-analysis-mars-stealer

*Threats*:
Mars\_stealer (tags: backdoor, rat, malware, phishing, stealer)
Oski\_stealer (tags: malware)
Netsupportmanager\_rat
Findpos
Saturn
Terra\_stealer
Exodus
Solarmarker

*Industry*:
Transport, Financial

*Geo*:
America, Azerbaijan, Belarus, Emea, Africa, Uzbekistan, Russia, Apac

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 17
Url: 1
Path: 3
Coin: 4
Domain: 3
IP: 2
Hash: 8

*YARA*: Found

