#ParsedReport
*30-05-2022*

Phishing Campaign Delivering Three Fileless Malware: AveMariaRAT / BitRAT / PandoraHVNC Part II

https://www.fortinet.com/blog/threat-research/phishing-campaign-delivering-fileless-malware-part-two

*Threats*:
Avemaria\_rat (tags: phishing, trojan, ransomware, ddos, keylogger, cryptomining, rat, malware)
Sbit\_rat (tags: phishing, ransomware, ddos, keylogger, cryptomining, rat, malware)
Pandorahvnc\_rat (tags: phishing, ransomware, ddos, keylogger, cryptomining, rat, malware)
Pandora
Vba/agent.ddon!tr (tags: malware)

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 3
Path: 1
Domain: 5
Coin: 1

*Functions Names*: 1

