#ParsedReport
*06-04-2022*

Contis Hacker Manuals Read, Reviewed & Analyzed

https://www.akamai.com/blog/security/conti

*Actors/Campaigns*:
Lapsus

*Threats*:
Conti (tags: stealer, phishing, dropper, backdoor, ransomware, dns, spyware, malware, trojan, rat, scan)
Ryuk
Maze
Cobalt\_strike
Mimikatz
Psexec\_tool
Winrm\_tool
Eternalblue\_vuln
Bluekeep\_vuln
Anydesk\_tool
Atera\_tool
Printnightmare\_vuln
Zerologon\_vuln
Lolbin
Trickbot

*Industry*:
Government, Financial

*Geo*:
Russian, Ukrainian, Russia

*TTPs*:
Tactics: 4
Technics: 0

*IOCs*:
File: 4

*Links*:
`https://github.com/akamai/akamai-security-research/tree/main/leaks/Conti`
`https://github.com/RUB-NDS/PRET`