#ParsedReport
*01-06-2022*

The Popular Malware Downloader, GootLoader, Expands its Payloads Yet Again, Infecting a Law Firm with IcedID. Appendix

https://www.esentire.com/blog/gootloader-initial-access-as-a-service-malware-expands-its-payloads-yet-again-infecting-law-firm-with-icedid

*Threats*:
Gootloader (tags: ransomware, malware, rat, trojan)
Icedid (tags: ransomware, malware, trojan, rat)
Cobalt\_strike (tags: ransomware, malware)
Beacon (tags: malware)
Conti (tags: malware)
Revil (tags: malware)
Fivehands (tags: malware)
Blackcat (tags: malware)
Gootkit

*Industry*:
Financial, Aerospace

*IOCs*:
Hash: 1
IP: 1
Domain: 1
File: 1

*Links*:
`https://github.com/pan-unit42/tweets/blob/master/2022-01-27-IOCs-for-Contact-Forms-IcedID-with-Cobalt-Strike.txt`