#ParsedReport
*19-05-2022*

The BlackByte ransomware group is striking users all over the globe

http://blog.talosintelligence.com/2022/05/the-blackbyte-ransomware-group-is.html

*Threats*:
Blackbyte (tags: vpn, phishing, malware, ransomware)
Lolbin
Anydesk\_tool
Proxyshell\_vuln
Psexec\_tool

*Industry*:
Financial

*Geo*:
Mexico, Netherlands, America, China, Colombia, Vietnam

*IOCs*:
File: 5
Path: 1

*Links*:
`https://github.com/Neo23x0/Raccine`