#ParsedReport
*22-05-2022*

Rewterz Threat Advisory Multiple Apple iOS and iPadOS Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-apple-ios-and-ipados-vulnerabilities-4

*CVEs*:
CVE-2022-26740  \[[Vulners](https://vulners.com/cve/CVE-2022-26740)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26731  \[[Vulners](https://vulners.com/cve/CVE-2022-26731)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-26701  \[[Vulners](https://vulners.com/cve/CVE-2022-26701)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26763  \[[Vulners](https://vulners.com/cve/CVE-2022-26763)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26736  \[[Vulners](https://vulners.com/cve/CVE-2022-26736)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26744  \[[Vulners](https://vulners.com/cve/CVE-2022-26744)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26739  \[[Vulners](https://vulners.com/cve/CVE-2022-26739)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26768  \[[Vulners](https://vulners.com/cve/CVE-2022-26768)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26706  \[[Vulners](https://vulners.com/cve/CVE-2022-26706)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-26737  \[[Vulners](https://vulners.com/cve/CVE-2022-26737)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-22673  \[[Vulners](https://vulners.com/cve/CVE-2022-22673)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-26738  \[[Vulners](https://vulners.com/cve/CVE-2022-26738)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26766  \[[Vulners](https://vulners.com/cve/CVE-2022-26766)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-26711  \[[Vulners](https://vulners.com/cve/CVE-2022-26711)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-26714  \[[Vulners](https://vulners.com/cve/CVE-2022-26714)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26757  \[[Vulners](https://vulners.com/cve/CVE-2022-26757)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-26765  \[[Vulners](https://vulners.com/cve/CVE-2022-26765)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

