#ParsedReport
*28-04-2022*

Rewterz Threat Advisory CVE-2022-29582 Linux Kernel Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-29582-linux-kernel-vulnerability

*CVEs*:
CVE-2022-29582  \[[Vulners](https://vulners.com/cve/CVE-2022-29582)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

