#ParsedReport
*25-05-2022*

Attacker Caught Hijacking Packages Using Multiple Techniques to Steal AWS Credentials. What Happened?

https://checkmarx.com/blog/attacker-caught-hijacking-packages-using-multiple-techniques-to-steal-aws-credentials

*IOCs*:
Domain: 1

*Links*:
`https://github.com/optimistdigital`
`https://github.com/checkmarx/chainjacking`
`https://github.com/hautelook/phpass`
`https://github.com/optimistdigital/nova-tailwind`
`https://github.com/bordoni/phpass`
`https://github.com/hautelook`
`https://github.com/outl1ne/nova-tailwind`
`https://github.com/hautelook/phpass/commit/3119474dbd111f4f489e34cc72a9f95fc991858a`