#ParsedReport
*01-06-2022*

CVE-2022-30190: New Zero-Day Vulnerability (Follina) in Microsoft Support Diagnostic Tool

https://www.netskope.com/blog/cve-2022-30190-new-zero-day-vulnerability-follina-in-microsoft-support-diagnostic-tool

*Threats*:
Follina\_vuln (tags: malware, stealer, fraud)
Log4shell\_vuln
Emotet
Redline\_stealer

*Geo*:
Belarus, Italy

*CVEs*:
CVE-2022-30190  \[[Vulners](https://vulners.com/cve/CVE-2022-30190)]
CVE-2021-40444  \[[Vulners](https://vulners.com/cve/CVE-2021-40444)]
    Vulners: Score: *6.8*, CVSS: *2.1*, 
    Vulners: Exploitation: True
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows 10 (-, 20h2, 21h1, 1607, 1809, 1909, 2004)
    - microsoft windows 7 (-)
    - microsoft windows 8.1 (-)
    - microsoft windows rt 8.1 (-)
    - microsoft windows server 2008 (-, r2)
    have more...

*IOCs*:
File: 5
Path: 1
Registry: 2
Hash: 6
Url: 2

