#ParsedReport
*26-05-2022*

Blame the Messenger: 4 Types of Dropper Malware in Microsoft Office & How to Detect Them

https://www.deepinstinct.com/blog/types-of-dropper-malware-in-microsoft-office

*Actors/Campaigns*:
Aggaa (tags: malware)

*Threats*:
Emotet (tags: malware, dropper)
Revenge\_rat (tags: malware)
Dridex (tags: dropper)

*IOCs*:
Url: 1
Path: 1
File: 2
Hash: 7

*Links*:
`https://github.com/deepinstinct/Exceller`
`https://github.com/DidierStevens/DidierStevensSuite/blob/master/oledump.py`