#ParsedReport
*29-04-2022*

Rewterz Threat Advisory CVE-2022-21449 Oracle Java SE Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-21449-oracle-java-se-vulnerability

*CVEs*:
CVE-2022-21449  \[[Vulners](https://vulners.com/cve/CVE-2022-21449)]
    Vulners: Score: *5.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix
    Soft:
    - oracle graalvm (21.3.1, 22.0.0.2)
    - oracle jdk (17.0.2, 18)


*TTPs*:
Tactics: 1
Technics: 0

