#ParsedReport
*09-05-2022*

SEO Poisoning A Gootloader Story

https://thedfirreport.com/2022/05/09/seo-poisoning-a-gootloader-story

*Threats*:
Gootloader (tags: malware, scan, rat, proxy)
Gootkit
Mimikatz
Lazagne
Bloodhound\_tool
Cobalt\_strike (tags: proxy)
Psexec\_tool
Beacon
Netscan\_tool
Meterpreter\_tool

*TTPs*:
Tactics: 10
Technics: 23

*IOCs*:
Registry: 7
File: 6
Path: 9
Url: 7
IP: 5
Domain: 1
Hash: 8

*YARA*: Found
*SIGMA*: Found

*Links*:
`https://github.com/The-DFIR-Report/cyberchef-recipes/blob/main/SEO%20Poisoning%20-%20A%20GootLoader%20Story`
`https://github.com/Kevin-Robertson/Invoke-TheHash/blob/master/Invoke-WMIExec.ps1`
`https://github.com/activecm/rita`
`https://github.com/hpthreatresearch/tools/blob/main/gootloader/decode.py`
`https://github.com/AlessandroZ/LaZagne`