#ParsedReport
*16-05-2022*

Rewterz Threat Advisory CVE-2022-28394 Trend Micro Password Manager Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-28394-trend-micro-password-manager-vulnerability

*CVEs*:
CVE-2022-29108  \[[Vulners](https://vulners.com/cve/CVE-2022-29108)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-28394  \[[Vulners](https://vulners.com/cve/CVE-2022-28394)]

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
IP: 2

