#ParsedReport
*24-05-2022*

TURLAs new phishing-based reconnaissancecampaignin Eastern Europe. TURLAs new phishing-based reconnaissance campaign in Eastern Europe

https://blog.sekoia.io/turla-new-phishing-campaign-eastern-europe

*Actors/Campaigns*:
Curious\_gorge
Fancy\_bear
Coldriver
Ghostwriter
Turla
Molerats

*Threats*:
Turla (tags: phishing, malware)
Uroburos
Maze

*Industry*:
Government, Petroleum, Education

*Geo*:
Russia, Latvia, Usa, Chinese, Austria, Lithuania, Russian, Ukraine, Chinas, Estonia

*TTPs*:

*IOCs*:
Domain: 3
File: 4
IP: 3
Url: 1
Hash: 2

*YARA*: Found

