#ParsedReport
*22-05-2022*

Rewterz Threat Advisory CVE-2022-20765 Cisco UCS Director Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-20765-cisco-ucs-director-vulnerability

*CVEs*:
CVE-2022-20765  \[[Vulners](https://vulners.com/cve/CVE-2022-20765)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

