#ParsedReport
*06-04-2022*

eSentire Threat Intelligence Malware Analysis: DoubleZero

https://www.esentire.com/blog/esentire-threat-intelligence-malware-analysis-doublezero

*Threats*:
Doublezero (tags: malware)
Whispergate (tags: malware)
Hermeticwiper (tags: malware)
Isaacwiper (tags: malware)
Killdisk (tags: malware)

*Geo*:
Ukraine, Ukrainian

*IOCs*:
Hash: 5
Registry: 1
File: 11
Path: 1

*YARA*: Found

