#ParsedReport
*30-05-2022*

GoodWill ransomware forces victims to donate to the poor and provides financial assistance to patients in need

https://cloudsek.com/threatintelligence/goodwill-ransomware-forces-victims-to-donate-to-the-poor-and-provides-financial-assistance-to-patients-in-need

*Threats*:
Goodwill (tags: malware, ransomware, rat)
Gozi (tags: ransomware)
Hiddentear

*Industry*:
Financial, Healthcare

*Geo*:
India, Turkish, Indian

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
IP: 2
Hash: 4

*Functions Names*: 1

