#ParsedReport
*31-03-2022*

Conti-nuation: methods and techniques observed in operations post the leaks

https://research.nccgroup.com/2022/03/31/conti-nuation-methods-and-techniques-observed-in-operations-post-the-leaks

*Threats*:
Conti
Bazarbackdoor
Trickbot
Cobalt\_strike
Qakbot
Proxyshell\_vuln
Proxylogon\_exploit
Bloodhound\_tool
Mimikatz
Zerologon\_vuln

*CVEs*:
CVE-2018-13379  \[[Vulners](https://vulners.com/cve/CVE-2018-13379)]
    Vulners score: 4.0
    Exploitation: True
    Patch: Official fix
    Soft:
    - fortinet fortios (le6.0.4, le5.6.7)

CVE-2018-13374  \[[Vulners](https://vulners.com/cve/CVE-2018-13374)]
    Vulners score: 4.4
    Exploitation: Unknown
    Patch: Official fix
    Soft:
    - fortinet fortios (le5.6.7, le6.0.2)

CVE-2021-44228  \[[Vulners](https://vulners.com/cve/CVE-2021-44228)]
    Vulners score: 4.0
    Exploitation: True
    Patch: Official fix
    Soft:
    - apache log4j (2.0, 2.0, 2.0, 2.0, <2.3.1, <2.12.2, <2.15.0)
    - siemens sppa-t3000 ses3000 firmware (\*)
    - siemens captial (<2019.1, 2019.1, 2019.1)
    - siemens comos (\*)
    - siemens desigo cc advanced reports (4.0, 4.1, 4.2, 5.0, 5.1)
    have more...

*TTPs*:
Tactics: 4
Technics: 0

*IOCs*:
File: 14
Url: 1
Path: 8
IP: 4
Domain: 1
Hash: 1

