#ParsedReport
*21-05-2022*

Rewterz Threat Update Anonymous Collective Continues To Breach Russian Organizations Russian-Ukrainian Cyber Warfare

https://www.rewterz.com/rewterz-news/rewterz-threat-update-anonymous-collective-continues-to-breach-russian-organizations-russian-ukrainian-cyber-warfare

*Industry*:
Petroleum, E-commerce, Energy, Transport, Government

*Geo*:
Spain, Korea, China, Japan, Italy, Israel, Russian, Russia, Germany, Azerbaijan, Turkey, Finland, Brazil, Ukraine

*TTPs*:
Tactics: 1
Technics: 0

