#ParsedReport
*29-05-2022*

Rewterz Threat Advisory Multiple Google Chrome Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-google-chrome-vulnerabilities-22

*Industry*:
Education

*CVEs*:
CVE-2022-1869  \[[Vulners](https://vulners.com/cve/CVE-2022-1869)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1868  \[[Vulners](https://vulners.com/cve/CVE-2022-1868)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1873  \[[Vulners](https://vulners.com/cve/CVE-2022-1873)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix

CVE-2022-1863  \[[Vulners](https://vulners.com/cve/CVE-2022-1863)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1862  \[[Vulners](https://vulners.com/cve/CVE-2022-1862)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1872  \[[Vulners](https://vulners.com/cve/CVE-2022-1872)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix

CVE-2022-1870  \[[Vulners](https://vulners.com/cve/CVE-2022-1870)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1871  \[[Vulners](https://vulners.com/cve/CVE-2022-1871)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix

CVE-2022-1866  \[[Vulners](https://vulners.com/cve/CVE-2022-1866)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1865  \[[Vulners](https://vulners.com/cve/CVE-2022-1865)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1854  \[[Vulners](https://vulners.com/cve/CVE-2022-1854)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1875  \[[Vulners](https://vulners.com/cve/CVE-2022-1875)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix

CVE-2022-1874  \[[Vulners](https://vulners.com/cve/CVE-2022-1874)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix

CVE-2022-1855  \[[Vulners](https://vulners.com/cve/CVE-2022-1855)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1859  \[[Vulners](https://vulners.com/cve/CVE-2022-1859)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1864  \[[Vulners](https://vulners.com/cve/CVE-2022-1864)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1860  \[[Vulners](https://vulners.com/cve/CVE-2022-1860)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1876  \[[Vulners](https://vulners.com/cve/CVE-2022-1876)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.4*
    X-Force: Patch: Official fix

CVE-2022-1858  \[[Vulners](https://vulners.com/cve/CVE-2022-1858)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1867  \[[Vulners](https://vulners.com/cve/CVE-2022-1867)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-1861  \[[Vulners](https://vulners.com/cve/CVE-2022-1861)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1856  \[[Vulners](https://vulners.com/cve/CVE-2022-1856)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

