#ParsedReport
*08-05-2022*

Rewterz Threat Advisory Multiple IBM Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-ibm-vulnerabilities-7

*CVEs*:
CVE-2022-22434  \[[Vulners](https://vulners.com/cve/CVE-2022-22434)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.2*
    X-Force: Patch: Official fix

CVE-2021-39020  \[[Vulners](https://vulners.com/cve/CVE-2021-39020)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *2*
    X-Force: Patch: Official fix

CVE-2022-22415  \[[Vulners](https://vulners.com/cve/CVE-2022-22415)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix

CVE-2022-22433  \[[Vulners](https://vulners.com/cve/CVE-2022-22433)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *2.7*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
IP: 1

