#ParsedReport
*22-05-2022*

Rewterz Threat Advisory CVE-2022-29383 NETGEAR ProSafe FVS336Gv2 and NETGEAR ProSafe FVS336Gv3 Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-29383-netgear-prosafe-fvs336gv2-and-netgear-prosafe-fvs336gv3-vulnerability

*CVEs*:
CVE-2022-29383  \[[Vulners](https://vulners.com/cve/CVE-2022-29383)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Unavailable


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 1

