#ParsedReport
*19-05-2022*

Lazarus Group Exploiting Log4Shell Vulnerability (NukeSped)

https://asec.ahnlab.com/en/34461

*Actors/Campaigns*:
Lazarus (tags: cryptomining, backdoor, ransomware, rat, stealer, malware)

*Threats*:
Log4shell\_vuln (tags: cryptomining, backdoor, ransomware, rat, stealer, malware)
Nukesped\_rat (tags: cryptomining, backdoor, ransomware, rat, stealer, malware)
Trojan/win.andardoor.c5094639
Infostealer/win.pwstealer.c4510631
Xmrig\_miner

*Geo*:
Korea

*CVEs*:
CVE-2021-44228  \[[Vulners](https://vulners.com/cve/CVE-2021-44228)]
    Vulners: Score: *9.3*, CVSS: *4.0*, 
    Vulners: Exploitation: True
    X-Force: Risk: *10*
    X-Force: Patch: Official fix
    Soft:
    - apache log4j (2.0, 2.0, 2.0, 2.0, <2.15.0, <2.3.1, <2.12.2)
    - siemens sppa-t3000 ses3000 firmware (\*)
    - siemens logo\! soft comfort (\*)
    - siemens spectrum power 4 (4.70, 4.70, <4.70, 4.70)
    - siemens siveillance control pro (\*)
    have more...

*IOCs*:
File: 7
IP: 4
Hash: 12
Url: 5
Domain: 1

