#ParsedReport
*19-05-2022*

Phishing Campaign Delivering Three Fileless Malware: AveMariaRAT / BitRAT / PandoraHVNC Part I

https://www.fortinet.com/blog/threat-research/phishing-campaign-delivering-fileless-malware

*Actors/Campaigns*:
Keksec (tags: malware, phishing)

*Threats*:
Avemaria\_rat (tags: malware, spam, ransomware, botnet, phishing, ddos, rat, proxy)
Sbit\_rat (tags: malware, spam, ransomware, botnet, phishing, ddos, rat, proxy)
Emotet (tags: malware, phishing)
Enemybot (tags: malware, phishing)
Vba/agent.ddon!tr (tags: malware)

*Industry*:
Financial

*IOCs*:
File: 17
Url: 5
Path: 2
Hash: 3

