#ParsedReport
*19-05-2022*

Phishing Campaign Delivering Three Fileless Malware: AveMariaRAT / BitRAT / PandoraHVNC Part I

https://www.fortinet.com/blog/threat-research/phishing-campaign-delivering-fileless-malware

*Actors/Campaigns*:
Keksec (tags: malware, phishing)

*Threats*:
Avemaria\_rat (tags: ransomware, spam, malware, phishing, rat, ddos, proxy, botnet)
Sbit\_rat (tags: ransomware, spam, malware, phishing, rat, ddos, proxy, botnet)
Pandorahvnc (tags: spam, botnet, malware, phishing, rat, ddos, proxy, ransomware)
Emotet (tags: malware, phishing)
Enemybot (tags: malware, phishing)
Vba/agent.ddon!tr (tags: malware)

*Industry*:
Financial

*IOCs*:
File: 17
Url: 5
Path: 2
Hash: 3

