#ParsedReport
*08-05-2022*

Rewterz Threat Advisory Multiple WordPress Plugin Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-wordpress-plugin-vulnerabilities-4

*CVEs*:
CVE-2022-29418  \[[Vulners](https://vulners.com/cve/CVE-2022-29418)]
    Vulners: Score: *3.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix
    Soft:
    - night mode project night mode (le1.0.0)

CVE-2022-29417  \[[Vulners](https://vulners.com/cve/CVE-2022-29417)]
    Vulners: Score: *4.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix
    Soft:
    - shortpixel shortpixel adaptive images (le3.3.1)

CVE-2022-29419  \[[Vulners](https://vulners.com/cve/CVE-2022-29419)]
    Vulners: Score: *6.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6*
    X-Force: Patch: Unavailable
    Soft:
    - 3xsocializer project 3xsocializer (le0.98.22)


*TTPs*:
Tactics: 1
Technics: 0

