#ParsedReport
*31-03-2022*

New Milestones for Deep Panda: Log4Shell and Digitally Signed Fire Chili Rootkits

https://www.fortinet.com/blog/threat-research/deep-panda-log4shell-fire-chili-rootkits

*Actors/Campaigns*:
Shell\_crew (tags: dropper, rat, backdoor, malware, rootkit)
Axiom

*Threats*:
Fire\_chili\_rootkit (tags: dropper, rat, backdoor, malware, rootkit)
Log4shell\_vuln (tags: dropper, rat, backdoor, malware, rootkit)
Gh0st\_rat
Netbot
Themida\_packer\_tool

*Industry*:
Financial

*Geo*:
Chinese, Korean

*TTPs*:

*IOCs*:
File: 10
Path: 1
Domain: 4
Hash: 50
IP: 3
Url: 4

*Links*:
`https://github.com/bowlofstew/rootkit.com/blob/master/cardmagic/PortHidDemo\_Vista.c`
`https://github.com/geemion/Record/blob/master/HideReg.c`
`https://github.com/sin5678/gh0st`