#ParsedReport
*16-05-2022*

Rewterz Threat Advisory Multiple Palo Alto Networks Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-palo-alto-networks-vulnerabilities-2

*CVEs*:
CVE-2022-0025  \[[Vulners](https://vulners.com/cve/CVE-2022-0025)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.7*
    X-Force: Patch: Official fix

CVE-2022-0024  \[[Vulners](https://vulners.com/cve/CVE-2022-0024)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.2*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

