#ParsedReport
*03-05-2022*

Analysis of BlackByte Ransomware's Go-Based Variants. Key Points

https://www.zscaler.com/blogs/security-research/analysis-blackbyte-ransomwares-go-based-variants

*Threats*:
Blackbyte (tags: ransomware, malware, rat)
Revil
Lockbit

*Industry*:
Ics, Financial

*Geo*:
Russia, Russian, Ukrainian, Belarusian

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
Hash: 9
Url: 4
Path: 20
File: 36
Registry: 7
IP: 1

*Links*:
`https://github.com/golang/go/blob/master/src/crypto/des/cipher.go`
`https://github.com/SpiderLabs/BlackByteDecryptor/blob/main/BlackByteDecryptor/Decryptor.cs`
`https://github.com/andrivet/ADVobfuscator`
`https://gist.github.com/api0cradle/d4aaef39db0d845627d819b2b6b30512`