#ParsedReport
*28-04-2022*

Rewterz Threat Advisory CVE-2022-28820 Adobe ACS AEM Commons Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-28820-adobe-acs-aem-commons-vulnerability

*CVEs*:
CVE-2022-28820  \[[Vulners](https://vulners.com/cve/CVE-2022-28820)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

*Links*:
`https://github.com/Adobe-Consulting-Services/acs-aem-commons/security/advisories/GHSA-w5m2-299g-rff5`