#ParsedReport
*25-04-2022*

Rewterz Threat Advisory Multiple Cisco Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-cisco-vulnerabilities-8

*CVEs*:
CVE-2022-20789  \[[Vulners](https://vulners.com/cve/CVE-2022-20789)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix

CVE-2022-20790  \[[Vulners](https://vulners.com/cve/CVE-2022-20790)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-20805  \[[Vulners](https://vulners.com/cve/CVE-2022-20805)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.1*
    X-Force: Patch: Official fix

CVE-2022-20804  \[[Vulners](https://vulners.com/cve/CVE-2022-20804)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

