#ParsedReport
*27-05-2022*

BAZARLOADER: Analysing The Main Loader. Step 1: Checking System Languages

https://www.0ffset.net/reverse-engineering/analysing-the-main-bazarloader/?utm\_source=rss&utm\_medium=rss&utm\_campaign=analysing-the-main-bazarloader

*Threats*:
Bazarbackdoor (tags: malware, dns)
Cobalt\_strike
Conti

*Geo*:
Russia

*IOCs*:
File: 1

*Functions Names*: 37

*Links*:
`https://github.com/m0n0ph1/Process-Hollowing`