#ParsedReport
*29-03-2022*

Forged in Fire: A Survey of MobileIron Log4Shell Exploitation

https://www.mandiant.com/resources/mobileiron-log4shell-exploitation

*Actors/Campaigns*:
Axiom
Unc3500
Unc961
Unc3535 

*Threats*:
Log4shell\_vuln
Xmrig\_miner
Nexus\_logger
Powershell\_shell\_tool
Holepunch\_tool
Holedoor (tags: backdoor)
Darkdoor (tags: backdoor)
Chinachopper

*Industry*:
Government, Media, Education, Healthcare, Financial, Telco, Energy, Retail

*Geo*:
America, Asia, China

*CVEs*:
CVE-2021-44228  \[[Vulners](https://vulners.com/cve/CVE-2021-44228)]
    Vulners score: 4.0
    Exploitation: True
    Patch: Official fix
    Soft:
    - apache log4j (2.0, 2.0, 2.0, 2.0, <2.3.1, <2.12.2, <2.15.0)
    - siemens sppa-t3000 ses3000 firmware (*)
    - siemens captial (<2019.1, 2019.1, 2019.1)
    - siemens comos (*)
    - siemens desigo cc advanced reports (4.0, 4.1, 4.2, 5.0, 5.1)
    have more...

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
Domain: 9
Url: 7
File: 5
IP: 22
Hash: 4

*Links*:
`https://github.com/cisagov/log4j-affected-db`