#ParsedReport
*02-06-2022*

Alert (AA22-152A)

https://www.cisa.gov/uscert/ncas/alerts/aa22-152a

*Actors/Campaigns*:
Karakurt

*Threats*:
Log4shell\_vuln
Cobalt\_strike
Beacon
Mimikatz
Blister\_loader

*Industry*:
Government, Healthcare, Financial

*Geo*:
America

*CVEs*:
CVE-2021-44228  \[[Vulners](https://vulners.com/cve/CVE-2021-44228)]
    Vulners: Score: *9.3*, CVSS: *4.0*, 
    Vulners: Exploitation: True
    X-Force: Risk: *10*
    X-Force: Patch: Official fix
    Soft:
    - apache log4j (2.0, 2.0, 2.0, 2.0, <2.15.0, <2.3.1, <2.12.2)
    - siemens sppa-t3000 ses3000 firmware (\*)
    - siemens logo\! soft comfort (\*)
    - siemens spectrum power 4 (4.70, 4.70, <4.70, 4.70)
    - siemens siveillance control pro (\*)
    have more...

*TTPs*:
Tactics: 4
Technics: 12

*IOCs*:
Url: 1
File: 6
Email: 9
Hash: 11

