#ParsedReport
*05-04-2022*

Cicada: Chinese APT Group Widens Targeting in Recent Espionage Activity

https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/cicada-apt10-china-ngo-government-attacks

*Actors/Campaigns*:
Stone\_panda (tags: malware, backdoor)

*Threats*:
Sodamaster
Mimikatz
Winvnc\_tool
Nbtscan\_tool

*Industry*:
Education, Ngo, Healthcare, Telco, Religion, Government

*Geo*:
Asia, Montenegro, Japan, Israel, Italy, Chinese, Turkey, India, Canada, America

*IOCs*:
File: 1
Hash: 27
IP: 2

