*25-03-2022*
SpiderLabs Blog. Cyber Attackers Leverage Russia-Ukraine Conflict in Multiple Spam Campaigns

https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/cyber-attackers-leverage-russia-ukraine-conflict-in-multiple-spam-campaigns

*Threats*:
Imminentmonitor\_rat (tags: spam)
Remcos\_rat (tags: spam, malware)
Agent\_tesla (tags: phishing)

*Industry*:
Government, Financial

*Geo*:
Ukrainian, Ukraine, Poland, Lithuania, Russia

*CVEs*:
CVE-2017-11882  \[[Vulners](https://vulners.com/cve/CVE-2017-11882)]
    Vulners score: 8.3
    Exploitation: True
    Patch: official fix
    Soft:
    - microsoft office (2013, 2010, 2016, 2007)

*IOCs*:
Url: 1
Hash: 3