#ParsedReport
*27-05-2022*

Rapidly evolving IoT malware EnemyBot now targeting Content Management System servers and Android devices

https://cybersecurity.att.com/blogs/labs-research/rapidly-evolving-iot-malware-enemybot-now-targeting-content-management-system-servers

*Actors/Campaigns*:
Keksec

*Threats*:
Enemybot (tags: scan, ddos, dns, botnet, trojan, rat, malware)
Alien
Mirai
Qakbot
Zeus
Tsunami\_botnet
Bashlite
Log4shell\_vuln

*Industry*:
Petroleum, Iot

*CVEs*:
CVE-2022-2294  \[[Vulners](https://vulners.com/cve/CVE-2022-2294)]
CVE-2021-4039  \[[Vulners](https://vulners.com/cve/CVE-2021-4039)]
    Vulners: Score: *10.0*, CVSS: *5.3*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - zyxel nwa1100-nh firmware (<2.12\(aasi.3\)c0)

CVE-2022-22947  \[[Vulners](https://vulners.com/cve/CVE-2022-22947)]
    Vulners: Score: *6.8*, CVSS: *7.8*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *Unknown*
    X-Force: Patch: Unknown
    Soft:
    - vmware spring cloud gateway (<3.0.7, 3.1.0)

CVE-2021-36356  \[[Vulners](https://vulners.com/cve/CVE-2021-36356)]
    Vulners: Score: *10.0*, CVSS: *4.8*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *Unknown*
    X-Force: Patch: Unknown
    Soft:
    - kramerav viaware (le2021-08)

CVE-2021-35064  \[[Vulners](https://vulners.com/cve/CVE-2021-35064)]
    Vulners: Score: *10.0*, CVSS: *4.7*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Unavailable
    Soft:
    - kramerav viaware (\*)

CVE-2017-18368  \[[Vulners](https://vulners.com/cve/CVE-2017-18368)]
    Vulners: Score: *10.0*, CVSS: *3.1*, 
    Vulners: Exploitation: True
    X-Force: Risk: *7.3*
    X-Force: Patch: Unavailable
    Soft:
    - billion 5200w-t firmware (7.3.8.0)
    - zyxel p660hn-t1a v2 firmware (7.3.15.0)
    - zyxel p660hn-t1a v1 firmware (7.3.15.0)

CVE-2018-10823  \[[Vulners](https://vulners.com/cve/CVE-2018-10823)]
    Vulners: Score: *9.0*, CVSS: *6.6*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.1*
    X-Force: Patch: Unavailable
    Soft:
    - d-link dwr-116 firmware (le1.06)
    - d-link dwr-512 firmware (le2.02)
    - d-link dwr-912 firmware (le2.02)
    - d-link dwr-111 firmware (le1.01)

CVE-2022-22954  \[[Vulners](https://vulners.com/cve/CVE-2022-22954)]
    Vulners: Score: *10.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - vmware identity manager (3.3.3, 3.3.4, 3.3.5, 3.3.6)
    - vmware vrealize automation (7.6, le8.6)
    - vmware workspace one access (20.10.0.0, 20.10.0.1, 21.08.0.0, 21.08.0.1)
    - vmware cloud foundation (le4.3.1)
    - vmware vrealize suite lifecycle manager (le8.2)
    have more...
CVE-2022-25075  \[[Vulners](https://vulners.com/cve/CVE-2022-25075)]
    Vulners: Score: *7.5*, CVSS: *6.9*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Official fix
    Soft:
    - totolink a3000ru firmware (v5.9c.2280\_b20180512)

CVE-2014-9118  \[[Vulners](https://vulners.com/cve/CVE-2014-9118)]
    Vulners: Score: *9.0*, CVSS: *8.2*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.3*
    X-Force: Patch: Official fix
    Soft:
    - dasanzhone znid 2426a firmware (-)

CVE-2020-5902  \[[Vulners](https://vulners.com/cve/CVE-2020-5902)]
    Vulners: Score: *10.0*, CVSS: *4.6*, 
    Vulners: Exploitation: True
    X-Force: Risk: *10*
    X-Force: Patch: Official fix
    Soft:
    - f5 big-ip access policy manager (<11.6.5.2, <12.1.5.2, <13.1.3.4, <14.1.2.6, le15.0.1.4, <15.1.0.4)
    - f5 big-ip advanced firewall manager (<11.6.5.2, <12.1.5.2, <13.1.3.4, <14.1.2.6, <15.0.1.4, <15.1.0.4)
    - f5 big-ip advanced web application firewall (<11.6.5.2, <12.1.5.2, <13.1.3.4, <14.1.2.6, <15.0.1.4, <15.1.0.4)
    - f5 big-ip analytics (<11.6.5.2, <12.1.5.2, <13.1.3.4, <14.1.2.6, <15.0.1.4, <15.1.0.4)
    - f5 big-ip application acceleration manager (<11.6.5.2, <12.1.5.2, <13.1.3.4, <14.1.2.6, <15.0.1.4, <15.1.0.4)
    have more...
CVE-2018-16763  \[[Vulners](https://vulners.com/cve/CVE-2018-16763)]
    Vulners: Score: *7.5*, CVSS: *6.0*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Unavailable
    Soft:
    - thedaylightstudio fuel cms (le1.4.2)

CVE-2015-2051  \[[Vulners](https://vulners.com/cve/CVE-2015-2051)]
    Vulners: Score: *10.0*, CVSS: *8.9*, 
    Vulners: Exploitation: True
    X-Force: Risk: *10*
    X-Force: Patch: Official fix
    Soft:
    - d-link dir-645 firmware (le1.04b12)

CVE-2020-7961  \[[Vulners](https://vulners.com/cve/CVE-2020-7961)]
    Vulners: Score: *7.5*, CVSS: *8.6*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - liferay liferay portal (le7.2.0)

CVE-2020-17456  \[[Vulners](https://vulners.com/cve/CVE-2020-17456)]
    Vulners: Score: *7.5*, CVSS: *7.0*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Unavailable
    Soft:
    - seowonintech slc-130 firmware (-)
    - seowonintech slr-120s firmware (-)
    - seowonintech slr-120s42g firmware (\*)
    - seowonintech slr-120d42g firmware (\*)
    - seowonintech slr-120t42g firmware (\*)
    have more...
CVE-2021-44228  \[[Vulners](https://vulners.com/cve/CVE-2021-44228)]
    Vulners: Score: *9.3*, CVSS: *4.0*, 
    Vulners: Exploitation: True
    X-Force: Risk: *10*
    X-Force: Patch: Official fix
    Soft:
    - apache log4j (2.0, 2.0, 2.0, 2.0, <2.15.0, <2.3.1, <2.12.2)
    - siemens sppa-t3000 ses3000 firmware (\*)
    - siemens logo\! soft comfort (\*)
    - siemens spectrum power 4 (4.70, 4.70, <4.70, 4.70)
    - siemens siveillance control pro (\*)
    have more...
CVE-2022-1388  \[[Vulners](https://vulners.com/cve/CVE-2022-1388)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - f5 big-ip access policy manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip advanced firewall manager (le11.6.5, le12.1.6, <15.1.5.1, <14.1.4.6, <13.1.5, <16.1.2.2)
    - f5 big-ip analytics (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip application acceleration manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip application security manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    have more...
CVE-2021-45046  \[[Vulners](https://vulners.com/cve/CVE-2021-45046)]
    Vulners: Score: *5.1*, CVSS: *3.2*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9*
    X-Force: Patch: Official fix
    Soft:
    - apache log4j (2.0, 2.0, 2.0, 2.0, <2.12.2, <2.16.0)
    - intel audio development kit (-)
    - intel computer vision annotation tool (-)
    - intel datacenter manager (-)
    - intel genomics kernel library (-)
    have more...

*IOCs*:
IP: 2
Hash: 15

*Links*:
`https://github.com/freakanonymous/enemy`