#ParsedReport
*16-05-2022*

Rewterz Threat Advisory ICS: Delta Electronics CNCSoft Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-ics-delta-electronics-cncsoft-vulnerabilities

*Industry*:
Ics

*CVEs*:
CVE-2022-1405  \[[Vulners](https://vulners.com/cve/CVE-2022-1405)]
CVE-2022-1404  \[[Vulners](https://vulners.com/cve/CVE-2022-1404)]

*TTPs*:
Tactics: 2
Technics: 0

