#ParsedReport
*08-05-2022*

Rewterz Threat Advisory CVE-2022-28890 Apache Jena Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-28890-apache-jena-vulnerability

*CVEs*:
CVE-2022-28890  \[[Vulners](https://vulners.com/cve/CVE-2022-28890)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

