#ParsedReport
*06-04-2022*

Cado Discovers Denonia: The First Malware Specifically Targeting Lambda

https://www.cadosecurity.com/cado-discovers-denonia-the-first-malware-specifically-targeting-lambda

*Threats*:
Denonia (tags: malware, cryptomining, dns, botnet)
Xmrig\_miner (tags: malware)
Log4shell\_vuln (tags: malware)

*IOCs*:
Hash: 2
Domain: 7
IP: 3

*Links*:
`https://github.com/goretk/redress`
`https://github.com/aws/aws-lambda-go`