#ParsedReport
*06-05-2022*

Emotet: New Delivery Mechanism to Bypass VBA Protection

https://www.netskope.com/blog/emotet-new-delivery-mechanism-to-bypass-vba-protection

*Threats*:
Emotet (tags: botnet, rat, trojan, malware, phishing, fraud)
Trickbot
Spring4shell

*Industry*:
Financial

*IOCs*:
File: 9
Hash: 143
Url: 12
IP: 67

*YARA*: Found

*Links*:
`https://github.com/netskopeoss/NetskopeThreatLabsIOCs/tree/main/Emotet/IOCs/2022-05-06`
`https://github.com/netskopeoss/NetskopeThreatLabsIOCs/blob/main/Emotet/IOCs/script/decrypt\_payload.py`
`https://github.com/netskopeoss/NetskopeThreatLabsIOCs/blob/main/Emotet/IOCs/script/decrypt\_c2.py`
`https://github.com/netskopeoss/NetskopeThreatLabsIOCs/tree/main/Emotet`