#ParsedReport
*14-04-2022*

INCONTROLLER: New State-Sponsored Cyber Attack Tools Target Multiple Industrial Control Systems

https://www.mandiant.com/resources/incontroller-state-sponsored-ics-tool

*Threats*:
Incontroller\_tool (tags: ddos, scan, rat, backdoor, malware)
Triton (tags: malware)
Crashoverride (tags: malware)
Stuxnet
Vpnfilter (tags: malware)

*Industry*:
Ics, Financial, Energy

*Geo*:
Iranian, Ukraine, Ukrainian, America, Russia

*CVEs*:
CVE-2020-15368  \[[Vulners](https://vulners.com/cve/CVE-2020-15368)]
    Vulners: Score: *2.1*, CVSS: *4.0*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.2*
    X-Force: Patch: Unavailable
    Soft:
    - asrock rgb driver firmware (-)


*TTPs*:
Tactics: 8
Technics: 0

*IOCs*:
File: 1

*YARA*: Found

