#ParsedReport
*19-05-2022*

New SYK Crypter Distributed Via Discord

https://blog.morphisec.com/syk-crypter-discord

*Threats*:
Babadeda (tags: ransomware)
Asyncrat\_rat (tags: ransomware)
Njrat\_rat (tags: ransomware)
Quasar\_rat (tags: ransomware)
Avemaria\_rat (tags: ransomware)
Nanocore\_rat (tags: ransomware)
Redline\_stealer (tags: ransomware)
Agent\_tesla

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 6
Url: 26
Domain: 17
IP: 2
Path: 5
Hash: 47

