#ParsedReport
*25-05-2022*

Dragon News Blog. Bablosoft; Lowering the Barrier of Entry for Malicious Actors

https://team-cymru.com/blog/2022/05/25/bablosoft-lowering-the-barrier-of-entry-for-malicious-actors

*Actors/Campaigns*:
Grim\_spider

*Threats*:
Bumblebee (tags: malware)
Blackguard\_stealer (tags: malware)
Redline\_stealer (tags: malware)

*Industry*:
E-commerce

*Geo*:
Russian, Ukraine, Russia

*IOCs*:
Domain: 3
IP: 4

