#ParsedReport
*19-05-2022*

CrateDepression \| Rust Supply-Chain Attack Infects Cloud CI Pipelines with Go Malware

https://www.sentinelone.com/labs/cratedepression-rust-supply-chain-attack-infects-cloud-ci-pipelines-with-go-malware

*Threats*:
Findpos
Applescript

*Industry*:
Financial

*IOCs*:
Url: 3
Domain: 2
IP: 1
File: 1
Hash: 35

*Links*:
`https://github.com/MythicAgents/poseidon`
`https://github.com/rodionovd/RDProcess`
`https://github.com/MarcMayzl/repos`
`https://github.com/paupino/rust-decimal/issues/514#issuecomment-1115408888`
`https://github.com/BurntSushi/xgb`
`https://github.com/its-a-feature/Mythic`
`https://github.com/anuraghazra/github-readme-stats`