#ParsedReport
*12-04-2022*

Fake Chrome Setup Leads to NetSupportManager RAT and Mars Stealer

https://www.esentire.com/blog/fake-chrome-setup-leads-to-netsupportmanager-rat-and-mars-stealer

*Threats*:
Netsupportmanager\_rat (tags: rat, malware, fraud, phishing, stealer)
Mars\_stealer (tags: rat, malware, fraud, phishing, stealer)
More\_eggs

*Industry*:
Financial

*IOCs*:
File: 13
Coin: 1
Domain: 2
IP: 1
Hash: 8

