#ParsedReport
*14-04-2022*

Threat Spotlight: "Haskers Gang" Introduces New ZingoStealer

http://blog.talosintelligence.com/2022/04/haskers-gang-zingostealer.html

*Threats*:
Zingo\_stealer (tags: stealer, ransomware, malware, cryptomining, rat)
Redline\_stealer (tags: fraud, malware, stealer)
Xmrig\_miner (tags: malware, cryptomining, stealer, rat)
Exodus

*Industry*:
Financial

*Geo*:
Russian

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
Url: 5
Domain: 3
File: 17
Path: 8
IP: 1
Coin: 1
Hash: 349

