#ParsedReport
*28-04-2022*

Trello From the Other Side: Tracking APT29 Phishing Campaigns

https://www.mandiant.com/resources/tracking-apt29-phishing-campaigns

*Actors/Campaigns*:
Duke (tags: dropper, malware, phishing, rat, proxy, backdoor, dns)
Darkhalo (tags: phishing)
Unc2542 (tags: phishing)

*Threats*:
Beatdrop\_loader (tags: phishing, malware)
Boommic\_loader (tags: phishing, malware)
Envyscout (tags: malware)
Beacon (tags: malware)
Html\_smuggling\_technique
Cobalt\_strike (tags: malware)
Bart
Timestomp\_tool
Kerberoasting\_technique

*Industry*:
Government

*Geo*:
Asia, Russian, Ukraine, Americas, Russia

*TTPs*:
Tactics: 13
Technics: 88

*IOCs*:
File: 10
Path: 3
Hash: 15
Registry: 1
Url: 1

