#ParsedReport
*19-05-2022*

Protecting Android users from 0-Day attacks

https://blog.google/threat-analysis-group/protecting-android-users-from-0-day-attacks

*Threats*:
Cytrox
Alien
Predator
Binder

*Industry*:
Government

*Geo*:
Serbia, Greece, Madagascar, Indonesia, Egypt, Armenia, Spain

*CVEs*:
CVE-2021-38003  \[[Vulners](https://vulners.com/cve/CVE-2021-38003)]
    Vulners: Score: *6.8*, CVSS: *4.2*, 
    Vulners: Exploitation: True
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix
    Soft:
    - google chrome (<95.0.4638.69)
    - fedoraproject fedora (34)
    - debian debian linux (10.0, 11.0)

CVE-2021-37976  \[[Vulners](https://vulners.com/cve/CVE-2021-37976)]
    Vulners: Score: *4.3*, CVSS: *3.8*, 
    Vulners: Exploitation: True
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix
    Soft:
    - google chrome (<94.0.4606.71)
    - fedoraproject fedora (33, 34, 35)
    - debian debian linux (10.0, 11.0)

CVE-2021-38000  \[[Vulners](https://vulners.com/cve/CVE-2021-38000)]
    Vulners: Score: *5.8*, CVSS: *4.4*, 
    Vulners: Exploitation: True
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix
    Soft:
    - google chrome (<95.0.4638.69)
    - fedoraproject fedora (34)
    - debian debian linux (10.0, 11.0)

CVE-2021-37973  \[[Vulners](https://vulners.com/cve/CVE-2021-37973)]
    Vulners: Score: *6.8*, CVSS: *3.8*, 
    Vulners: Exploitation: True
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix
    Soft:
    - google chrome (<94.0.4606.61)
    - fedoraproject fedora (33, 35)
    - debian debian linux (10.0, 11.0)

CVE-2021-1048  \[[Vulners](https://vulners.com/cve/CVE-2021-1048)]
    Vulners: Score: *7.2*, CVSS: *6.2*, 
    Vulners: Exploitation: True
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix
    Soft:
    - google android (-)


*IOCs*:
Domain: 5
File: 2
Hash: 1

*Links*:
`https://github.com/shivanigithub/fenced-frame`