#ParsedReport
*23-04-2022*

ASEC Weekly Malware Statistics ( 20220411 \~ 20220417 )

https://asec-ahnlab-com.translate.goog/ko/33741/?\_x\_tr\_sl=auto&\_x\_tr\_tl=en&\_x\_tr\_hl=ru&\_x\_tr\_pto=wapp

*Threats*:
Agent\_tesla (tags: stealer, malware)
Azorult
Formbook (tags: stealer)
Lokibot\_stealer
Avemaria\_rat
Redline\_stealer
Beamwinhttp\_loader
Snake\_keylogger (tags: malware)

*Industry*:
Financial

*Geo*:
Korea

*IOCs*:
Domain: 5
IP: 6
Email: 7
File: 18
Url: 15

