#ParsedReport
*08-05-2022*

Rewterz Threat Advisory CVE-2022-23443 Fortinet FortiSOAR Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-23443-fortinet-fortisoar-vulnerability

*CVEs*:
CVE-2022-23443  \[[Vulners](https://vulners.com/cve/CVE-2022-23443)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

