#ParsedReport
*20-05-2022*

Weaponization of Excel Add-Ins Part 2: Dridex Infection Chain Case Studies

https://unit42.paloaltonetworks.com/excel-add-ins-dridex-infection-chain

*Threats*:
Dridex (tags: malware, rat, dropper)
Agent\_tesla
Atomic\_bombing\_technique

*Geo*:
Japan, Apac, Emea, America

*IOCs*:
File: 2
Hash: 6338
Url: 1496
IP: 4

*Links*:
`https://github.com/pan-unit42/iocs/blob/master/Dridex%20Infection%20Chain%20Case%20Studies`