#ParsedReport
*16-05-2022*

Rewterz Threat Advisory ICS: Siemens Desigo products Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-ics-siemens-desigo-products-vulnerability

*Industry*:
Ics

*CVEs*:
CVE-2021-41545  \[[Vulners](https://vulners.com/cve/CVE-2021-41545)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

