#ParsedReport
*16-05-2022*

Rewterz Threat Advisory CVE-2022-29108 Microsoft SharePoint Server Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-29108-microsoft-sharepoint-server-vulnerability

*CVEs*:
CVE-2022-29108  \[[Vulners](https://vulners.com/cve/CVE-2022-29108)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

