#ParsedReport
*19-04-2022*

Rewterz Threat Advisory Multiple WordPress Plugin Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-wordpress-plugin-vulnerabilities-3

*CVEs*:
CVE-2022-27629  \[[Vulners](https://vulners.com/cve/CVE-2022-27629)]
CVE-2022-27848  \[[Vulners](https://vulners.com/cve/CVE-2022-27848)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

