#ParsedReport
*04-05-2022*

Attacking Emotets Control Flow Flattening

https://news.sophos.com/en-us/2022/05/04/attacking-emotets-control-flow-flattening

*Actors/Campaigns*:
Stone\_panda

*Threats*:
Emotet (tags: spam, botnet, malware)
Stantinko

*IOCs*:
Hash: 2

*Links*:
`https://github.com/obfuscator-llvm/obfuscator/wiki`
`https://github.com/eset/stadeo`
`https://github.com/sophoslabs/emotet\_unflatten\_poc`