#ParsedReport
*14-04-2022*

Rewterz Threat Advisory Multiple Siemens Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-siemens-vulnerabilities

*CVEs*:
CVE-2022-28661  \[[Vulners](https://vulners.com/cve/CVE-2022-28661)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-25650  \[[Vulners](https://vulners.com/cve/CVE-2022-25650)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.1*
    X-Force: Patch: Official fix

CVE-2022-28329  \[[Vulners](https://vulners.com/cve/CVE-2022-28329)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix

CVE-2022-27194  \[[Vulners](https://vulners.com/cve/CVE-2022-27194)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix

CVE-2022-28328  \[[Vulners](https://vulners.com/cve/CVE-2022-28328)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.4*
    X-Force: Patch: Official fix

CVE-2022-25752  \[[Vulners](https://vulners.com/cve/CVE-2022-25752)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-27480  \[[Vulners](https://vulners.com/cve/CVE-2022-27480)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix

CVE-2022-25755  \[[Vulners](https://vulners.com/cve/CVE-2022-25755)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *2.6*
    X-Force: Patch: Official fix

CVE-2022-25754  \[[Vulners](https://vulners.com/cve/CVE-2022-25754)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Official fix

CVE-2022-26380  \[[Vulners](https://vulners.com/cve/CVE-2022-26380)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.4*
    X-Force: Patch: Official fix

CVE-2022-28663  \[[Vulners](https://vulners.com/cve/CVE-2022-28663)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-27241  \[[Vulners](https://vulners.com/cve/CVE-2022-27241)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix

CVE-2022-25622  \[[Vulners](https://vulners.com/cve/CVE-2022-25622)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix

CVE-2022-25756  \[[Vulners](https://vulners.com/cve/CVE-2022-25756)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.9*
    X-Force: Patch: Official fix

CVE-2022-27481  \[[Vulners](https://vulners.com/cve/CVE-2022-27481)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.4*
    X-Force: Patch: Official fix

CVE-2022-25751  \[[Vulners](https://vulners.com/cve/CVE-2022-25751)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.2*
    X-Force: Patch: Official fix

CVE-2022-28662  \[[Vulners](https://vulners.com/cve/CVE-2022-28662)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

