#ParsedReport
*24-05-2022*

New Nokoyawa Variant Catching Up to Peers with Blatant Code Reuse

https://www.fortinet.com/blog/threat-research/nokoyawa-variant-catching-up

*Actors/Campaigns*:
Keksec

*Threats*:
Nokoyawa (tags: cryptomining, malware, botnet, phishing, ddos, ransomware)
Chaos
Pandora
Enemybot
Karma (tags: ransomware)
Nemty
Babuk (tags: ransomware)
Filecoder

*Industry*:
Financial

*Geo*:
Russia

*IOCs*:
File: 33
Hash: 2

