#ParsedReport
*22-05-2022*

Rewterz Threat Advisory Multiple Apple iTunes Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-apple-itunes-vulnerabilities

*CVEs*:
CVE-2022-26773  \[[Vulners](https://vulners.com/cve/CVE-2022-26773)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.7*
    X-Force: Patch: Official fix

CVE-2022-26774  \[[Vulners](https://vulners.com/cve/CVE-2022-26774)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

