#ParsedReport
*18-04-2022*

Rewterz Threat Advisory Multiple Juniper Networks Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-juniper-networks-vulnerabilities

*CVEs*:
CVE-2022-22198  \[[Vulners](https://vulners.com/cve/CVE-2022-22198)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix

CVE-2022-22194  \[[Vulners](https://vulners.com/cve/CVE-2022-22194)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix

CVE-2022-22185  \[[Vulners](https://vulners.com/cve/CVE-2022-22185)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix

CVE-2022-22191  \[[Vulners](https://vulners.com/cve/CVE-2022-22191)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-22189  \[[Vulners](https://vulners.com/cve/CVE-2022-22189)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-22187  \[[Vulners](https://vulners.com/cve/CVE-2022-22187)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-22186  \[[Vulners](https://vulners.com/cve/CVE-2022-22186)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.2*
    X-Force: Patch: Official fix

CVE-2022-22188  \[[Vulners](https://vulners.com/cve/CVE-2022-22188)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

