#ParsedReport
*08-05-2022*

Rewterz Threat Alert Stonefly Group Continues To Hit High-Value Targets Active IOCs

https://www.rewterz.com/rewterz-news/rewterz-threat-alert-stonefly-group-continues-to-hit-high-value-targets-active-iocs

*Actors/Campaigns*:
Lazarus (tags: ddos)
Dream\_job

*Threats*:
Log4shell\_vuln

*Industry*:
Financial, Energy, Government

*Geo*:
Korean

*CVEs*:
CVE-2021-44228  \[[Vulners](https://vulners.com/cve/CVE-2021-44228)]
    Vulners: Score: *9.3*, CVSS: *4.0*, 
    Vulners: Exploitation: True
    X-Force: Risk: *10*
    X-Force: Patch: Official fix
    Soft:
    - apache log4j (2.0, 2.0, 2.0, 2.0, <2.15.0, <2.3.1, <2.12.2)
    - siemens sppa-t3000 ses3000 firmware (\*)
    - siemens logo\! soft comfort (\*)
    - siemens spectrum power 4 (4.70, 4.70, <4.70, 4.70)
    - siemens siveillance control pro (\*)
    have more...

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
Domain: 4
Hash: 15
Url: 5

