#ParsedReport
*08-05-2022*

Rewterz Threat Alert Threat Actors Exploiting the War in Ukraine Active IOCs

https://www.rewterz.com/rewterz-news/rewterz-threat-alert-threat-actors-exploiting-the-war-in-ukraine-active-iocs

*Actors/Campaigns*:
Ghostwriter (tags: phishing, malware)
Fancy\_bear (tags: phishing, malware)
Curious\_gorge
Coldriver

*Threats*:
Empire\_loader
Turla

*Industry*:
E-commerce, Financial, Government

*Geo*:
Asia, Ukrainian, Russia, Lithuania, Ukraine, Poland, Latvia

*CVEs*:
CVE-2021-40444  \[[Vulners](https://vulners.com/cve/CVE-2021-40444)]
    Vulners: Score: *6.8*, CVSS: *2.1*, 
    Vulners: Exploitation: True
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows 10 (-, 20h2, 21h1, 1607, 1809, 1909, 2004)
    - microsoft windows 7 (-)
    - microsoft windows 8.1 (-)
    - microsoft windows rt 8.1 (-)
    - microsoft windows server 2008 (-, r2)
    have more...

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
Domain: 14
Hash: 6

