#ParsedReport
*30-05-2022*

ASEC Weekly Malware Statistics ( 20220523 \~ 20220529 )

https://asec-ahnlab-com.translate.goog/ko/34862/?\_x\_tr\_sl=auto&\_x\_tr\_tl=en&\_x\_tr\_hl=ru&\_x\_tr\_pto=wapp

*Threats*:
Agent\_tesla (tags: scan, malware, stealer)
Azorult
Formbook (tags: stealer)
Lokibot\_stealer
Avemaria\_rat
Beamwinhttp\_loader
Garbage\_cleaner
Cryptbot\_stealer
Remcos\_rat (tags: spam, malware, rat)
Nanocore\_rat

*Industry*:
Transport

*Geo*:
Pacific, Korea

*IOCs*:
Domain: 4
IP: 3
Email: 5
File: 28
Url: 11

