#ParsedReport
*25-04-2022*

THREAT ANALYSIS REPORT: SocGholish and Zloader From Fake Updates and Installers to Owning Your Systems. MITRE ATT&CK Techniques

https://www.cybereason.com/blog/threat-analysis-report-socgholish-and-zloader-from-fake-updates-and-installers-to-owning-your-systems

*Threats*:
Socgholish\_loader (tags: backdoor, rat, ransomware, malware, scan, phishing, proxy)
Z\_loader (tags: backdoor, rat, ransomware, malware, scan, phishing, proxy)
Cobalt\_strike
Egregor
Ryuk
Atera\_tool
Nsudo\_tool

*Industry*:
Government

*Geo*:
Russia, Hungary

*CVEs*:
CVE-2013-3900  \[[Vulners](https://vulners.com/cve/CVE-2013-3900)]
    Vulners: Score: *7.6*, CVSS: *7.3*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.3*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows server 2008 (r2, r2, -)
    - microsoft windows 7 (-)
    - microsoft windows rt (-)
    - microsoft windows 8.1 (-)
    - microsoft windows server 2003 (-)
    have more...

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 20
IP: 6
Domain: 10
Path: 27
Hash: 8

*Links*:
`https://github.com/M2Team/NSudo`