#ParsedReport
*25-04-2022*

Rewterz Threat Advisory ICS: Delta Electronics ASDA-Soft Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-ics-delta-electronics-asda-soft-vulnerabilities

*Industry*:
Ics

*CVEs*:
CVE-2022-1403  \[[Vulners](https://vulners.com/cve/CVE-2022-1403)]
CVE-2022-1402  \[[Vulners](https://vulners.com/cve/CVE-2022-1402)]

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
IP: 1

