#ParsedReport
*05-05-2022*

North Koreas Lazarus: their initial access trade-craft using social media and social engineering. tl;dr

https://research.nccgroup.com/2022/05/05/north-koreas-lazarus-and-their-initial-access-trade-craft-using-social-media-and-social-engineering

*Actors/Campaigns*:
Lazarus (tags: malware, vpn, phishing)

*Threats*:
Lcpdot (tags: vpn, malware)

*Industry*:
Government

*Geo*:
Koreas

*TTPs*:
Tactics: 1
Technics: 4

*IOCs*:
Domain: 6
Path: 2
File: 3
IP: 1
Hash: 6

