#ParsedReport
*25-05-2022*

Hunting a Global Telecommunications Threat: DecisiveArchitect and Its Custom Implant JustForFun

https://www.crowdstrike.com/blog/how-to-hunt-for-decisivearchitect-and-justforfun-implant

*Actors/Campaigns*:
Lightbasin

*Threats*:
Red\_menshen (tags: malware, rat)
Bpfdoor (tags: malware, rat)
Sysvinit\_tool
Mimikatz
Psexec\_tool

*Industry*:
Logistic, Telco

*CVEs*:
CVE-2019-3010  \[[Vulners](https://vulners.com/cve/CVE-2019-3010)]
    Vulners: Score: *4.6*, CVSS: *5.2*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix
    Soft:
    - oracle solaris (11)


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
Url: 1
Path: 1

