#ParsedReport
*14-04-2022*

ESET takes part in global operation to disrupt Zloader botnets

https://www.welivesecurity.com/2022/04/13/eset-takes-part-global-operation-disrupt-zloader-botnets

*Actors/Campaigns*:
Darkside

*Threats*:
Z\_loader (tags: malware, botnet, proxy, ransomware, stealer, rat, trojan, spam)
Zeus
Rig\_tool
Hiddenvnc\_tool
Raccoon\_stealer
Cobalt\_strike
Atera\_tool
Gozi
Kryptik\_trojan

*Industry*:
E-commerce, Financial

*Geo*:
Ukraine, Canada, Japan, Australia, Usa, America, Germany

*CVEs*:
CVE-2012-0151  \[[Vulners](https://vulners.com/cve/CVE-2012-0151)]
    Vulners: Score: *9.3*, CVSS: *7.7*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.3*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows vista (\*, \*)
    - microsoft windows server 2008 (r2, \*, \*, \*, r2)
    - microsoft windows xp (\*, -)
    - microsoft windows 7 (\*, \*)
    - microsoft windows server 2003 (\*)
    have more...
CVE-2013-3900  \[[Vulners](https://vulners.com/cve/CVE-2013-3900)]
    Vulners: Score: *7.6*, CVSS: *7.3*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.3*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows server 2008 (r2, r2, -)
    - microsoft windows 7 (-)
    - microsoft windows rt (-)
    - microsoft windows 8.1 (-)
    - microsoft windows server 2003 (-)
    have more...

*TTPs*:
Tactics: 12
Technics: 53

*IOCs*:
IP: 4
File: 7
Hash: 18
Url: 33

