#ParsedReport
*10-04-2022*

Dragon News Blog. MoqHao Part 2: Continued European Expansion

https://team-cymru.com/blog/2022/04/07/moqhao-part-2-continued-european-expansion

*Actors/Campaigns*:
Roaming\_mantis

*Threats*:
Moqhao (tags: phishing, malware)
Wroba
Formbook
Merlin\_tool

*Industry*:
Financial

*Geo*:
Japan, South Korea, Taiwan, France, Germany, United States

*IOCs*:
Hash: 2
IP: 52

*Links*:
`https://github.com/Ne0nd0g/merlin`
`https://github.com/salesforce/jarm`
`https://github.com/ninoseki`