#ParsedReport
*04-05-2022*

Operation CuckooBees: Deep-Dive into Stealthy Winnti Techniques

https://www.cybereason.com/blog/operation-cuckoobees-deep-dive-into-stealthy-winnti-techniques

*Actors/Campaigns*:
Axiom (tags: rootkit, rat, dropper, proxy, trojan, backdoor, malware, dns)

*Threats*:
Winrm\_tool (tags: rat)
Mimikatz
Acehash
Stashlog
Sparklog
Privatelog
Winnkit
Eternal\_petya

*Industry*:
Government

*Geo*:
China, America, Chinese, Asia

*TTPs*:
Tactics: 6
Technics: 0

*IOCs*:
File: 18
Registry: 3
Hash: 11
Path: 20

*Links*:
`https://github.com/`
`https://github.com/chickenlove/webshell/blob/master/jsp/css.jsp`
`https://github.com/chickenlove/webshell/blob/master/jsp/hackk8/jsp\_77/win32/cmd\_win32.jsp`
`https://github.com/chickenlove/webshell/blob/master/jsp/hackk8/jsp\_77/win32/up\_win32.jsp`