#ParsedReport
*31-05-2022*

Patch Your WSO2: CVE-2022-29464 Exploited to Install Linux-Compatible Cobalt Strike Beacons, Other Malware

https://www.trendmicro.com/en\_us/research/22/e/patch-your-wso2-cve-2022-29464-exploited-to-install-linux-compatible-cobalt-strike-beacons-other-malware.html

*Threats*:
Cobalt\_strike (tags: rat, botnet, cryptomining, malware, trojan, scan, backdoor)
Beacon (tags: rat, botnet, cryptomining, malware, trojan, scan, backdoor)
Metasploit\_tool (tags: malware)
Mirai (tags: malware)
Spring4shell (tags: malware)
Malxmr\_miner (tags: malware)

*Industry*:
Energy, Education, Financial, Healthcare, Government

*CVEs*:
CVE-2022-22965  \[[Vulners](https://vulners.com/cve/CVE-2022-22965)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - vmware spring framework (<5.3.18, <5.2.20)
    - cisco cx cloud agent (<2.1.0)
    - oracle sd-wan edge (9.0, 9.1)
    - oracle retail xstore point of service (20.0.1, 21.0.0)
    - oracle communications cloud native core security edge protection proxy (1.7.0, 22.1.0)
    have more...
CVE-2022-29464  \[[Vulners](https://vulners.com/cve/CVE-2022-29464)]
    Vulners: Score: *10.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - wso2 api manager (le4.0.0)
    - wso2 enterprise integrator (le6.6.0)
    - wso2 identity server (le5.11.0)
    - wso2 identity server analytics (5.4.0, 5.4.1, 5.5.0, 5.6.0)
    - wso2 identity server as key manager (le5.10.0)
    have more...
CVE-2012-4681  \[[Vulners](https://vulners.com/cve/CVE-2012-4681)]
    Vulners: Score: *10.0*, CVSS: *4.8*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.3*
    X-Force: Patch: Official fix
    Soft:
    - sun jdk (1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0.200, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0.210, 1.6.0, 1.4.2\_13, 1.4.2\_30, 1.4.2\_12, 1.4.2\_31, 1.4.2\_3, 1.4.2\_8, 1.4.2\_16, 1.4.2\_23, 1.4.2\_32, 1.4.2\_18, 1.4.2\_19, 1.4.2\_29, 1.4.2\_6, 1.4.2\_26, 1.4.2, 1.4.2\_7, 1.4.2\_27, 1.4.2\_28, 1.4.2\_35, 1.4.2\_36, 1.4.2\_4, 1.4.2\_11, 1.4.2\_22, 1.4.2\_1, 1.4.2\_2, 1.4.2\_9, 1.4.2\_10, 1.4.2\_17, 1.4.2\_37, 1.4.2\_5, 1.4.2\_14, 1.4.2\_25, 1.4.2\_33, 1.4.2\_34, 1.4.2\_15, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0)
    - sun jre (1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.4.2\_26, 1.4.2\_7, 1.4.2\_27, 1.4.2\_16, 1.4.2\_24, 1.4.2\_4, 1.4.2\_13, 1.4.2\_29, 1.4.2\_1, 1.4.2\_8, 1.4.2\_25, 1.4.2\_15, 1.4.2\_31, 1.4.2\_2, 1.4.2\_19, 1.4.2\_14, 1.4.2\_21, 1.4.2\_22, 1.4.2\_30, 1.4.2\_37, 1.4.2\_9, 1.4.2\_17, 1.4.2\_18, 1.4.2\_33, 1.4.2\_35, 1.4.2\_23, 1.4.2\_32, 1.4.2\_3, 1.4.2\_10, 1.4.2\_11, 1.4.2\_12, 1.4.2\_20, 1.4.2\_28, 1.4.2\_36, 1.4.2\_5, 1.4.2\_34, 1.4.2\_6, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0, 1.5.0)
    - oracle jre (1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, le1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.7.0, le1.7.0, 1.7.0, 1.7.0, 1.7.0, 1.7.0, 1.7.0, le1.4.2\_38, le1.5.0)
    - oracle jdk (1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, le1.6.0, 1.6.0, 1.6.0, 1.6.0, 1.6.0, le1.7.0, 1.7.0, 1.7.0, 1.7.0, 1.7.0, 1.7.0, 1.7.0, le1.4.2\_38, le1.5.0)


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 2
IP: 1
Hash: 13
Path: 1
Url: 1

*Links*:
`https://github.com/wso2/product-apim/issues?q=is%3Aopen+is%3Aissue`
`https://github.com/hakivvi`
`https://github.com/shadow1ng/fscan`
`https://github.com/hakivvi/CVE-2022-29464/blob/main/exploit.py`
`https://github.com/wso2/product-apim`