#ParsedReport
*21-04-2022*

Hackers Spearphish Corporate Hiring Managers with Poisoned Resumes, Infecting Them with the More\_Eggs Malware, Warns eSentire

https://www.esentire.com/blog/hackers-spearphish-corporate-hiring-managers-with-poisoned-resumes-infecting-them-with-the-more-eggs-malware

*Actors/Campaigns*:
Venom\_spider
Magecart (tags: ransomware, malware, backdoor)
Evilnum (tags: ransomware, malware, backdoor)

*Threats*:
More\_eggs (tags: proxy, rat, ransomware, malware, phishing, backdoor)
Cobalt (tags: ransomware, malware, backdoor)
Terra\_loader
Meterpreter\_tool
Metasploit\_tool
Terra\_stealer
Lolbin

*Industry*:
Aerospace, Retail, Healthcare, E-commerce, Financial

*Geo*:
Canada

*TTPs*:
Tactics: 5
Technics: 28

*IOCs*:
File: 10
Hash: 5

