#ParsedReport
*11-05-2022*

Nerbian RAT Using COVID-19 Themes Features Sophisticated Evasion Techniques. Detection

https://www.proofpoint.com/us/blog/threat-insight/nerbian-rat-using-covid-19-themes-features-sophisticated-evasion-techniques

*Threats*:
Nerbian\_rat (tags: dropper, trojan, malware, phishing, rat)
Armour

*Industry*:
Government, Healthcare

*Geo*:
Italy, Spain, Ireland, Spanish

*IOCs*:
Hash: 6
Email: 2
File: 53
Path: 4
Url: 2
IP: 1
Domain: 1

*YARA*: Found

*Links*:
`https://github.com/digitalocean/go-smbios/smbios`