#ParsedReport
*02-06-2022*

Tales From the Honeypot: WatchDog Evolves With a New Multi-Stage Cryptojacking Attack

https://www.cadosecurity.com/tales-from-the-honeypot-watchdog-evolves-with-a-new-multi-stage-cryptojacking-attack

*Actors/Campaigns*:
Teamtnt

*Threats*:
Zgrab\_scanner\_tool
Masscan\_tool
Xmrig\_miner
Pnscan\_tool
Log4shell\_vuln

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
Domain: 2
File: 2
IP: 2
Hash: 6
Url: 10
Coin: 1

*Links*:
`https://github.com/zmap/zgrab2`
`https://github.com/robertdavidgraham/masscan`
`https://github.com/ptrrkssn/pnscan`