#ParsedReport
*18-05-2022*

CISA Issues Emergency Directive and Releases Advisory Related to VMware Vulnerabilities

https://us-cert.cisa.gov/ncas/current-activity/2022/05/18/cisa-issues-emergency-directive-and-releases-advisory-related

*Threats*:
Spring4shell

*CVEs*:
CVE-2022-1388  \[[Vulners](https://vulners.com/cve/CVE-2022-1388)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - f5 big-ip access policy manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip advanced firewall manager (le11.6.5, le12.1.6, <15.1.5.1, <14.1.4.6, <13.1.5, <16.1.2.2)
    - f5 big-ip analytics (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip application acceleration manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip application security manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    have more...
CVE-2022-22972  \[[Vulners](https://vulners.com/cve/CVE-2022-22972)]
CVE-2022-22973  \[[Vulners](https://vulners.com/cve/CVE-2022-22973)]
CVE-2022-22954  \[[Vulners](https://vulners.com/cve/CVE-2022-22954)]
    Vulners: Score: *10.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - vmware identity manager (3.3.3, 3.3.4, 3.3.5, 3.3.6)
    - vmware vrealize automation (7.6, le8.6)
    - vmware workspace one access (20.10.0.0, 20.10.0.1, 21.08.0.0, 21.08.0.1)
    - vmware cloud foundation (le4.3.1)
    - vmware vrealize suite lifecycle manager (le8.2)
    have more...
CVE-2022-22960  \[[Vulners](https://vulners.com/cve/CVE-2022-22960)]
    Vulners: Score: *7.2*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix
    Soft:
    - vmware cloud foundation (<5.0)
    - vmware identity manager (3.3.3, 3.3.4, 3.3.5, 3.3.6)
    - vmware vrealize automation (7.6, <9.0)
    - vmware vrealize suite lifecycle manager (<9.0)
    - vmware workspace one access (20.10.0.0, 20.10.0.1, 21.08.0.0, 21.08.0.1)
    have more...

