#ParsedReport
*29-05-2022*

Rewterz Threat Advisory Multiple Citrix ADC and Citrix Gateway Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-citrix-adc-and-citrix-gateway-vulnerabilities

*CVEs*:
CVE-2022-27507  \[[Vulners](https://vulners.com/cve/CVE-2022-27507)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-27508  \[[Vulners](https://vulners.com/cve/CVE-2022-27508)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

