#ParsedReport
*02-05-2022*

Moshen Dragons Triad-and-Error Approach \| Abusing Security Software to Sideload PlugX and ShadowPad

https://www.sentinelone.com/labs/moshen-dragons-triad-and-error-approach-abusing-security-software-to-sideload-plugx-and-shadowpad

*Actors/Campaigns*:
Moshendragon
Nomadpanda
Redfoxtrot
Emissary\_panda

*Threats*:
Plugx\_rat (tags: proxy, backdoor, rat, malware)
Shadowpad (tags: proxy, backdoor, rat, malware)
Gunters (tags: backdoor, malware)
Talisman

*Industry*:
Telco

*Geo*:
Asia, Chinese

*IOCs*:
Path: 7
File: 2
Registry: 1
Hash: 13
Domain: 7

*Links*:
`https://github.com/SecureAuthCorp/impacket`
`https://github.com/GoSecure/DLLPasswordFilterImplant`