#ParsedReport
*06-05-2022*

Bad Rabbit Ransomware

https://www.varonis.com/blog/bad-rabbit-ransomware

*Actors/Campaigns*:
Sandworm

*Threats*:
Petya (tags: ransomware)
Eternal\_petya
Watering\_hole\_technique
Imminentmonitor\_rat
Mimikatz
Mamba
Stop

*Industry*:
Financial

*Geo*:
Russia, Ukraines, Russian, Japan

*CVEs*:
CVE-2017-0145  \[[Vulners](https://vulners.com/cve/CVE-2017-0145)]
    Vulners: Score: *9.3*, CVSS: *8.9*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - microsoft server message block (1.0)


*IOCs*:
Domain: 1
IP: 1
Url: 26
Hash: 6

*Links*:
`https://github.com/worawit/MS17-010/blob/master/zzz\_exploit.py`