#ParsedReport
*06-05-2022*

Rewterz Threat Advisory CVE-2022-0477 GitLab Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-0477-gitlab-vulnerability

*CVEs*:
CVE-2022-0477  \[[Vulners](https://vulners.com/cve/CVE-2022-0477)]
    Vulners: Score: *4.0*, CVSS: *1.9*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix
    Soft:
    - gitlab (<14.6.4, 14.7.0, <14.5.4)


*TTPs*:
Tactics: 1
Technics: 0

