#ParsedReport
*26-05-2022*

Country Extortion: Ransomware expands business to include the government sector

https://blog.checkpoint.com/2022/05/26/country-extortion-ransomware-expands-business-to-the-governmental-sector

*Threats*:
Conti (tags: ransomware)
Smokeloader\_backdoor (tags: ransomware)

*Industry*:
Government, Education, Financial

*Geo*:
Ukraine, America, Russia, Russian, Peru, Americans

*IOCs*:
File: 7

