#ParsedReport
*27-05-2022*

ASEC Weekly Malware Statistics (May 16th, 2022 May 22nd, 2022)

https://asec.ahnlab.com/en/34785

*Threats*:
Agent\_tesla (tags: malware)
Formbook (tags: malware)
Lokibot\_stealer (tags: malware)
Redline\_stealer (tags: malware)
Beamwinhttp\_loader (tags: malware)
Avemaria\_rat (tags: malware)

*Industry*:
Financial, Transport

*IOCs*:
Domain: 4
IP: 23
Email: 5
File: 30
Url: 25

