#ParsedReport
*30-04-2022*

THE LOTUS PANDA IS AWAKE, AGAIN. ANALYSIS OF ITS LAST STRIKE.

https://cluster25.io/2022/04/29/lotus-panda-awake-last-strike

*Actors/Campaigns*:
Naikon (tags: rat, malware, phishing)

*Threats*:
Beacon (tags: rat)
Viper\_rat (tags: rat)
Cobalt\_strike (tags: rat)
Arl\_tool (tags: rat)
Meterpreter\_tool
Powershell\_shell\_tool

*Industry*:
Government

*Geo*:
China, Malaysia, Asian, Philippines, Thailand, Singapore, Indonesia, Chinese, Cambodia, Myanmar, Vietnam

*TTPs*:
Tactics: 4
Technics: 7

*IOCs*:
Path: 1
File: 3
Hash: 4
IP: 1

*Links*:
`https://github.com/FunnyWolf/Viper`
`https://github.com/TophantTechnology/ARL`