#ParsedReport
*18-04-2022*

From the Front Lines \| Peering into A PYSA Ransomware Attack

https://www.sentinelone.com/blog/from-the-front-lines-peering-into-a-pysa-ransomware-attack

*Actors/Campaigns*:
Quickbooks

*Threats*:
Mespinoza (tags: malware, phishing, ransomware, backdoor)
Lolbin
Cobalt\_strike
Empire\_loader
Chisel\_tool
Powershell\_ransomware
Psexec\_tool
Koadic\_tool
Mimikatz
Anydesk\_tool
Magicsocks

*Industry*:
Government, Education, Healthcare

*TTPs*:
Tactics: 3
Technics: 19

*IOCs*:
File: 12
Path: 3
Hash: 40

*Links*:
`https://github.com/winscp/winscp`
`https://github.com/jpillora/chisel`