#ParsedReport
*26-04-2022*

New Malware of Lazarus Threat Actor Group Exploiting INITECH Process

https://asec.ahnlab.com/en/33801

*Actors/Campaigns*:
Lazarus (tags: malware)

*Threats*:
Lazarshell (tags: malware)
Infostealer/win.outlook (tags: malware)
Trojan/win.agent (tags: malware)
Akdoor (tags: malware)
Lazarbinder (tags: malware)
Lazardoor (tags: malware)
Lazarkeyloger (tags: malware)
Lazarloader (tags: malware)
Lazarportscan (tags: malware)
Zvrek (tags: malware)
Trojan/win32.agent (tags: malware)

*Industry*:
Chemical

*Geo*:
Korean

*IOCs*:
File: 8
Hash: 49
Url: 7
Path: 2
IP: 6

