#ParsedReport
*18-04-2022*

Rewterz Threat Advisory CVE-2022-22966 VMware Cloud Director Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-22966-vmware-cloud-director-vulnerability

*CVEs*:
CVE-2022-22966  \[[Vulners](https://vulners.com/cve/CVE-2022-22966)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

