#ParsedReport
*01-04-2022*

AcidRain \| A Modem Wiper Rains Down on Europe

https://www.sentinelone.com/labs/acidrain-a-modem-wiper-rains-down-on-europe

*Actors/Campaigns*:
Fancy\_bear
Sandworm

*Threats*:
Acidrain (tags: rat, vpn, ddos, malware)
Vpnfilter (tags: botnet)
Whispergate
Hermeticwiper
Isaacwiper
Killdisk
Doublezero
Cyclops\_blink

*Industry*:
Ics, Government, Iot

*Geo*:
Germany, Ukraine, Italy, German, Italian, Russia

*IOCs*:
Hash: 2

*Links*:
`https://github.com/trendmicro/tlsh`