#ParsedReport
*29-05-2022*

Rewterz Threat Advisory CVE-2021-39043 IBM Jazz Team Server Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2021-39043-ibm-jazz-team-server-vulnerability

*CVEs*:
CVE-2021-39043  \[[Vulners](https://vulners.com/cve/CVE-2021-39043)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.4*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
IP: 1

