#ParsedReport
*28-04-2022*

CISA and FBI Update Advisory on Destructive Malware Targeting Organizations in Ukraine

https://us-cert.cisa.gov/ncas/current-activity/2022/04/28/cisa-and-fbi-update-advisory-destructive-malware-targeting

*Threats*:
Whispergate (tags: malware)
Hermeticwiper (tags: malware)
Isaacwiper (tags: malware)
Hermeticwizard (tags: malware)
Killdisk (tags: malware)
Spring4shell

*Industry*:
Financial

*Geo*:
Korean, Ukraine, Russian

