#ParsedReport
*10-05-2022*

Examining the Black Basta Ransomwares Infection Routine

https://www.trendmicro.com/en\_us/research/22/e/examining-the-black-basta-ransomwares-infection-routine.html

*Threats*:
Blackbasta (tags: rat, malware, ransomware, phishing)
Conti (tags: ransomware)
Ransom.win32.bastacrypt.thdbgbb (tags: ransomware)
Ransom.win32.bastacrypt.yxcd2 (tags: ransomware)
Ransom.win32.bastacrypt.thdbibb (tags: ransomware)

*Industry*:
Financial

*Geo*:
Canada, Australia

*IOCs*:
Path: 3
Registry: 3
Hash: 8
File: 2

