#ParsedReport
*16-03-2022*

Have Your Cake and Eat it Too? An Overview of UNC2891

https://www.mandiant.com/resources/unc2891-overview

*Actors/Campaigns*:
Unc2891 (tags: dns, rootkit, rat, malware, keylogger, backdoor, dropper, proxy)
Lightbasin

*Threats*:
Nexus\_logger
Rekoobe (tags: dns, rootkit, backdoor, proxy)

*Industry*:
Financial

*TTPs*:

*IOCs*:
IP: 1
Hash: 7

*YARA*: Found

*Links*:
`https://github.com/Kabot/mig-logcleaner-resurrected`
`https://github.com/creaktive/tsh`