#ParsedReport
*20-05-2022*

Rewterz Threat Advisory Multiple Intel Xeon Processors Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-intel-xeon-processors-vulnerabilities

*CVEs*:
CVE-2022-21131  \[[Vulners](https://vulners.com/cve/CVE-2022-21131)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.3*
    X-Force: Patch: Official fix

CVE-2022-21136  \[[Vulners](https://vulners.com/cve/CVE-2022-21136)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

