#ParsedReport
*22-05-2022*

Rewterz Threat Advisory CVE-2022-26747 Apple Xcode Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-26747-apple-xcode-vulnerability

*CVEs*:
CVE-2022-26747  \[[Vulners](https://vulners.com/cve/CVE-2022-26747)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

