#ParsedReport
*19-04-2022*

Public Cloud Cybersecurity Threat Intelligence (202203)

https://blog.netlab.360.com/public-cloud-threat-intelligence-202203

*Threats*:
Spring4shell

*Industry*:
Government, Iot

*CVEs*:
CVE-2022-22963  \[[Vulners](https://vulners.com/cve/CVE-2022-22963)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - vmware spring cloud function (le3.1.6, le3.2.2)

CVE-2022-2294724  \[[Vulners](https://vulners.com/cve/CVE-2022-2294724)]
CVE-2022-22947  \[[Vulners](https://vulners.com/cve/CVE-2022-22947)]
    Vulners: Score: *6.8*, CVSS: *7.8*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *10*
    X-Force: Patch: Official fix
    Soft:
    - vmware spring cloud gateway (<3.0.7, 3.1.0)

CVE-2022-22965  \[[Vulners](https://vulners.com/cve/CVE-2022-22965)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - vmware spring framework (<5.2.20, <5.3.18)
    - cisco cx cloud agent (<2.1.0)


*IOCs*:
File: 6

