#ParsedReport
*06-05-2022*

Rewterz Threat Advisory Multiple IBM QRadar Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-ibm-qradar-vulnerabilities

*CVEs*:
CVE-2021-29776  \[[Vulners](https://vulners.com/cve/CVE-2021-29776)]
    Vulners: Score: *4.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.1*
    X-Force: Patch: Official fix
    Soft:
    - ibm qradar security information and event manager (<7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.4.3, 7.3.3, 7.3.3, <7.4.3, 7.4.3, 7.4.3, 7.4.3, 7.5.0)

CVE-2021-38869  \[[Vulners](https://vulners.com/cve/CVE-2021-38869)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix
    Soft:
    - ibm qradar security information and event manager (<7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.4.3, 7.3.3, 7.3.3, <7.4.3, 7.4.3, 7.4.3, 7.4.3, 7.5.0)

CVE-2021-38878  \[[Vulners](https://vulners.com/cve/CVE-2021-38878)]
    Vulners: Score: *5.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.9*
    X-Force: Patch: Official fix
    Soft:
    - ibm qradar security information and event manager (<7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.4.3, 7.3.3, 7.3.3, <7.4.3, 7.4.3, 7.4.3, 7.4.3, 7.5.0)

CVE-2021-38919  \[[Vulners](https://vulners.com/cve/CVE-2021-38919)]
    Vulners: Score: *5.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.9*
    X-Force: Patch: Official fix
    Soft:
    - ibm qradar security information and event manager (<7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.4.3, 7.3.3, 7.3.3, <7.4.3, 7.4.3, 7.4.3, 7.4.3, 7.5.0)

CVE-2021-38939  \[[Vulners](https://vulners.com/cve/CVE-2021-38939)]
    Vulners: Score: *5.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.7*
    X-Force: Patch: Official fix
    Soft:
    - ibm qradar security information and event manager (<7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.4.3, 7.3.3, 7.3.3, <7.4.3, 7.4.3, 7.4.3, 7.4.3, 7.5.0)

CVE-2021-38874  \[[Vulners](https://vulners.com/cve/CVE-2021-38874)]
    Vulners: Score: *4.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix
    Soft:
    - ibm qradar security information and event manager (<7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.4.3, 7.3.3, 7.3.3, <7.4.3, 7.4.3, 7.4.3, 7.4.3, 7.5.0)

CVE-2022-22345  \[[Vulners](https://vulners.com/cve/CVE-2022-22345)]
    Vulners: Score: *3.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.8*
    X-Force: Patch: Official fix
    Soft:
    - ibm qradar security information and event manager (<7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.3.3, 7.4.3, 7.3.3, 7.3.3, <7.4.3, 7.4.3, 7.4.3, 7.4.3, 7.5.0)


*TTPs*:
Tactics: 1
Technics: 0

