#ParsedReport
*22-05-2022*

Rewterz Threat Update Unpatched F5 BIG-IP Devices Under Active Attack

https://www.rewterz.com/rewterz-news/rewterz-threat-update-unpatched-f5-big-ip-devices-under-active-attack

*CVEs*:
CVE-2022-1388  \[[Vulners](https://vulners.com/cve/CVE-2022-1388)]
    Vulners: Score: *7.5*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - f5 big-ip access policy manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip advanced firewall manager (le11.6.5, le12.1.6, <15.1.5.1, <14.1.4.6, <13.1.5, <16.1.2.2)
    - f5 big-ip analytics (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip application acceleration manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    - f5 big-ip application security manager (le11.6.5, le12.1.6, <16.1.2.2, <15.1.5.1, <14.1.4.6, <13.1.5)
    have more...

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 1
IP: 3

