#ParsedReport
*22-05-2022*

Rewterz Threat Advisory CVE-2022-26726 Apple watchOS Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-26726-apple-watchos-vulnerability

*CVEs*:
CVE-2022-26726  \[[Vulners](https://vulners.com/cve/CVE-2022-26726)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

