#ParsedReport
*13-05-2022*

Operation RestyLink: APT campaign targeting Japanese companies

https://insight-jp.nttsecurity.com/post/102hojk/operation-restylink-apt-campaign-targeting-japanese-companies

*Actors/Campaigns*:
Darkhotel (tags: rat, phishing)
Kimsuky
Duke (tags: malware)
Red\_delta
Lazarus
Darkhalo
Blacktech

*Threats*:
Cobalt\_strike
Covenant\_tool
Goldbackdoor
Wellmess\_rat
Flagpro

*Industry*:
Government

*Geo*:
Korea, China, Japanese, Ukraine, Korean, Dprk, Russia, Usa, Japan, Asia

*IOCs*:
File: 2
Domain: 1
IP: 7

