#ParsedReport
*29-05-2022*

Rewterz Threat Advisory CVE-2022-27231 WordPress WP Statistics plugin Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-27231-wordpress-wp-statistics-plugin-vulnerability

*CVEs*:
CVE-2022-27231  \[[Vulners](https://vulners.com/cve/CVE-2022-27231)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

