#ParsedReport
*02-05-2022*

UNC3524: Eye Spy on Your Email

https://www.mandiant.com/resources/unc3524-eye-spy-email

*Actors/Campaigns*:
Unc3524 (tags: proxy, dns, botnet, backdoor, malware, rat)
Unc3452
Darkhalo
Duke
Fancy\_bear

*Threats*:
Magnitude
Quietexit
Dropbear\_tool
Regeorg
Dcsync\_technique

*Industry*:
Financial, Iot

*TTPs*:
Tactics: 9
Technics: 25

*IOCs*:
IP: 1
File: 1
Hash: 1

*YARA*: Found

*Links*:
`https://github.com/SecureAuthCorp/impacket/blob/master/examples/wmiexec.py`