#ParsedReport
*11-04-2022*

MetaStealer malware: An improved version of RedLine actively distributed via malspam campaign

https://www.secureblink.com/cyber-security-news/meta-stealer-malware-an-improved-version-of-red-line-actively-distributed-via-malspam-campaign

*Threats*:
Meta\_stealer (tags: phishing, stealer, spam, botnet, malware)
Redline\_stealer (tags: phishing, stealer, spam, botnet, malware)

*Industry*:
E-commerce

*IOCs*:
File: 2
IP: 1

