#ParsedReport
*20-04-2022*

Shuckworm: Espionage Group Continues Intense Campaign Against Ukraine

https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/shuckworm-intense-campaign-ukraine

*Actors/Campaigns*:
Gamaredon (tags: malware, backdoor)

*Threats*:
Pterodo (tags: rat, dns, dropper)

*Geo*:
Russian, Ukraine, Ukrainian

*IOCs*:
File: 9
Path: 1
Domain: 1
Hash: 162
Url: 77

*Links*:
`https://github.com/Symantec/threathunters/tree/main/Shuckworm`