#ParsedReport
*31-03-2022*

State-sponsored Attack Groups Capitalise on Russia-Ukraine War for Cyber Espionage. Introduction

https://research.checkpoint.com/2022/state-sponsored-attack-groups-capitalise-on-russia-ukraine-war-for-cyber-espionage

*Actors/Campaigns*:
Siamesekitten (tags: malware)
Sidewinder (tags: malware, stealer)

*Threats*:
Machete

*Industry*:
Financial, Government, Energy

*Geo*:
Nicaragua, Iranian, America, India, Indian, Venezuela, Americans, Africa, Pakistani, Israel, Pakistan, Israeli, Asia, Arabia, Russia, Iran, Ukraine, China, Saudi, Russian

*CVEs*:
CVE-2017-11882  \[[Vulners](https://vulners.com/cve/CVE-2017-11882)]
    Vulners score: 8.3
    Exploitation: True
    Patch: Official fix
    Soft:
    - microsoft office (2013, 2010, 2016, 2007)


*IOCs*:
Email: 1
Domain: 7
File: 15
Hash: 53
IP: 3
Url: 7
Path: 2

*YARA*: Found

*Links*:
`https://github.com/TheGeekHT/Loki.Rat/`
`https://github.com/ghuntley/Heijden.Dns`