#ParsedReport
*25-04-2022*

Defeating BazarLoader Anti-Analysis Techniques

https://unit42.paloaltonetworks.com/bazarloader-anti-analysis-techniques

*Threats*:
Bazarbackdoor (tags: malware, ransomware, backdoor)

*IOCs*:
Hash: 1

*Links*:
`https://github.com/pan-unit42/iocs/blob/master/DeObfuscate\_Opaque`
`https://github.com/pan-unit42/iocs/blob/master/Appcall\_rename\_api`
`https://github.com/idapython`