#ParsedReport
*18-04-2022*

Rewterz Threat Advisory Multiple McAfee Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-mcafee-vulnerabilities

*CVEs*:
CVE-2022-1256  \[[Vulners](https://vulners.com/cve/CVE-2022-1256)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-1257  \[[Vulners](https://vulners.com/cve/CVE-2022-1257)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-1258  \[[Vulners](https://vulners.com/cve/CVE-2022-1258)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.4*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 1

