#ParsedReport
*06-04-2022*

FFDroider Stealer Targeting Social Media Platform Users

https://www.zscaler.com/blogs/security-research/ffdroider-stealer-targeting-social-media-platform-users

*Threats*:
Ffdroider\_stealer (tags: vpn, malware, stealer)
Cobalt\_strike (tags: stealer)

*Industry*:
Financial

*TTPs*:
Tactics: 1
Technics: 8

*IOCs*:
File: 12
Path: 7
Registry: 1
Url: 5
Domain: 8
Hash: 4

