#ParsedReport
*18-04-2022*

Orion Threat Alert: Flight of the BumbleBee. A new campaign in the wild: BumbleBee

https://www.cynet.com/orion-threat-alert-flight-of-the-bumblebee

*Actors/Campaigns*:
Exotic\_lily
Wizard\_spider
Molerats

*Threats*:
Bumblebee (tags: spam, malware, phishing, ransomware, rat)
Cobalt\_strike
Lolbin
Fake-trusteer
Bazarbackdoor
Icedid
Conti
Lockbit
Avoslocker
Emotet

*Industry*:
Financial

*TTPs*:
Tactics: 6
Technics: 0

*IOCs*:
File: 15
Path: 1
IP: 9
Hash: 9
Domain: 3

