#ParsedReport
*18-04-2022*

Rewterz Threat Alert CADDYWIPER Used in Attacks Against Ukraine Active IOCs Russian-Ukrainian Cyber Warfare

https://www.rewterz.com/rewterz-news/rewterz-threat-alert-caddywiper-used-in-attacks-against-ukraine-active-iocs-russian-ukrainian-cyber-warfare

*Threats*:
Killdisk
Hermeticwiper
Isaacwiper

*Industry*:
Financial

*Geo*:
Ukrainian, Ukraine

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 4
Domain: 1
IP: 2
Hash: 9

