#ParsedReport
*20-04-2022*

Reversing a NSIS dropper using quick and dirty shellcode emulation. The Excel document

https://malcat.fr/blog/reversing-a-nsis-dropper-using-quick-and-dirty-shellcode-emulation

*Threats*:
Nsis\_dropper (tags: malware, stealer, rat)
Dbat\_loader
Lokibot\_stealer (tags: malware, rat, stealer)

*CVEs*:
CVE-2018-0798  \[[Vulners](https://vulners.com/cve/CVE-2018-0798)]
    Vulners: Score: *9.3*, CVSS: *9.3*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix
    Soft:
    - microsoft office (2010, 2016, 2016, 2007, 2013)
    - microsoft word (2013, 2016, 2007, 2010, 2013)
    - microsoft office compatibility pack (-)

*IOCs*:
Url: 1
File: 2
Hash: 4

*Links*:
`https://github.com/mandiant/speakeasy`