#ParsedReport
*22-04-2022*

Rewterz Threat Advisory Multiple Cisco Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-cisco-vulnerabilities-7

*CVEs*:
CVE-2022-20778  \[[Vulners](https://vulners.com/cve/CVE-2022-20778)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-20786  \[[Vulners](https://vulners.com/cve/CVE-2022-20786)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.4*
    X-Force: Patch: Official fix

CVE-2022-20788  \[[Vulners](https://vulners.com/cve/CVE-2022-20788)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-20787  \[[Vulners](https://vulners.com/cve/CVE-2022-20787)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.7*
    X-Force: Patch: Official fix

CVE-2022-20783  \[[Vulners](https://vulners.com/cve/CVE-2022-20783)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix

CVE-2022-20795  \[[Vulners](https://vulners.com/cve/CVE-2022-20795)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.8*
    X-Force: Patch: Official fix

CVE-2022-20732  \[[Vulners](https://vulners.com/cve/CVE-2022-20732)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
IP: 2

