#ParsedReport
*16-05-2022*

Rewterz Threat Update Costa Rica Announces A State Of Emergency Following The Conti Ransomware Groups Attacks

https://www.rewterz.com/rewterz-news/rewterz-threat-update-costa-rica-announces-a-state-of-emergency-following-the-conti-ransomware-groups-attacks

*Threats*:
Conti (tags: malware)

*Industry*:
E-commerce, Government, Financial

*Geo*:
Peru

*TTPs*:
Tactics: 1
Technics: 0

