#ParsedReport
*06-05-2022*

Rewterz Threat Update Russian State-Sponsored and Criminal Cyber Threats to Critical Infrastructure Russian-Ukrainian Cyber Warfare

https://www.rewterz.com/rewterz-news/rewterz-threat-update-russian-state-sponsored-and-criminal-cyber-threats-to-critical-infrastructure-russian-ukrainian-cyber-warfare

*Actors/Campaigns*:
Duke
Fancy\_bear (tags: phishing, malware)
Gamaredon (tags: malware)
Darkhalo

*Threats*:
Conti (tags: ransomware)
Smokeloader\_backdoor (tags: malware)
Seaduke
Empire\_loader
Trickbot

*Industry*:
E-commerce, Government

*Geo*:
America, Germany, Ukraine, Australia, Russia, Uzbekistan, Canada, Korea, Asia, Russian

*CVEs*:
CVE-2021-40444  \[[Vulners](https://vulners.com/cve/CVE-2021-40444)]
    Vulners: Score: *6.8*, CVSS: *2.1*, 
    Vulners: Exploitation: True
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows 10 (-, 20h2, 21h1, 1607, 1809, 1909, 2004)
    - microsoft windows 7 (-)
    - microsoft windows 8.1 (-)
    - microsoft windows rt 8.1 (-)
    - microsoft windows server 2008 (-, r2)
    have more...

*TTPs*:
Tactics: 1
Technics: 0

