#ParsedReport
*18-04-2022*

Rewterz Threat Advisory Multiple Cisco Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-cisco-vulnerabilities-6

*CVEs*:
CVE-2022-20682  \[[Vulners](https://vulners.com/cve/CVE-2022-20682)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.6*
    X-Force: Patch: Official fix

CVE-2022-20731  \[[Vulners](https://vulners.com/cve/CVE-2022-20731)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.8*
    X-Force: Patch: Official fix

CVE-2022-20692  \[[Vulners](https://vulners.com/cve/CVE-2022-20692)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.7*
    X-Force: Patch: Official fix

CVE-2022-20722  \[[Vulners](https://vulners.com/cve/CVE-2022-20722)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix

CVE-2022-20724  \[[Vulners](https://vulners.com/cve/CVE-2022-20724)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix

CVE-2022-20720  \[[Vulners](https://vulners.com/cve/CVE-2022-20720)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-20693  \[[Vulners](https://vulners.com/cve/CVE-2022-20693)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.7*
    X-Force: Patch: Official fix

CVE-2022-20676  \[[Vulners](https://vulners.com/cve/CVE-2022-20676)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.1*
    X-Force: Patch: Official fix

CVE-2022-20694  \[[Vulners](https://vulners.com/cve/CVE-2022-20694)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.8*
    X-Force: Patch: Official fix

CVE-2022-20727  \[[Vulners](https://vulners.com/cve/CVE-2022-20727)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.1*
    X-Force: Patch: Official fix

CVE-2022-20723  \[[Vulners](https://vulners.com/cve/CVE-2022-20723)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-20678  \[[Vulners](https://vulners.com/cve/CVE-2022-20678)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.6*
    X-Force: Patch: Official fix

CVE-2022-20681  \[[Vulners](https://vulners.com/cve/CVE-2022-20681)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-20679  \[[Vulners](https://vulners.com/cve/CVE-2022-20679)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.8*
    X-Force: Patch: Official fix

CVE-2022-20739  \[[Vulners](https://vulners.com/cve/CVE-2022-20739)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Official fix

CVE-2022-20721  \[[Vulners](https://vulners.com/cve/CVE-2022-20721)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix

CVE-2022-20677  \[[Vulners](https://vulners.com/cve/CVE-2022-20677)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.1*
    X-Force: Patch: Official fix

CVE-2022-20661  \[[Vulners](https://vulners.com/cve/CVE-2022-20661)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.6*
    X-Force: Patch: Official fix

CVE-2022-20761  \[[Vulners](https://vulners.com/cve/CVE-2022-20761)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.4*
    X-Force: Patch: Official fix

CVE-2022-20725  \[[Vulners](https://vulners.com/cve/CVE-2022-20725)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-20683  \[[Vulners](https://vulners.com/cve/CVE-2022-20683)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.6*
    X-Force: Patch: Official fix

CVE-2022-20717  \[[Vulners](https://vulners.com/cve/CVE-2022-20717)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-20714  \[[Vulners](https://vulners.com/cve/CVE-2022-20714)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.6*
    X-Force: Patch: Official fix

CVE-2022-20716  \[[Vulners](https://vulners.com/cve/CVE-2022-20716)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-20726  \[[Vulners](https://vulners.com/cve/CVE-2022-20726)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix

CVE-2022-20719  \[[Vulners](https://vulners.com/cve/CVE-2022-20719)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-20718  \[[Vulners](https://vulners.com/cve/CVE-2022-20718)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.5*
    X-Force: Patch: Official fix

CVE-2022-20697  \[[Vulners](https://vulners.com/cve/CVE-2022-20697)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.6*
    X-Force: Patch: Official fix

CVE-2022-20622  \[[Vulners](https://vulners.com/cve/CVE-2022-20622)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.6*
    X-Force: Patch: Official fix

CVE-2022-20758  \[[Vulners](https://vulners.com/cve/CVE-2022-20758)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.8*
    X-Force: Patch: Official fix

CVE-2022-20735  \[[Vulners](https://vulners.com/cve/CVE-2022-20735)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-20684  \[[Vulners](https://vulners.com/cve/CVE-2022-20684)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.4*
    X-Force: Patch: Official fix

CVE-2022-20695  \[[Vulners](https://vulners.com/cve/CVE-2022-20695)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *10*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 3
Technics: 0

