#ParsedReport
*21-05-2022*

Rewterz Threat Advisory CVE-2022-22325 IBM MQ Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-22325-ibm-mq-vulnerability

*CVEs*:
CVE-2022-22325  \[[Vulners](https://vulners.com/cve/CVE-2022-22325)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

