#ParsedReport
*25-04-2022*

Check Point Research detects vulnerability in the Everscale blockchain wallet, preventing cryptocurrency theft

https://research.checkpoint.com/2022/check-point-research-detects-vulnerability-in-the-everscale-blockchain-wallet-preventing-cryptocurrency-theft

*Industry*:
Financial

*IOCs*:
File: 7
Hash: 1

*Links*:
`https://github.com/react-native-device-info/react-native-device-info`
`https://github.com/tonlabs/TON-SDK/blob/master/docs/reference/types-and-methods/mod\_crypto.md#nacl\_secret\_box\_open`
`https://github.com/react-native-device-info/react-native-device-info#getuniqueid`
`https://github.com/tonlabs/TON-SDK/blob/master/docs/reference/types-and-methods/mod\_crypto.md#scrypt`