#ParsedReport
*16-05-2022*

Rewterz Threat Advisory ICS: Multiple Siemens JT2Go and Teamcenter Visualization Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-ics-multiple-siemens-jt2go-and-teamcenter-visualization-vulnerabilities

*Industry*:
Ics

*CVEs*:
CVE-2022-29032  \[[Vulners](https://vulners.com/cve/CVE-2022-29032)]
CVE-2022-29033  \[[Vulners](https://vulners.com/cve/CVE-2022-29033)]
CVE-2022-29031  \[[Vulners](https://vulners.com/cve/CVE-2022-29031)]
CVE-2022-29029  \[[Vulners](https://vulners.com/cve/CVE-2022-29029)]
CVE-2022-29030  \[[Vulners](https://vulners.com/cve/CVE-2022-29030)]
CVE-2022-29028  \[[Vulners](https://vulners.com/cve/CVE-2022-29028)]

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 3

