#ParsedReport
*19-05-2022*

Twisted Panda: Chinese APT espionage operation against Russians state-owned defense institutes. Introduction

https://research.checkpoint.com/2022/twisted-panda-chinese-apt-espionage-operation-against-russians-state-owned-defense-institutes

*Actors/Campaigns*:
Stone\_panda (tags: backdoor)
Red\_delta (tags: backdoor)

*Threats*:
Plugx\_rat (tags: backdoor)
Hodur\_rat (tags: backdoor)

*Industry*:
Energy, Healthcare, Aerospace

*Geo*:
Belarus, China, Ukraine, Russia, Chinas, Chinese, Russian

*IOCs*:
Domain: 5
Url: 1
File: 10
Hash: 19
IP: 1

*YARA*: Found

