#ParsedReport
*02-06-2022*

Hacker group "Ocean Lotus" combat weapon "Buni" latest exposure, targeting Linux platform

https://mp-weixin-qq-com.translate.goog/s/zHLY81XeNL8afYaPtd0Myw?\_x\_tr\_sl=zh-CN&\_x\_tr\_tl=en&\_x\_tr\_hl=en

*Actors/Campaigns*:
Oceanlotus (tags: backdoor, trojan, malware)
Blacktech

*Threats*:
Doubleheaded\_dragon
Wannacry

*Industry*:
Government, Iot, Transport, Financial, Energy, Healthcare

*Geo*:
China, Asia

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
IP: 1

