#ParsedReport
*04-04-2022*

FIN7 Power Hour: Adversary Archaeology and the Evolution of FIN7

https://www.mandiant.com/resources/evolution-of-fin7

*Actors/Campaigns*:
Carbanak (tags: scan, dropper, ransomware, dns, malware, backdoor, phishing, rat, proxy)
Darkside (tags: ransomware)
Blackmatter
Fin12

*Threats*:
Revil
Blackcat (tags: ransomware)
Powerplant
Birdwatch\_loader
Fowlgaze
Loadout\_loader
Griffon
Badusb\_technique
Dice\_loader
Killack
Powertrash\_tool
Supersoft
Pillowmint
Powersploit
Termite
Metasploit\_tool
Bughatch
Cobalt\_strike
Kerberoasting\_technique
Hello
Atera\_agent
Easylook\_tool
Boatlaunch\_tool
Jssloader
Maze (tags: ransomware)
Ryuk (tags: ransomware)
Bateleur
Driftpin

*Industry*:
Financial, Healthcare, Telco

*TTPs*:
Tactics: 10
Technics: 53

*IOCs*:
Path: 4
File: 28
Hash: 34
Coin: 1
Domain: 15

*Links*:
`https://github.com/monoxgas/sRDI`
`https://github.com/PowerShellMafia/PowerSploit/blob/master/CodeExecution/Invoke-Shellcode.ps1`