#ParsedReport
*03-04-2022*

PlugX: A Talisman to Behold

https://www.trellix.com/en-us/about/newsroom/stories/threat-labs/plugx-a-talisman-to-behold.html

*Actors/Campaigns*:
Redfoxtrot

*Threats*:
Plugx\_rat (tags: rat, dns, malware, backdoor, scan)
Thor
Pcshare

*Industry*:
Telco

*Geo*:
Asia, China, Africa, Chinas, Asian, Chinese

*TTPs*:
Tactics: 3
Technics: 14

*IOCs*:
File: 13
Path: 2
Domain: 10
Hash: 19
IP: 18

