#ParsedReport
*13-04-2022*

Rewterz Threat Advisory CVE-2022-24437 Node.js git-pull-or-clone module Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-24437-node-js-git-pull-or-clone-module-vulnerability

*CVEs*:
CVE-2022-24437  \[[Vulners](https://vulners.com/cve/CVE-2022-24437)]

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 1

*Links*:
`https://github.com/feross/git-pull-or-clone/commit/f9ce092be13cc32e685dfa26e7705e9c6e3108a3`