#ParsedReport
*21-05-2022*

Rewterz Threat Advisory Multiple SonicWall SMA1000 series Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-sonicwall-sma1000-series-vulnerabilities

*CVEs*:
CVE-2022-1702  \[[Vulners](https://vulners.com/cve/CVE-2022-1702)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2022-22282  \[[Vulners](https://vulners.com/cve/CVE-2022-22282)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.2*
    X-Force: Patch: Official fix

CVE-2022-1701  \[[Vulners](https://vulners.com/cve/CVE-2022-1701)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.7*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

