#ParsedReport
*25-04-2022*

Rewterz Threat Advisory ICS: Johnson Controls Metasys SCT Pro Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-ics-johnson-controls-metasys-sct-pro-vulnerability

*Industry*:
Ics

*CVEs*:
CVE-2021-36203  \[[Vulners](https://vulners.com/cve/CVE-2021-36203)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

