#ParsedReport
*19-05-2022*

Rise in XorDdos: A deeper look at the stealthy DDoS malware targeting Linux devices

https://www.microsoft.com/security/blog/2022/05/19/rise-in-xorddos-a-deeper-look-at-the-stealthy-ddos-malware-targeting-linux-devices

*Threats*:
Xorddos (tags: phishing, cryptomining, botnet, scam, dns, backdoor, rootkit, malware, rat, ddos, trojan)
Tsunami\_botnet (tags: ddos, malware)
Xmrig\_miner (tags: ddos, malware)

*Industry*:
Iot

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 6
Url: 1
Hash: 17
Domain: 2

*Links*:
`https://github.com/jermeyyy/rooty`