#ParsedReport
*29-05-2022*

Rewterz Threat Advisory Multiple GitLab Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-gitlab-vulnerabilities-3

*CVEs*:
CVE-2022-1423  \[[Vulners](https://vulners.com/cve/CVE-2022-1423)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.1*
    X-Force: Patch: Official fix

CVE-2022-1416  \[[Vulners](https://vulners.com/cve/CVE-2022-1416)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix

CVE-2022-1413  \[[Vulners](https://vulners.com/cve/CVE-2022-1413)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

