#ParsedReport
*28-04-2022*

BRONZE PRESIDENT Targets Russian Speakers with Updated PlugX

https://www.secureworks.com/blog/bronze-president-targets-russian-speakers-with-updated-plugx

*Actors/Campaigns*:
Red\_delta (tags: malware, rat, dns)

*Threats*:
Plugx\_rat (tags: rat, malware, dns)

*Geo*:
Poland, Belarus, Russian, Myanmar, Asia, Ukraine, Chinas, Lithuania, Vietnam, China, Latvia

*IOCs*:
File: 1
Path: 1
IP: 3
Hash: 4

