#ParsedReport
*29-05-2022*

Rewterz Threat Advisory Multiple Mozilla Firefox, Firefox ESR, Firefox for Android and Thunderbird Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-mozilla-firefox-firefox-esr-firefox-for-android-and-thunderbird-vulnerabilities

*CVEs*:
CVE-2022-1802  \[[Vulners](https://vulners.com/cve/CVE-2022-1802)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1529  \[[Vulners](https://vulners.com/cve/CVE-2022-1529)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

