#ParsedReport
*28-04-2022*

eSentire Threat Intelligence Malware Analysis: SolarMarker

https://www.esentire.com/blog/esentire-threat-intelligence-malware-analysis-solarmarker

*Threats*:
Solarmarker (tags: rat, dns, backdoor, stealer, malware, phishing, vpn)
Fingerprintjs\_tool
Velar
Arkei\_stealer
Exodus (tags: stealer)
Grateful\_pos (tags: stealer)

*Geo*:
Emea, Russian, America, Apac, Africa

*IOCs*:
File: 5
Path: 1
IP: 10
Hash: 14

*YARA*: Found

*Links*:
`https://github.com/nicolauns/hunter-php-javascript-obfuscator`