#ParsedReport
*27-04-2022*

Microsoft finds new elevation of privilege Linux vulnerability, Nimbuspwn

https://www.microsoft.com/security/blog/2022/04/26/microsoft-finds-new-elevation-of-privilege-linux-vulnerability-nimbuspwn

*Threats*:
Nimbuspwn\_vuln (tags: ransomware, rat, malware, backdoor)
Toctou\_vuln

*CVEs*:
CVE-2022-29800  \[[Vulners](https://vulners.com/cve/CVE-2022-29800)]
CVE-2022-29799  \[[Vulners](https://vulners.com/cve/CVE-2022-29799)]
CVE-2022-0987  \[[Vulners](https://vulners.com/cve/CVE-2022-0987)]

*IOCs*:
File: 3

*Links*:
`https://github.com/blueman-project/blueman/security/advisories/GHSA-3r9p-m5c8-8mw8`