#ParsedReport
*23-05-2022*

A peek behind the BPFDoor

https://elastic.github.io/security-research/intelligence/2022/05/04.bpfdoor/article

*Threats*:
Bpfdoor (tags: rat, malware, vpn, scan, backdoor)
Bvp47

*Industry*:
Logistic, Iot, Telco, Ics, Government, Education

*Geo*:
Myanmar, India, Korea, Turkey, Taiwan, Asia, Vietnam, China

*TTPs*:
Tactics: 3
Technics: 0

*IOCs*:
Hash: 15

*YARA*: Found

*Links*:
`https://github.com/elastic/detection-rules/blob/main/rules/linux/execution\_process\_started\_in\_shared\_memory\_directory.toml`
`https://github.com/rhysre`
`https://github.com/elastic/detection-rules/blob/main/rules/linux/execution\_abnormal\_process\_id\_file\_created.toml`
`https://github.com/DefSecSentinel`
`https://github.com/jtnk`
`https://github.com/tabell`