*25-03-2022*
Conti Ransomware Attacks Persist With an Updated Version Despite Leaks. Indicators of Compromise. Zscaler Cloud Sandbox Detection. Conclusion. Technical Analysis

https://www.zscaler.com/blogs/security-research/conti-ransomware-attacks-persist-updated-version-despite-leaks

*Threats*:
Conti (tags: malware, ransomware)
Maze

*Geo*:
Ukraine, Ukrainian

*IOCs*:
File: 3
Registry: 1
Path: 1
Url: 1
Hash: 5