#ParsedReport
*16-05-2022*

Fake Mobile Apps Steal Facebook Credentials, Cryptocurrency-Related Keys. Password-stealing Facestealer variants disguised as fitness, photo editing, and other apps

https://www.trendmicro.com/en\_us/research/22/e/fake-mobile-apps-steal-facebook-credentials--crypto-related-keys.html

*Threats*:
Facestealer (tags: cryptomining, vpn, scan, phishing, malware, spyware)
Joker
Agent\_tesla (tags: cryptomining)
Plaguebot

*Industry*:
Financial

*TTPs*:
Tactics: 4
Technics: 0

*IOCs*:
Url: 2
Hash: 9

