#ParsedReport
*04-05-2022*

Operation CuckooBees: Cybereason Uncovers Massive Chinese Intellectual Property Theft Operation

https://www.cybereason.com/blog/operation-cuckoobees-cybereason-uncovers-massive-chinese-intellectual-property-theft-operation

*Actors/Campaigns*:
Axiom (tags: malware)

*Threats*:
Deploylog
Spyder
Privatelog
Winnkit
Stashlog
Eternal\_petya

*Industry*:
Government, E-commerce

*Geo*:
America, Asia, Chinese, China

