*23-03-2022*
Mustang Pandas Hodur: Old tricks, new Korplug variant

https://www.welivesecurity.com/2022/03/23/mustang-panda-hodur-old-tricks-new-korplug-variant

*Actors/Campaigns*:
Red\_delta (malware, rat, dns, phishing, backdoor)

*Threats*:
Hodur\_rat (malware, rat, dns, phishing, backdoor)
Plugx\_rat (malware, rat, dns, phishing, backdoor)
Thor (backdoor)
Cobalt\_strike
Poison\_ivy
Watering\_hole\_technique
Sunburst
Delf

*Industry*:
Media, Telco, Government

*Geo*:
Cyprus, Greece, Sudan, Asia, Mongolia, Africa, Myanmar, Ukraines, Vietnam, Russia, African, Ukraine

*TTPs*:
Tactics: 9
Technics: 44

*IOCs*:
File: 5
IP: 10
Hash: 28
Domain: 4

*Links*:
https://github.com/kcreyts/plugxdecoder