#ParsedReport
*04-04-2022*

Spring4Shell (CVE-2022-22965): details and mitigations

https://securelist.com/spring4shell-cve-2022-22965/106239

*Threats*:
Spring4shell (tags: malware)
Log4shell\_vuln

*CVEs*:
CVE-2022-22963  \[[Vulners](https://vulners.com/cve/CVE-2022-22963)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix

CVE-2010-1622  \[[Vulners](https://vulners.com/cve/CVE-2010-1622)]
    Vulners: Score: *6.0*, CVSS: *7.3*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix
    Soft:
    - oracle fusion middleware (11.1.1.8.0, 7.6.2, 11.1.1.6.1)
    - springsource spring framework (2.5.6, 2.5.7, 2.5.2, 2.5.3, 3.0.0, 2.5.0, 2.5.1, 3.0.2, 3.0.1, 2.5.4, 2.5.5)

CVE-2022-22965  \[[Vulners](https://vulners.com/cve/CVE-2022-22965)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix


*IOCs*:
Hash: 2
File: 1

