#ParsedReport
*06-05-2022*

Rewterz Threat Advisory IBM Planning Analytics Workspace Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-ibm-planning-analytics-workspace-vulnerabilities

*CVEs*:
CVE-2022-22392  \[[Vulners](https://vulners.com/cve/CVE-2022-22392)]
    Vulners: Score: *6.8*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.8*
    X-Force: Patch: Official fix
    Soft:
    - ibm planning analytics workspace (2.0)

CVE-2021-39040  \[[Vulners](https://vulners.com/cve/CVE-2021-39040)]
    Vulners: Score: *6.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.3*
    X-Force: Patch: Official fix
    Soft:
    - ibm planning analytics workspace (2.0)


*TTPs*:
Tactics: 2
Technics: 0

