#ParsedReport
*08-05-2022*

Rewterz Threat Alert Docker Engine Honeypots Used in Attacks on Russia Active IOCs Russian-Ukrainian Cyber Warfare

https://www.rewterz.com/rewterz-news/rewterz-threat-alert-docker-engine-honeypots-used-in-attacks-on-russia-active-iocs-russian-ukrainian-cyber-warfare

*Industry*:
Government

*Geo*:
Russia, Belarusian, Russian, Ukraine

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
Hash: 3

