#ParsedReport
*28-04-2022*

This isn't Optimus Prime's Bumblebee but it's Still Transforming

https://www.proofpoint.com/us/blog/threat-insight/bumblebee-is-still-transforming

*Threats*:
Bumblebee (tags: botnet, malware, ransomware, trojan, rat)
Bazarbackdoor (tags: malware)
Icedid
Cobalt\_strike
Sliver\_tool
Meterpreter\_tool
Conti (tags: malware)
Diavol
Prometheus
Kpot\_stealer
Buer\_loader
Gozi

*Industry*:
Financial

*Geo*:
Ukrainian

*IOCs*:
File: 13
Hash: 5

*Links*:
`https://github.com/LordNoteworthy/al-khaser/blob/06d4a89e9ecc3e49e4d2df67fe0b2d6faf04166e/al-khaser/Shared/Utils.cpp#L950`