#ParsedReport
*18-04-2022*

Rewterz Threat Alert ICS/SCADA Devices Under Attack Using APT Tools

https://www.rewterz.com/rewterz-news/rewterz-threat-alert-ics-scada-devices-under-attack-using-apt-tools

*Industry*:
Ics, Financial, Energy

*CVEs*:
CVE-2020-15368  \[[Vulners](https://vulners.com/cve/CVE-2020-15368)]
    Vulners: Score: *2.1*, CVSS: *4.0*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.2*
    X-Force: Patch: Unavailable
    Soft:
    - asrock rgb driver firmware (-)


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 1

