#ParsedReport
*22-05-2022*

Rewterz Threat Advisory CVE-2022-26923 Microsoft Windows Active Directory Domain Services Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-26923-microsoft-windows-active-directory-domain-services-vulnerability

*CVEs*:
CVE-2022-26923  \[[Vulners](https://vulners.com/cve/CVE-2022-26923)]
    Vulners: Score: *9.0*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix
    Soft:
    - microsoft windows 10 (-, 1607, -, 1607, 1809, 1809, 20h2, 20h2, 20h2, 21h1, 21h1, 21h1, 21h2, 21h2, 21h2, 1809, 1909, 1909, 1909)
    - microsoft windows server 2012 (r2)
    - microsoft windows server 2016 (-)
    - microsoft windows 8.1 (-, -)
    - microsoft windows server 2019 (-)
    have more...

*TTPs*:
Tactics: 2
Technics: 0

