#ParsedReport
*22-05-2022*

Rewterz Threat Advisory CVE-2022-26650 Apache ShenYu Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-26650-apache-shenyu-vulnerability

*CVEs*:
CVE-2022-26650  \[[Vulners](https://vulners.com/cve/CVE-2022-26650)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

*Links*:
`https://github.com/apache/incubator-shenyu/pull/2975`