#ParsedReport
*18-04-2022*

An Investigation of the BlackCat Ransomware via Trend Micro Vision One. Finding the threats

https://www.trendmicro.com/en\_us/research/22/d/an-investigation-of-the-blackcat-ransomware.html

*Threats*:
Blackcat (tags: backdoor, scan, dns, ransomware, malware, rat)
Cobalt\_strike (tags: ransomware)
Proxyshell\_vuln
Proxylogon\_exploit
Netscan\_tool
Bloodhound\_tool
Crackmapexec\_tool
Mimikatz
Lolbin

*CVEs*:
CVE-2021-31207  \[[Vulners](https://vulners.com/cve/CVE-2021-31207)]
    Vulners: Score: *6.5*, CVSS: *2.8*, 
    Vulners: Exploitation: True
    X-Force: Risk: *6.6*
    X-Force: Patch: Official fix
    Soft:
    - microsoft exchange server (2013, 2016, 2016, 2019, 2019)

CVE-2021-34523  \[[Vulners](https://vulners.com/cve/CVE-2021-34523)]
    Vulners: Score: *7.5*, CVSS: *6.4*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9*
    X-Force: Patch: Official fix
    Soft:
    - microsoft exchange server (2013, 2016, 2016, 2019, 2019)

CVE-2021-34473  \[[Vulners](https://vulners.com/cve/CVE-2021-34473)]
    Vulners: Score: *10.0*, CVSS: *6.4*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.1*
    X-Force: Patch: Official fix
    Soft:
    - microsoft exchange server (2013, 2016, 2016, 2019, 2019)


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 13
IP: 2
Path: 1
Hash: 25
Domain: 1

*Links*:
`https://github.com/Kevin-Robertson/Inveigh`