#ParsedReport
*18-04-2022*

Microsoft releases open-source tool for securing MikroTik routers

https://cybersecurity.att.com/blogs/security-essentials/microsoft-releases-open-source-tool-for-securing-mikrotik-routers

*Threats*:
Trickbot (tags: malware, trojan)
Ryuk

*Industry*:
Iot, Government

*Geo*:
Ukrainian, Russia

*CVEs*:
CVE-2018-14847  \[[Vulners](https://vulners.com/cve/CVE-2018-14847)]
    Vulners: Score: *6.4*, CVSS: *4.6*, 
    Vulners: Exploitation: True
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix
    Soft:
    - mikrotik routeros (le6.42)


*IOCs*:
File: 1

