#ParsedReport
*27-04-2022*

LockBit Ransomware Side-loads Cobalt Strike Beacon with Legitimate VMware Utility

https://www.sentinelone.com/labs/lockbit-ransomware-side-loads-cobalt-strike-beacon-with-legitimate-vmware-utility

*Threats*:
Cobalt\_strike (tags: malware, scan, ransomware, rat)
Lockbit (tags: malware, scan, ransomware, rat)
Reflectiveloader
Stealbit

*TTPs*:

*IOCs*:
File: 4
Path: 6
Url: 3
Hash: 6
IP: 2

*YARA*: Found

