#ParsedReport
*08-05-2022*

Rewterz Threat Advisory CVE-2022-28193 NVIDIA Jetson Linux Driver Package Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-28193-nvidia-jetson-linux-driver-package-vulnerability

*CVEs*:
CVE-2022-28193  \[[Vulners](https://vulners.com/cve/CVE-2022-28193)]
    Vulners: Score: *4.6*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.3*
    X-Force: Patch: Official fix
    Soft:
    - nvidia jetson linux (<32.7.2)


*TTPs*:
Tactics: 2
Technics: 0

