#ParsedReport
*05-05-2022*

"Excuse me, how will the conflict between Russia and Ukraine affect the situation on the peninsula?" Analysis of the recent targeted attack activities of APT organization Kimsuky

https://blog-nsfocus-net.translate.goog/apt-kimsuky-3/?\_x\_tr\_sch=http&\_x\_tr\_sl=auto&\_x\_tr\_tl=en&\_x\_tr\_hl=ru&\_x\_tr\_pto=wapp

*Actors/Campaigns*:
Kimsuky (tags: trojan, phishing, malware)

*Geo*:
Ukraine, Korea, Russia

*IOCs*:
File: 27
Url: 7
Path: 1

