#ParsedReport
*17-04-2022*

Rewterz Threat Advisory CVE-2022-0023 Palo Alto Networks PAN-OS Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-0023-palo-alto-networks-pan-os-vulnerability

*CVEs*:
CVE-2022-0023  \[[Vulners](https://vulners.com/cve/CVE-2022-0023)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *5.9*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

