#ParsedReport
*29-04-2022*

Rewterz Threat Advisory ICS: Hitachi Energy MicroSCADA Pro/X SYS600

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-ics-hitachi-energy-microscada-pro-x-sys600

*Threats*:
Raccoon\_stealer

*Industry*:
Ics, Energy

*CVEs*:
CVE-2020-8174  \[[Vulners](https://vulners.com/cve/CVE-2020-8174)]
    Vulners: Score: *9.3*, CVSS: *5.2*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - nodejs node.js (<10.21.0, <12.18.0, <14.4.0)
    - oracle banking extensibility workbench (14.3.0, 14.4.0)
    - oracle mysql cluster (le7.3.30, le7.4.29, le7.5.19, le7.6.15, le8.0.21)
    - oracle retail xstore point of service (16.0.6, 17.0.4, 18.0.3, 19.0.2, 20.0.1)
    - netapp active iq unified manager (-, -)
    have more...
CVE-2020-8172  \[[Vulners](https://vulners.com/cve/CVE-2020-8172)]
    Vulners: Score: *5.8*, CVSS: *2.7*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *Unknown*
    X-Force: Patch: Unknown
    Soft:
    - nodejs node.js (<12.18.0, <14.4.0)

CVE-2020-8201  \[[Vulners](https://vulners.com/cve/CVE-2020-8201)]
    Vulners: Score: *5.8*, CVSS: *4.9*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.4*
    X-Force: Patch: Official fix
    Soft:
    - nodejs node.js (<12.18.4, <14.11.0)
    - opensuse leap (15.2)

CVE-2020-8265  \[[Vulners](https://vulners.com/cve/CVE-2020-8265)]
    Vulners: Score: *6.8*, CVSS: *4.7*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix
    Soft:
    - nodejs node.js (<10.23.1, <12.20.1, <14.15.4, <15.5.1)
    - debian debian linux (10.0)
    - fedoraproject fedora (32, 33)
    - oracle graalvm (19.3.4, 20.3.0)
    - siemens sinec infrastructure network services (<1.0.1.1)
    have more...
CVE-2020-8287  \[[Vulners](https://vulners.com/cve/CVE-2020-8287)]
    Vulners: Score: *6.4*, CVSS: *2.7*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.4*
    X-Force: Patch: Official fix
    Soft:
    - nodejs node.js (<10.23.1, <12.20.1, <14.15.4, <15.5.1)
    - debian debian linux (10.0)
    - fedoraproject fedora (32, 33)
    - oracle graalvm (19.3.4, 20.3.0)
    - siemens sinec infrastructure network services (<1.0.1.1)
    have more...
CVE-2020-1968  \[[Vulners](https://vulners.com/cve/CVE-2020-1968)]
    Vulners: Score: *4.3*, CVSS: *4.3*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *3.7*
    X-Force: Patch: Official fix
    Soft:
    - openssl (le1.0.2v)
    - canonical ubuntu linux (16.04, 18.04)
    - debian debian linux (9.0)
    - oracle jd edwards world security (a9.4)
    - oracle peoplesoft enterprise peopletools (8.56, 8.57, 8.58)
    have more...
CVE-2021-32028  \[[Vulners](https://vulners.com/cve/CVE-2021-32028)]
    Vulners: Score: *4.0*, CVSS: *3.0*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix
    Soft:
    - postgresql (<9.6.22, <10.17, <11.12, <12.7, <13.3)

CVE-2021-32027  \[[Vulners](https://vulners.com/cve/CVE-2021-32027)]
    Vulners: Score: *6.5*, CVSS: *3.5*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix
    Soft:
    - postgresql (<9.6.22, <10.17, <11.12, <12.7, <13.3)
    - redhat jboss enterprise application platform (7.0.0)
    - redhat software collections (-)
    - redhat enterprise linux (7.0, 8.0)

CVE-2020-8252  \[[Vulners](https://vulners.com/cve/CVE-2020-8252)]
    Vulners: Score: *4.6*, CVSS: *4.8*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *Unknown*
    X-Force: Patch: Unknown
    Soft:
    - nodejs node.js (<10.22.1, <12.18.4, <14.9.0)
    - opensuse leap (15.2)


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 1

