#ParsedReport
*22-04-2022*

Rewterz Threat Advisory CVE-2022-1254 McAfee Skyhigh SWG Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-1254-mcafee-skyhigh-swg-vulnerability

*CVEs*:
CVE-2022-1254  \[[Vulners](https://vulners.com/cve/CVE-2022-1254)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
IP: 1

