#ParsedReport
*02-06-2022*

YourCyanide: A CMD-based Ransomware With Multiple Layers of Obfuscation. YourCyanide technical analysis

https://www.trendmicro.com/en\_us/research/22/f/yourcyanide-a-cmd-based-ransomware.html

*Threats*:
Passview\_tool
Ransom.win32.gonnacope.yxcew
Trojan.vbs.gonnacope.a
Trojan.win64.kekpop.yxcet
Trojan.win64.kekpop.yxcest
Trojan.win64.kekpop.yxcert

*Industry*:
Financial

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 27
Url: 2
Registry: 2
Hash: 56

*Functions Names*: 1

