#ParsedReport
*22-05-2022*

Rewterz Threat Advisory CVE-2022-26724 Apple tvOS Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-26724-apple-tvos-vulnerability

*CVEs*:
CVE-2022-26724  \[[Vulners](https://vulners.com/cve/CVE-2022-26724)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.2*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

