#ParsedReport
*27-04-2022*

Hive0117 Continues Fileless Malware Delivery in Eastern Europe

https://securityintelligence.com/posts/hive00117-fileless-malware-delivery-eastern-europe

*Actors/Campaigns*:
Hive0117 (tags: keylogger, malware, trojan, phishing, rat, backdoor)

*Threats*:
Darkwatchman (tags: malware)

*Industry*:
Telco, Financial, Energy, Logistic, Government

*Geo*:
German, Ukraine, Lithuania, Estonia, Russia, Russian

*IOCs*:
Domain: 3
File: 4
IP: 2
Email: 1
Url: 1
Hash: 7

