#ParsedReport
*16-05-2022*

Rewterz Threat Advisory SAP Employee Self Service Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-sap-employee-self-service-vulnerability

*CVEs*:
CVE-2022-29613  \[[Vulners](https://vulners.com/cve/CVE-2022-29613)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 1
Technics: 0

