#ParsedReport
*14-04-2022*

Rewterz Threat Advisory Multiple Apache Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-apache-vulnerabilities-12

*CVEs*:
CVE-2021-31805  \[[Vulners](https://vulners.com/cve/CVE-2021-31805)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.1*
    X-Force: Patch: Official fix

CVE-2021-28544  \[[Vulners](https://vulners.com/cve/CVE-2021-28544)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.3*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

