#ParsedReport
*16-05-2022*

Rewterz Threat Advisory Multiple Google Chrome Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-google-chrome-vulnerabilities-21

*CVEs*:
CVE-2022-1640  \[[Vulners](https://vulners.com/cve/CVE-2022-1640)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1635  \[[Vulners](https://vulners.com/cve/CVE-2022-1635)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1638  \[[Vulners](https://vulners.com/cve/CVE-2022-1638)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1637  \[[Vulners](https://vulners.com/cve/CVE-2022-1637)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1636  \[[Vulners](https://vulners.com/cve/CVE-2022-1636)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1634  \[[Vulners](https://vulners.com/cve/CVE-2022-1634)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1633  \[[Vulners](https://vulners.com/cve/CVE-2022-1633)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1639  \[[Vulners](https://vulners.com/cve/CVE-2022-1639)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix

CVE-2022-1641  \[[Vulners](https://vulners.com/cve/CVE-2022-1641)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *8.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

