#ParsedReport
*21-04-2022*

LemonDuck Targets Docker for Cryptomining Operations

https://www.crowdstrike.com/blog/lemonduck-botnet-targets-docker-for-cryptomining-operations

*Threats*:
Lemonduck (tags: botnet, proxy, dropper, rat, cryptomining, malware)
Proxylogon\_exploit
Eternalblue\_vuln
Bluekeep\_vuln
Cr8escape\_vuln
Xmrig\_miner (tags: proxy)

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 2
Domain: 1

*Links*:
`https://github.com/xmrig/xmrig-proxy`