#ParsedReport
*23-05-2022*

Spoofed Saudi Purchase Order Drops GuLoader: Part 1

https://www.fortinet.com/blog/threat-research/spoofed-saudi-purchase-order-drops-guloader

*Threats*:
Cloudeye (tags: spam, ransomware, rat, phishing, malware)
Chaos
Agent\_tesla
Formbook
Lokibot\_stealer

*Industry*:
Energy, Petroleum

*Geo*:
Russia, Arabia, Saudi, Ukraine

*IOCs*:
Email: 1
Domain: 1
File: 1
Hash: 3

*Links*:
`https://github.com/myfreeer/7z-build-nsis`