#ParsedReport
*22-04-2022*

Threat Thursday: BlackGuard Infostealer Rises from Russian Underground Markets

https://blogs.blackberry.com/en/2022/04/threat-thursday-blackguard-infostealer

*Threats*:
Blackguard\_stealer (tags: stealer, malware, ransomware, vpn)
Arkei\_stealer (tags: stealer)
Bhunt\_stealer (tags: stealer)
Exodus

*Industry*:
Financial

*Geo*:
Tajikistan, Belarus, Russian, Ireland, Ukraine, Azerbaijan, Russia, Kyrgyzstan, Uzbekistan

*TTPs*:
Tactics: 2
Technics: 0

*IOCs*:
File: 11
Path: 5
Coin: 1
Hash: 5
Url: 4

*YARA*: Found

