#ParsedReport
*08-05-2022*

Rewterz Threat Advisory Multiple Node.js Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-node-js-vulnerabilities-8

*CVEs*:
CVE-2022-30241  \[[Vulners](https://vulners.com/cve/CVE-2022-30241)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.2*
    X-Force: Patch: Official fix

CVE-2022-25324  \[[Vulners](https://vulners.com/cve/CVE-2022-25324)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.5*
    X-Force: Patch: Unavailable


*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 2

*Links*:
`https://github.com/abodelot/jquery.json-viewer/pull/26`