#ParsedReport
*08-05-2022*

Rewterz Threat Advisory Multiple Cisco Products Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-cisco-products-vulnerabilities-10

*CVEs*:
CVE-2022-20799  \[[Vulners](https://vulners.com/cve/CVE-2022-20799)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.7*
    X-Force: Patch: Official fix

CVE-2022-20753  \[[Vulners](https://vulners.com/cve/CVE-2022-20753)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.7*
    X-Force: Patch: Official fix

CVE-2022-20734  \[[Vulners](https://vulners.com/cve/CVE-2022-20734)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.4*
    X-Force: Patch: Official fix

CVE-2022-20794  \[[Vulners](https://vulners.com/cve/CVE-2022-20794)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.7*
    X-Force: Patch: Official fix

CVE-2022-20764  \[[Vulners](https://vulners.com/cve/CVE-2022-20764)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix

CVE-2022-20801  \[[Vulners](https://vulners.com/cve/CVE-2022-20801)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.7*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

