#ParsedReport
*29-05-2022*

Rewterz Threat Advisory CVE-2022-1729 Linux Kernel Vulnerability

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-cve-2022-1729-linux-kernel-vulnerability

*CVEs*:
CVE-2022-1729  \[[Vulners](https://vulners.com/cve/CVE-2022-1729)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix

CVE-2022-20821  \[[Vulners](https://vulners.com/cve/CVE-2022-20821)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.5*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

