#ParsedReport
*12-04-2022*

Attackers linger on government agency computers before deploying Lockbit ransomware

https://news.sophos.com/en-us/2022/04/12/attackers-linger-on-government-agency-computers-before-deploying-lockbit-ransomware

*Threats*:
Lockbit (tags: rat, scan, ransomware, malware, cryptomining, proxy, vpn)
Anydesk\_tool (tags: ransomware)
Mimikatz (tags: ransomware)
Screenconnect\_tool (tags: ransomware)
Psexec\_tool (tags: ransomware)
Gmer\_tool (tags: ransomware)
Iobit\_tool (tags: ransomware)
Putty\_tool (tags: ransomware)
Bogus
Lazagne
Nlbrute\_tool
Mail\_passview\_tool

*Industry*:
Government, Healthcare

*Geo*:
American, Iran, Poland, Bulgaria, Russia, Canada, Estonia

*IOCs*:
File: 2
IP: 1
Hash: 10

