#ParsedReport
*18-04-2022*

Rewterz Threat Advisory Multiple Citrix Vulnerabilities

https://www.rewterz.com/rewterz-news/rewterz-threat-advisory-multiple-citrix-vulnerabilities

*CVEs*:
CVE-2022-27505  \[[Vulners](https://vulners.com/cve/CVE-2022-27505)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2021-44520  \[[Vulners](https://vulners.com/cve/CVE-2021-44520)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix

CVE-2022-27503  \[[Vulners](https://vulners.com/cve/CVE-2022-27503)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.1*
    X-Force: Patch: Official fix

CVE-2021-44519  \[[Vulners](https://vulners.com/cve/CVE-2021-44519)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix

CVE-2022-27506  \[[Vulners](https://vulners.com/cve/CVE-2022-27506)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *4.9*
    X-Force: Patch: Official fix

CVE-2022-26151  \[[Vulners](https://vulners.com/cve/CVE-2022-26151)]
    Vulners: Score: *Unknown*, CVSS: *PENDING*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix


*TTPs*:
Tactics: 2
Technics: 0

