#ParsedReport
*27-04-2022*

A lookback under the TA410 umbrella: Its cyberespionage TTPs and activity

https://www.welivesecurity.com/2022/04/27/lookback-ta410-umbrella-cyberespionage-ttps-activity

*Actors/Campaigns*:
Ta410 (tags: rat, malware, backdoor, dropper, rootkit, proxy, phishing, keylogger)
Stone\_panda
A41apt
Equation

*Threats*:
Flowcloud\_rat (tags: rootkit, backdoor)
Plugx\_rat (tags: rat, backdoor)
Quasar\_rat (tags: backdoor)
Proxylogon\_exploit
Proxyshell\_vuln
Lolbin
Htran
Earthworm\_tool
Farfli
Gh0st\_rat
Guardrails\_tool
Metasploit\_tool
Dnguard\_tool
Rozena
Meterpreter\_tool
Eternalblue\_vuln

*Industry*:
Government, Education

*Geo*:
China, Africa, Israel, Ukraine, French, Japan, India, Asian, Asia

*CVEs*:
CVE-2017-11882  \[[Vulners](https://vulners.com/cve/CVE-2017-11882)]
    Vulners: Score: *9.3*, CVSS: *8.3*, 
    Vulners: Exploitation: True
    X-Force: Risk: *7.8*
    X-Force: Patch: Official fix
    Soft:
    - microsoft office (2013, 2010, 2016, 2007)

CVE-2019-0604  \[[Vulners](https://vulners.com/cve/CVE-2019-0604)]
    Vulners: Score: *7.5*, CVSS: *4.1*, 
    Vulners: Exploitation: True
    X-Force: Risk: *9.8*
    X-Force: Patch: Official fix
    Soft:
    - microsoft sharepoint foundation (2013)
    - microsoft sharepoint server (2019, 2010)
    - microsoft sharepoint enterprise server (2016)


*TTPs*:
Tactics: 10
Technics: 53

*IOCs*:
File: 25
Domain: 6
Hash: 43
Path: 7
Url: 7
Registry: 6
IP: 14

*YARA*: Found

*Links*:
`https://github.com/LOLBAS-Project/LOLBAS#user-content-the-history-of-the-lolbin`
`https://github.com/eset/malware-ioc`
`https://github.com/sin5678/gh0st`
`https://github.com/UndefinedIdentifier/LCX`
`https://github.com/quasar/Quasar`
`https://github.com/protocolbuffers/protobuf`
`https://github.com/a0rtega/pafish`
`https://github.com/rootkiter/EarthWorm`