#ParsedReport
*05-04-2022*

Detailed writeup on LAPSUS$ Cybercriminal Group who have compromised Microsoft and Okta

https://cloudsek.com/profile-lapsus-cybercriminal-group

*Actors/Campaigns*:
Lapsus (tags: ransomware, phishing, stealer, vpn, malware)

*Threats*:
Redline\_stealer

*Geo*:
USA, Russia, Spain, Nepal

*CVEs*:
CVE-2019-5591  \[[Vulners](https://vulners.com/cve/CVE-2019-5591)]
    Vulners: Score: *3.3*, CVSS: *4.8*, 
    Vulners: Exploitation: True
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix
    Soft:
    - fortinet fortios (le6.2.0)

CVE-2021-45328  \[[Vulners](https://vulners.com/cve/CVE-2021-45328)]
    Vulners: Score: *5.8*, CVSS: *3.3*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *7.4*
    X-Force: Patch: Official fix
    Soft:
    - gitea (<1.4.3)

CVE-2022-0510  \[[Vulners](https://vulners.com/cve/CVE-2022-0510)]
    Vulners: Score: *3.5*, CVSS: *2.2*, 
    Vulners: Exploitation: Unknown
    X-Force: Risk: *6.4*
    X-Force: Patch: Official fix
    Soft:
    - pimcore (le10.3.0)

CVE-2018-13379  \[[Vulners](https://vulners.com/cve/CVE-2018-13379)]
    Vulners: Score: *5.0*, CVSS: *4.0*, 
    Vulners: Exploitation: True
    X-Force: Risk: *7.5*
    X-Force: Patch: Official fix
    Soft:
    - fortinet fortios (le6.0.4, le5.6.7)

CVE-2020-12812  \[[Vulners](https://vulners.com/cve/CVE-2020-12812)]
    Vulners: Score: *7.5*, CVSS: *3.3*, 
    Vulners: Exploitation: True
    X-Force: Risk: *5.3*
    X-Force: Patch: Official fix
    Soft:
    - fortinet fortios (<6.0.10, <6.2.4, 6.4.0)

have more...

*TTPs*:
Tactics: 1
Technics: 0

*IOCs*:
File: 3
Hash: 11
IP: 4

