#ParsedReport
*11-05-2022*

Transparent Tribe Targets Educational Institution

https://labs.k7computing.com/index.php/transparent-tribe-targets-educational-institution

*Actors/Campaigns*:
Transparenttribe (tags: scan, keylogger, malware, trojan, rat)

*Threats*:
Crimson\_rat

*Industry*:
Government

*Geo*:
Pakistani, Indian, Pakistan

*IOCs*:
File: 1
Domain: 1
Url: 1
Hash: 2

*Links*:
`https://github.com/Rhotav/Crypto-Deobfuscator`